/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */
/* freight_ops.c — smart content: the op stream, its bounded expander, the
 * deterministic SEED generators and a greedy hash-chain LZ77 encoder.
 * See freight.h for the format, the rules and the HONEST LIMITS.
 *
 * Expansion safety, in order: the declared total is checked against the
 * caller's out_cap and limit before a byte is written; every op length is
 * checked against what is left of the declared total before it runs; every
 * varint, count and distance is bounds-checked against the input and the
 * output already produced; the stream must end exactly on an op boundary
 * with exactly the declared total produced. Each op consumes at least one
 * input byte and produces at least one output byte, so work is bounded by
 * ops_len + total. */
#include "freight.h"
#include "sha256.h"

static const uint8_t ops_magic[FREIGHT_OPS_MAGIC_LEN] = {'Z', 'X', 'O', 'P'};

static bool fr_eq(const uint8_t *a, const uint8_t *b, uint32_t n)
{
    uint8_t acc = 0;
    for (uint32_t i = 0; i < n; i++) acc |= (uint8_t) (a[i] ^ b[i]);
    return acc == 0;
}

static uint64_t get64(const uint8_t *p)
{
    uint64_t v = 0;
    for (int i = 7; i >= 0; i--) v = (v << 8) | p[i];
    return v;
}

/* LEB128, at most 10 bytes, minimal, no bits past 64. */
static bool rd_var(const uint8_t *p, uint64_t n, uint64_t *pos, uint64_t *v)
{
    uint64_t x = 0;
    for (uint32_t i = 0; i < 10; i++) {
        if (*pos >= n) return false;
        uint8_t b = p[(*pos)++];
        if (i == 9 && b > 1) return false;
        x |= (uint64_t) (b & 0x7f) << (7 * i);
        if (!(b & 0x80)) {
            if (i > 0 && b == 0) return false;
            *v = x;
            return true;
        }
    }
    return false;
}

static uint32_t var_len(uint64_t v)
{
    uint32_t n = 1;
    while (v >= 0x80) {
        v >>= 7;
        n++;
    }
    return n;
}

/* ---- generators ---- */

int freight_gen_run(uint8_t gen, const uint8_t *params, uint32_t plen, uint8_t *out, uint64_t len)
{
    if ((plen && !params) || (len && !out) || plen > FREIGHT_GEN_PARAM_MAX) return FREIGHT_ERR_ARG;
    switch (gen) {
    case FREIGHT_GEN_XORSHIFT: {
        if (plen != 8) return FREIGHT_ERR_FORMAT;
        uint64_t x = get64(params);
        if (x == 0) return FREIGHT_ERR_FORMAT;
        uint64_t i = 0;
        while (i < len) {
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            uint64_t v = x * 0x2545F4914F6CDD1DULL;
            for (uint32_t b = 0; b < 8 && i < len; b++, i++) out[i] = (uint8_t) (v >> (8 * b));
        }
        return FREIGHT_OK;
    }
    case FREIGHT_GEN_REPEAT: {
        if (plen < 1) return FREIGHT_ERR_FORMAT;
        uint32_t j = 0;
        for (uint64_t i = 0; i < len; i++) {
            out[i] = params[j];
            if (++j == plen) j = 0;
        }
        return FREIGHT_OK;
    }
    case FREIGHT_GEN_FIBWORD: {
        /* Fixed point of the morphism a -> ab, b -> a, generated by reading
         * the word's own prefix: the read index always trails the write. */
        if (plen != 2 || params[0] == params[1]) return FREIGHT_ERR_FORMAT;
        const uint8_t a = params[0], b = params[1];
        if (len == 0) return FREIGHT_OK;
        out[0] = a;
        if (len > 1) out[1] = b;
        uint64_t i = 2, j = 1;
        while (i < len) {
            uint8_t s = out[j++];
            out[i++] = a;
            if (s == a && i < len) out[i++] = b;
        }
        return FREIGHT_OK;
    }
    case FREIGHT_GEN_SIERPINSKI: {
        if (plen != 3 || params[0] < 1 || params[0] > 15) return FREIGHT_ERR_FORMAT;
        const uint32_t lw = params[0];
        const uint64_t mask = ((uint64_t) 1 << lw) - 1;
        const uint8_t on = params[1], off = params[2];
        for (uint64_t i = 0; i < len; i++) {
            uint64_t x = i & mask, y = (i >> lw) & mask;
            out[i] = (x & y) == 0 ? on : off;
        }
        return FREIGHT_OK;
    }
    default:
        return FREIGHT_ERR_FORMAT;
    }
}

/* ---- expansion ---- */

static int parse_hdr(const uint8_t *ops, uint64_t n, uint64_t *total, bool *has_sha, uint64_t *body)
{
    if (!ops || n < FREIGHT_OPS_HDR) return FREIGHT_ERR_FORMAT;
    for (uint32_t i = 0; i < FREIGHT_OPS_MAGIC_LEN; i++)
        if (ops[i] != ops_magic[i]) return FREIGHT_ERR_FORMAT;
    if (ops[4] != FREIGHT_OPS_VERSION) return FREIGHT_ERR_FORMAT;
    if (ops[5] & ~FREIGHT_OPS_F_SHA) return FREIGHT_ERR_FORMAT;
    *has_sha = (ops[5] & FREIGHT_OPS_F_SHA) != 0;
    *total = get64(ops + 6);
    *body = *has_sha ? FREIGHT_OPS_HDR_SHA : FREIGHT_OPS_HDR;
    if (n < *body) return FREIGHT_ERR_FORMAT;
    return FREIGHT_OK;
}

int freight_ops_peek(const uint8_t *ops, uint64_t ops_len, uint64_t *total, bool *has_sha)
{
    uint64_t t, b;
    bool s;
    int rc = parse_hdr(ops, ops_len, &t, &s, &b);
    if (rc) return rc;
    if (total) *total = t;
    if (has_sha) *has_sha = s;
    return FREIGHT_OK;
}

int freight_ops_expand(const uint8_t *ops, uint64_t ops_len, uint8_t *out, uint64_t out_cap,
                       uint64_t limit, freight_resolve_fn resolve, void *ctx, uint64_t *out_len)
{
    uint64_t total, p;
    bool has_sha;
    if (out_len) *out_len = 0;
    int rc = parse_hdr(ops, ops_len, &total, &has_sha, &p);
    if (rc) return rc;
    if (total > out_cap || total > limit) return FREIGHT_ERR_LIMIT;
    if (total && !out) return FREIGHT_ERR_ARG;

    uint64_t pos = 0;
    while (p < ops_len) {
        const uint8_t op = ops[p++];
        uint64_t len;
        switch (op) {
        case FREIGHT_OP_LITERAL: {
            if (!rd_var(ops, ops_len, &p, &len)) return FREIGHT_ERR_FORMAT;
            if (len == 0 || len > total - pos || len > ops_len - p) return FREIGHT_ERR_FORMAT;
            for (uint64_t i = 0; i < len; i++) out[pos + i] = ops[p + i];
            p += len;
            break;
        }
        case FREIGHT_OP_COPY: {
            uint64_t d;
            if (!rd_var(ops, ops_len, &p, &d) || !rd_var(ops, ops_len, &p, &len))
                return FREIGHT_ERR_FORMAT;
            if (d == 0 || d > pos || len == 0 || len > total - pos) return FREIGHT_ERR_FORMAT;
            /* Forward byte copy: overlap repeats the period d. */
            uint8_t *dst = out + pos;
            const uint8_t *src = dst - d;
            for (uint64_t i = 0; i < len; i++) dst[i] = src[i];
            break;
        }
        case FREIGHT_OP_CIDREF: {
            uint64_t cl;
            if (!rd_var(ops, ops_len, &p, &cl)) return FREIGHT_ERR_FORMAT;
            if (cl == 0 || cl > FREIGHT_CID_MAX || cl > ops_len - p) return FREIGHT_ERR_FORMAT;
            const uint8_t *cid = ops + p;
            p += cl;
            if (!rd_var(ops, ops_len, &p, &len)) return FREIGHT_ERR_FORMAT;
            if (len == 0 || len > total - pos) return FREIGHT_ERR_FORMAT;
            if (!resolve || !resolve(ctx, cid, (uint32_t) cl, out + pos, len))
                return FREIGHT_ERR_RESOLVE;
            break;
        }
        case FREIGHT_OP_SEED: {
            if (ops_len - p < 2) return FREIGHT_ERR_FORMAT;
            const uint8_t gen = ops[p], pl = ops[p + 1];
            p += 2;
            if (pl > FREIGHT_GEN_PARAM_MAX || pl > ops_len - p) return FREIGHT_ERR_FORMAT;
            const uint8_t *prm = ops + p;
            p += pl;
            if (!rd_var(ops, ops_len, &p, &len)) return FREIGHT_ERR_FORMAT;
            if (len == 0 || len > total - pos) return FREIGHT_ERR_FORMAT;
            rc = freight_gen_run(gen, prm, pl, out + pos, len);
            if (rc) return FREIGHT_ERR_FORMAT;
            break;
        }
        default:
            return FREIGHT_ERR_FORMAT;
        }
        pos += len;
    }
    if (pos != total) return FREIGHT_ERR_FORMAT;
    if (has_sha) {
        uint8_t d[SHA256_DIGEST_LEN];
        sha256(out, (size_t) total, d);
        if (!fr_eq(d, ops + FREIGHT_OPS_HDR, SHA256_DIGEST_LEN)) return FREIGHT_ERR_HASH;
    }
    if (out_len) *out_len = total;
    return FREIGHT_OK;
}

/* ---- writer ---- */

static void w_byte(freight_ops_writer_t *w, uint8_t b)
{
    if (w->err) return;
    if (w->len >= w->cap) {
        w->err = FREIGHT_ERR_SPACE;
        return;
    }
    w->buf[w->len++] = b;
}

static void w_var(freight_ops_writer_t *w, uint64_t v)
{
    while (v >= 0x80) {
        w_byte(w, (uint8_t) (v | 0x80));
        v >>= 7;
    }
    w_byte(w, (uint8_t) v);
}

static void w_bytes(freight_ops_writer_t *w, const uint8_t *b, uint64_t n)
{
    if (w->err) return;
    if (n > w->cap - w->len) {
        w->err = FREIGHT_ERR_SPACE;
        return;
    }
    for (uint64_t i = 0; i < n; i++) w->buf[w->len + i] = b[i];
    w->len += n;
}

/* Common length check: every op produces 1..(declared - produced) bytes. */
static bool w_take(freight_ops_writer_t *w, uint64_t len)
{
    if (w->err) return false;
    if (len == 0 || len > w->declared - w->produced) {
        w->err = FREIGHT_ERR_ARG;
        return false;
    }
    return true;
}

void freight_ops_writer_init(freight_ops_writer_t *w, uint8_t *buf, uint64_t cap,
                             uint64_t declared_total, const uint8_t *sha256_or_null)
{
    if (!w) return;
    w->buf = buf;
    w->cap = buf ? cap : 0;
    w->len = 0;
    w->declared = declared_total;
    w->produced = 0;
    w->err = FREIGHT_OK;
    w_bytes(w, ops_magic, FREIGHT_OPS_MAGIC_LEN);
    w_byte(w, FREIGHT_OPS_VERSION);
    w_byte(w, sha256_or_null ? FREIGHT_OPS_F_SHA : 0);
    for (int i = 0; i < 8; i++) w_byte(w, (uint8_t) (declared_total >> (8 * i)));
    if (sha256_or_null) w_bytes(w, sha256_or_null, FREIGHT_SHA256_BYTES);
}

void freight_ops_put_literal(freight_ops_writer_t *w, const uint8_t *b, uint64_t n)
{
    if (!w || !w_take(w, n)) return;
    if (!b) {
        w->err = FREIGHT_ERR_ARG;
        return;
    }
    w_byte(w, FREIGHT_OP_LITERAL);
    w_var(w, n);
    w_bytes(w, b, n);
    w->produced += n;
}

void freight_ops_put_copy(freight_ops_writer_t *w, uint64_t distance, uint64_t len)
{
    if (!w || !w_take(w, len)) return;
    if (distance == 0 || distance > w->produced) {
        w->err = FREIGHT_ERR_ARG;
        return;
    }
    w_byte(w, FREIGHT_OP_COPY);
    w_var(w, distance);
    w_var(w, len);
    w->produced += len;
}

void freight_ops_put_cidref(freight_ops_writer_t *w, const uint8_t *cid, uint32_t cid_len,
                            uint64_t len)
{
    if (!w || !w_take(w, len)) return;
    if (!cid || cid_len == 0 || cid_len > FREIGHT_CID_MAX) {
        w->err = FREIGHT_ERR_ARG;
        return;
    }
    w_byte(w, FREIGHT_OP_CIDREF);
    w_var(w, cid_len);
    w_bytes(w, cid, cid_len);
    w_var(w, len);
    w->produced += len;
}

void freight_ops_put_seed(freight_ops_writer_t *w, uint8_t gen, const uint8_t *params,
                          uint32_t plen, uint64_t len)
{
    if (!w || !w_take(w, len)) return;
    if ((plen && !params) || plen > FREIGHT_GEN_PARAM_MAX) {
        w->err = FREIGHT_ERR_ARG;
        return;
    }
    w_byte(w, FREIGHT_OP_SEED);
    w_byte(w, gen);
    w_byte(w, (uint8_t) plen);
    w_bytes(w, params, plen);
    w_var(w, len);
    w->produced += len;
}

int freight_ops_writer_finish(freight_ops_writer_t *w, uint64_t *out_len)
{
    if (!w) return FREIGHT_ERR_ARG;
    if (w->err) return w->err;
    if (w->produced != w->declared) return FREIGHT_ERR_ARG;
    if (out_len) *out_len = w->len;
    return FREIGHT_OK;
}

/* ---- encoder ---- */

#define ENC_HEADS     (1u << FREIGHT_ENC_HASH_BITS)
#define ENC_MIN_MATCH 4u
#define ENC_MAX_MATCH 65536u
#define ENC_CHAIN     128u

static uint32_t enc_hash(const uint8_t *p)
{
    uint32_t v = (uint32_t) p[0] | ((uint32_t) p[1] << 8) | ((uint32_t) p[2] << 16) |
                 ((uint32_t) p[3] << 24);
    return (v * 2654435761u) >> (32 - FREIGHT_ENC_HASH_BITS);
}

uint64_t freight_ops_bound(uint64_t n, bool with_sha)
{
    /* Literal runs <= copies + 1 <= n / 4 + 1, each at most 11 bytes of
     * overhead; copies never cost more than the bytes they replace. */
    return (with_sha ? FREIGHT_OPS_HDR_SHA : FREIGHT_OPS_HDR) + n + 11u * ((n >> 2) + 1u);
}

int freight_ops_encode(const uint8_t *in, uint64_t n, bool with_sha, uint8_t *out, uint64_t cap,
                       uint64_t *out_len, uint32_t *work, uint32_t work_words)
{
    if (!out || !out_len || !work || (n && !in)) return FREIGHT_ERR_ARG;
    if (n >= 0xFFFFFFFFull) return FREIGHT_ERR_ARG;
    if (work_words < FREIGHT_ENC_WORK_MIN) return FREIGHT_ERR_SPACE;

    uint32_t *head = work, *prev = work + ENC_HEADS;
    uint32_t win = 256;
    while (win < 65536u && (win << 1) <= work_words - ENC_HEADS) win <<= 1;
    const uint32_t mask = win - 1;
    for (uint32_t i = 0; i < ENC_HEADS; i++) head[i] = 0;

    uint8_t digest[SHA256_DIGEST_LEN];
    if (with_sha) sha256(in, (size_t) n, digest);
    freight_ops_writer_t w;
    freight_ops_writer_init(&w, out, cap, n, with_sha ? digest : (const uint8_t *) 0);

    const uint32_t len = (uint32_t) n;
    uint32_t i = 0, lit = 0;
    while (i < len && !w.err) {
        uint32_t best = 0, bestd = 0;
        if (len - i >= ENC_MIN_MATCH) {
            uint32_t maxl = len - i < ENC_MAX_MATCH ? len - i : ENC_MAX_MATCH;
            uint32_t cand = head[enc_hash(in + i)];
            for (uint32_t steps = 0; cand && steps < ENC_CHAIN; steps++) {
                uint32_t c = cand - 1, d = i - c;
                if (d > win) break;
                uint32_t l = 0;
                while (l < maxl && in[c + l] == in[i + l]) l++;
                if (l > best) {
                    best = l;
                    bestd = d;
                    if (l == maxl) break;
                }
                /* prev[c] cannot be stale: a later writer of that slot is at
                 * c + win or beyond, which is >= i and not inserted yet. */
                uint32_t nx = prev[c & mask];
                if (nx == 0 || nx - 1 >= c) break;
                cand = nx;
            }
        }
        uint32_t cost = 1 + var_len(bestd) + var_len(best);
        if (best >= ENC_MIN_MATCH && cost < best) {
            if (i > lit) freight_ops_put_literal(&w, in + lit, i - lit);
            freight_ops_put_copy(&w, bestd, best);
            for (uint32_t t = 0; t < best; t++, i++) {
                if (len - i >= ENC_MIN_MATCH) {
                    uint32_t h = enc_hash(in + i);
                    prev[i & mask] = head[h];
                    head[h] = i + 1;
                }
            }
            lit = i;
        } else {
            if (len - i >= ENC_MIN_MATCH) {
                uint32_t h = enc_hash(in + i);
                prev[i & mask] = head[h];
                head[h] = i + 1;
            }
            i++;
        }
    }
    if (i > lit) freight_ops_put_literal(&w, in + lit, i - lit);
    return freight_ops_writer_finish(&w, out_len);
}
