/* test_macgyver.c — MacGyver Build System (MCG0) Tests
 *
 * Tests for shared AST registry, obligation tracking, and triad link protocol.
 *
 * Author: 36N9 Genetics, LLC
 * License: SEL-3.3 (kernel component)
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "macgyver.h"

static int tests_run = 0;
static int tests_passed = 0;
static int tests_failed = 0;

#define TEST(name) static void name(void)
#define RUN(name) do { \
    tests_run++; \
    printf("  [TEST] %s ... ", #name); \
    name(); \
    tests_passed++; \
    printf("PASS\n"); \
} while(0)

#define ASSERT(cond, msg) do { \
    if (!(cond)) { \
        printf("FAIL: %s\n", msg); \
        tests_failed++; \
        return; \
    } \
} while(0)

#define PASS() return

/* ===== Registry Init Tests ===== */

TEST(registry_init_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    ASSERT(reg.node_count == 0, "no nodes");
    ASSERT(reg.obligation_count == 0, "no obligations");
    ASSERT(reg.triad_count == 0, "no triads");
    ASSERT(reg.next_node_id == 1, "next node id is 1");
    ASSERT(reg.next_obligation_id == 1, "next obligation id is 1");
    ASSERT(reg.next_triad_id == 1, "next triad id is 1");
    PASS();
}

/* ===== AST Node Tests ===== */

TEST(add_node_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    int32_t idx = mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "main", 0);
    ASSERT(idx >= 0, "node added");
    ASSERT(idx == 0, "first node is index 0");
    ASSERT(reg.node_count == 1, "count incremented");

    mcg_node_t *n = mcg_get_node(&reg, 1);
    ASSERT(n != NULL, "node found by id");
    ASSERT(strcmp(n->name, "main") == 0, "name matches");
    ASSERT(n->type == MCG_NODE_MODULE, "type is module");
    ASSERT(n->role == MCG_ROLE_S_PLUS, "role is S+");
    ASSERT(n->parent_id == 0, "parent is 0 (root)");
    ASSERT(!n->reviewed, "not reviewed by default");
    ASSERT(!n->generated, "not generated by default");
    PASS();
}

TEST(add_child_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "parent", 0);
    mcg_add_node(&reg, MCG_NODE_FUNCTION, MCG_ROLE_S_PLUS, "child", 1);

    ASSERT(mcg_add_child(&reg, 1, 2), "child added");
    mcg_node_t *p = mcg_get_node(&reg, 1);
    ASSERT(p->child_count == 1, "parent has 1 child");
    ASSERT(p->child_ids[0] == 2, "child id is 2");

    /* Nonexistent parent */
    ASSERT(!mcg_add_child(&reg, 999, 2), "nonexistent parent fails");
    PASS();
}

TEST(set_node_digest_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "mod", 0);
    uint8_t digest[4] = {0xCA, 0xFE, 0xBA, 0xBE};
    ASSERT(mcg_set_node_digest(&reg, 1, digest, 4), "digest set");
    mcg_node_t *n = mcg_get_node(&reg, 1);
    ASSERT(n->digest_len == 4, "digest length is 4");
    ASSERT(n->digest[0] == 0xCA, "digest[0] matches");
    PASS();
}

TEST(mark_reviewed_generated_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_CONTRACT, MCG_ROLE_S_MINUS, "guard", 0);
    ASSERT(mcg_mark_reviewed(&reg, 1, true), "marked reviewed");
    ASSERT(mcg_mark_generated(&reg, 1, true), "marked generated");
    mcg_node_t *n = mcg_get_node(&reg, 1);
    ASSERT(n->reviewed, "is reviewed");
    ASSERT(n->generated, "is generated");
    PASS();
}

TEST(get_nonexistent_node_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    ASSERT(mcg_get_node(&reg, 999) == NULL, "nonexistent returns NULL");
    PASS();
}

/* ===== Obligation Tests ===== */

TEST(add_obligation_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_FUNCTION, MCG_ROLE_S_PLUS, "func", 0);
    mcg_add_node(&reg, MCG_NODE_CONTRACT, MCG_ROLE_S_MINUS, "guard", 0);

    int32_t idx = mcg_add_obligation(&reg, MCG_ROLE_S_MINUS, "bounds-check",
                                     "reject out-of-bounds access", 1, 2);
    ASSERT(idx >= 0, "obligation added");
    ASSERT(reg.obligation_count == 1, "count incremented");

    mcg_obligation_t *o = &reg.obligations[0];
    ASSERT(strcmp(o->label, "bounds-check") == 0, "label matches");
    ASSERT(o->role == MCG_ROLE_S_MINUS, "role is S-");
    ASSERT(o->source_node_id == 1, "source node is 1");
    ASSERT(o->target_node_id == 2, "target node is 2");
    ASSERT(!o->satisfied, "not satisfied by default");
    ASSERT(!o->verified, "not verified by default");
    PASS();
}

TEST(satisfy_verify_obligation_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_obligation(&reg, MCG_ROLE_S_PLUS, "postcondition", "result is valid", 0, 0);

    ASSERT(mcg_satisfy_obligation(&reg, 0), "obligation satisfied");
    ASSERT(reg.obligations[0].satisfied, "satisfied flag set");

    ASSERT(mcg_verify_obligation(&reg, 0), "obligation verified");
    ASSERT(reg.obligations[0].verified, "verified flag set");
    PASS();
}

TEST(count_unsatisfied_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_obligation(&reg, MCG_ROLE_S_PLUS, "a", "", 0, 0);
    mcg_add_obligation(&reg, MCG_ROLE_S_PLUS, "b", "", 0, 0);
    mcg_add_obligation(&reg, MCG_ROLE_S_MINUS, "c", "", 0, 0);
    mcg_satisfy_obligation(&reg, 0);

    ASSERT(mcg_count_unsatisfied(&reg, MCG_ROLE_S_PLUS) == 1, "1 unsatisfied S+");
    ASSERT(mcg_count_unsatisfied(&reg, MCG_ROLE_S_MINUS) == 1, "1 unsatisfied S-");
    ASSERT(mcg_count_unsatisfied(&reg, MCG_ROLE_S_ZERO) == 0, "0 unsatisfied S0");
    PASS();
}

TEST(count_unverified_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_obligation(&reg, MCG_ROLE_S_PLUS, "a", "", 0, 0);
    mcg_add_obligation(&reg, MCG_ROLE_S_MINUS, "b", "", 0, 0);
    mcg_verify_obligation(&reg, 0);

    ASSERT(mcg_count_unverified(&reg) == 1, "1 unverified");
    PASS();
}

/* ===== Triad Link Protocol Tests ===== */

TEST(create_triad_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    int32_t forge = mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "app.36n9", 0);
    int32_t counter = mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "app.9n63", 0);
    int32_t medi = mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "app.0n0", 0);

    int32_t tidx = mcg_create_triad(&reg, "app-triad",
                                    (uint32_t)forge + 1,
                                    (uint32_t)counter + 1,
                                    (uint32_t)medi + 1);
    ASSERT(tidx >= 0, "triad created");
    ASSERT(reg.triad_count == 1, "count incremented");

    mcg_triad_t *t = &reg.triads[0];
    ASSERT(strcmp(t->name, "app-triad") == 0, "name matches");
    ASSERT(t->forge_node_id == 1, "forge node is 1");
    ASSERT(t->counterforge_node_id == 2, "counterforge node is 2");
    ASSERT(t->mediatrix_node_id == 3, "mediatrix node is 3");
    ASSERT(t->forge_status == MCG_STATUS_PENDING, "forge pending");
    ASSERT(t->counterforge_status == MCG_STATUS_PENDING, "counterforge pending");
    ASSERT(t->mediatrix_status == MCG_STATUS_PENDING, "mediatrix pending");
    ASSERT(!t->linked, "not linked");
    ASSERT(t->atomic, "is atomic");
    PASS();
}

TEST(set_component_status_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t", 1, 2, 3);

    ASSERT(mcg_set_component_status(&reg, 0, MCG_COMPONENT_FORGE, MCG_STATUS_COMPILING), "forge compiling");
    ASSERT(mcg_set_component_status(&reg, 0, MCG_COMPONENT_COUNTERFORGE, MCG_STATUS_COMPILING), "counterforge compiling");
    ASSERT(reg.triads[0].forge_status == MCG_STATUS_COMPILING, "forge is compiling");
    ASSERT(reg.triads[0].counterforge_status == MCG_STATUS_COMPILING, "counterforge is compiling");
    PASS();
}

TEST(set_component_digest_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t", 1, 2, 3);

    uint8_t digest[4] = {0x01, 0x02, 0x03, 0x04};
    ASSERT(mcg_set_component_digest(&reg, 0, MCG_COMPONENT_FORGE, digest, 4), "forge digest set");
    ASSERT(reg.triads[0].forge_digest_len == 4, "forge digest length");
    ASSERT(reg.triads[0].forge_digest[0] == 0x01, "forge digest[0]");
    PASS();
}

TEST(is_triad_complete_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t", 1, 2, 3);

    ASSERT(!mcg_is_triad_complete(&reg, 0), "not complete initially");

    mcg_set_component_status(&reg, 0, MCG_COMPONENT_FORGE, MCG_STATUS_COMPILED);
    ASSERT(!mcg_is_triad_complete(&reg, 0), "not complete with 1/3");

    mcg_set_component_status(&reg, 0, MCG_COMPONENT_COUNTERFORGE, MCG_STATUS_COMPILED);
    ASSERT(!mcg_is_triad_complete(&reg, 0), "not complete with 2/3");

    mcg_set_component_status(&reg, 0, MCG_COMPONENT_MEDIATRIX, MCG_STATUS_COMPILED);
    ASSERT(mcg_is_triad_complete(&reg, 0), "complete with 3/3");
    PASS();
}

TEST(compute_triad_digest_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t", 1, 2, 3);

    uint8_t d1[4] = {0xAA, 0xBB, 0xCC, 0xDD};
    uint8_t d2[4] = {0x11, 0x22, 0x33, 0x44};
    uint8_t d3[4] = {0x55, 0x66, 0x77, 0x88};
    mcg_set_component_digest(&reg, 0, MCG_COMPONENT_FORGE, d1, 4);
    mcg_set_component_digest(&reg, 0, MCG_COMPONENT_COUNTERFORGE, d2, 4);
    mcg_set_component_digest(&reg, 0, MCG_COMPONENT_MEDIATRIX, d3, 4);

    ASSERT(mcg_compute_triad_digest(&reg, 0), "triad digest computed");
    ASSERT(reg.triads[0].triad_digest_len == MCG_MAX_DIGEST_LEN, "digest length is max");
    /* Verify it's not all zeros */
    bool nonzero = false;
    for (uint32_t i = 0; i < MCG_MAX_DIGEST_LEN; i++) {
        if (reg.triads[0].triad_digest[i] != 0) { nonzero = true; break; }
    }
    ASSERT(nonzero, "triad digest is non-zero");
    PASS();
}

TEST(link_triad_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t", 1, 2, 3);

    /* Can't link before complete */
    ASSERT(!mcg_link_triad(&reg, 0), "can't link incomplete triad");

    mcg_set_component_status(&reg, 0, MCG_COMPONENT_FORGE, MCG_STATUS_COMPILED);
    mcg_set_component_status(&reg, 0, MCG_COMPONENT_COUNTERFORGE, MCG_STATUS_COMPILED);
    mcg_set_component_status(&reg, 0, MCG_COMPONENT_MEDIATRIX, MCG_STATUS_COMPILED);

    uint8_t d[4] = {0x01, 0x02, 0x03, 0x04};
    mcg_set_component_digest(&reg, 0, MCG_COMPONENT_FORGE, d, 4);
    mcg_set_component_digest(&reg, 0, MCG_COMPONENT_COUNTERFORGE, d, 4);
    mcg_set_component_digest(&reg, 0, MCG_COMPONENT_MEDIATRIX, d, 4);

    ASSERT(mcg_link_triad(&reg, 0), "triad linked");
    ASSERT(reg.triads[0].linked, "linked flag set");
    ASSERT(reg.triads[0].forge_status == MCG_STATUS_LINKED, "forge is linked");
    ASSERT(reg.triads[0].counterforge_status == MCG_STATUS_LINKED, "counterforge is linked");
    ASSERT(reg.triads[0].mediatrix_status == MCG_STATUS_LINKED, "mediatrix is linked");
    ASSERT(reg.triads[0].triad_digest_len > 0, "triad digest computed");
    PASS();
}

/* ===== Build Orchestration Tests ===== */

TEST(compile_component_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t", 1, 2, 3);

    /* Set digests on nodes */
    uint8_t d[4] = {0xDE, 0xAD, 0xBE, 0xEF};
    mcg_set_node_digest(&reg, 1, d, 4);
    mcg_set_node_digest(&reg, 2, d, 4);
    mcg_set_node_digest(&reg, 3, d, 4);

    ASSERT(mcg_compile_component(&reg, 0, MCG_COMPONENT_FORGE), "forge compiled");
    ASSERT(reg.triads[0].forge_status == MCG_STATUS_COMPILED, "forge is compiled");
    ASSERT(reg.triads[0].forge_digest_len == 4, "forge digest copied");

    /* Compile without digest fails */
    mcg_registry_t reg2;
    mcg_registry_init(&reg2);
    mcg_add_node(&reg2, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "x", 0);
    mcg_add_node(&reg2, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "y", 0);
    mcg_add_node(&reg2, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "z", 0);
    mcg_create_triad(&reg2, "t2", 1, 2, 3);
    ASSERT(!mcg_compile_component(&reg2, 0, MCG_COMPONENT_FORGE), "compile without digest fails");
    PASS();
}

TEST(build_triad_success_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "app.36n9", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "app.9n63", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "app.0n0", 0);
    mcg_create_triad(&reg, "full-build", 1, 2, 3);

    uint8_t d1[4] = {0x01, 0x02, 0x03, 0x04};
    uint8_t d2[4] = {0x05, 0x06, 0x07, 0x08};
    uint8_t d3[4] = {0x09, 0x0A, 0x0B, 0x0C};
    mcg_set_node_digest(&reg, 1, d1, 4);
    mcg_set_node_digest(&reg, 2, d2, 4);
    mcg_set_node_digest(&reg, 3, d3, 4);

    ASSERT(mcg_build_triad(&reg, 0), "triad built successfully");
    ASSERT(reg.triads[0].linked, "triad is linked");
    ASSERT(reg.triads[0].forge_status == MCG_STATUS_LINKED, "forge linked");
    ASSERT(reg.triads[0].counterforge_status == MCG_STATUS_LINKED, "counterforge linked");
    ASSERT(reg.triads[0].mediatrix_status == MCG_STATUS_LINKED, "mediatrix linked");
    ASSERT(reg.triads[0].triad_digest_len > 0, "triad digest computed");
    PASS();
}

TEST(build_triad_atomic_failure_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "ok", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "missing-digest", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "ok2", 0);
    mcg_create_triad(&reg, "fail-build", 1, 2, 3);

    /* Only set digest on forge node, not counterforge */
    uint8_t d[4] = {0xFF, 0xFF, 0xFF, 0xFF};
    mcg_set_node_digest(&reg, 1, d, 4);
    /* Node 2 has no digest — counterforge will fail */

    ASSERT(!mcg_build_triad(&reg, 0), "atomic build fails");
    ASSERT(reg.triads[0].forge_status == MCG_STATUS_FAILED, "forge failed (atomic rollback)");
    ASSERT(!reg.triads[0].linked, "not linked");
    PASS();
}

TEST(count_by_status_test) {
    mcg_registry_t reg;
    mcg_registry_init(&reg);

    /* Create two triads */
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "a", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "b", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "c", 0);
    mcg_create_triad(&reg, "t1", 1, 2, 3);

    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_PLUS, "d", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_MINUS, "e", 0);
    mcg_add_node(&reg, MCG_NODE_MODULE, MCG_ROLE_S_ZERO, "f", 0);
    mcg_create_triad(&reg, "t2", 4, 5, 6);

    ASSERT(mcg_count_by_status(&reg, MCG_STATUS_PENDING) == 2, "2 pending");

    mcg_set_component_status(&reg, 0, MCG_COMPONENT_FORGE, MCG_STATUS_COMPILED);
    ASSERT(mcg_count_by_status(&reg, MCG_STATUS_PENDING) == 1, "1 pending");
    ASSERT(mcg_count_by_status(&reg, MCG_STATUS_COMPILED) == 1, "1 compiled");
    PASS();
}

/* ===== Name Function Tests ===== */

TEST(name_functions_test) {
    ASSERT(strcmp(mcg_component_name(MCG_COMPONENT_FORGE), "forge") == 0, "forge name");
    ASSERT(strcmp(mcg_component_name(MCG_COMPONENT_COUNTERFORGE), "counterforge") == 0, "counterforge name");
    ASSERT(strcmp(mcg_component_name(MCG_COMPONENT_MEDIATRIX), "mediatrix") == 0, "mediatrix name");
    ASSERT(strcmp(mcg_node_type_name(MCG_NODE_MODULE), "module") == 0, "module name");
    ASSERT(strcmp(mcg_node_type_name(MCG_NODE_FUNCTION), "function") == 0, "function name");
    ASSERT(strcmp(mcg_node_type_name(MCG_NODE_CONTRACT), "contract") == 0, "contract name");
    ASSERT(strcmp(mcg_role_name(MCG_ROLE_S_PLUS), "S+") == 0, "S+ name");
    ASSERT(strcmp(mcg_role_name(MCG_ROLE_S_MINUS), "S-") == 0, "S- name");
    ASSERT(strcmp(mcg_role_name(MCG_ROLE_S_ZERO), "S0") == 0, "S0 name");
    ASSERT(strcmp(mcg_status_name(MCG_STATUS_PENDING), "pending") == 0, "pending name");
    ASSERT(strcmp(mcg_status_name(MCG_STATUS_LINKED), "linked") == 0, "linked name");
    ASSERT(strcmp(mcg_status_name(MCG_STATUS_FAILED), "failed") == 0, "failed name");
    PASS();
}

/* ===== Main ===== */

int main(void) {
    printf("\n=== ZXV MacGyver (MCG0) Tests ===\n\n");

    RUN(registry_init_test);
    RUN(add_node_test);
    RUN(add_child_test);
    RUN(set_node_digest_test);
    RUN(mark_reviewed_generated_test);
    RUN(get_nonexistent_node_test);
    RUN(add_obligation_test);
    RUN(satisfy_verify_obligation_test);
    RUN(count_unsatisfied_test);
    RUN(count_unverified_test);
    RUN(create_triad_test);
    RUN(set_component_status_test);
    RUN(set_component_digest_test);
    RUN(is_triad_complete_test);
    RUN(compute_triad_digest_test);
    RUN(link_triad_test);
    RUN(compile_component_test);
    RUN(build_triad_success_test);
    RUN(build_triad_atomic_failure_test);
    RUN(count_by_status_test);
    RUN(name_functions_test);

    printf("\n=== Results: %d/%d passed, %d failed ===\n",
           tests_passed, tests_run, tests_failed);
    if (tests_failed == 0) {
        printf("ALL TESTS PASSED\n");
    }
    return tests_failed > 0 ? 1 : 0;
}
