#!/usr/bin/env python3
# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate test_web4_vectors.h from PUBLISHED test-vector documents.

Nothing here computes an expected value: every string is copied verbatim from
the source document, so the C tests check this module against other people's
implementations, not against itself.

Usage: gen_web4_vectors.py <dir-with-downloads> > test_web4_vectors.h

Sources (download into <dir> under these names):
  bip-0173.mediawiki  https://raw.githubusercontent.com/bitcoin/bips/master/bip-0173.mediawiki
  bip-0350.mediawiki  https://raw.githubusercontent.com/bitcoin/bips/master/bip-0350.mediawiki
  erc-55.md           https://raw.githubusercontent.com/ethereum/ercs/master/ERCS/erc-55.md
  eip1559.json        https://raw.githubusercontent.com/ethereumjs/ethereumjs-monorepo/%40ethereumjs/tx%403.5.2/packages/tx/test/json/eip1559.json
"""
import json
import re
import sys
import os

d = sys.argv[1]


def rd(name):
    with open(os.path.join(d, name), encoding="utf-8") as f:
        return f.read()


def cstr(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch in '"\\':
            out.append("\\" + ch)
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("\\x%02x\"\"" % o)
    return '"' + "".join(out) + '"'


def section(text, start, end):
    i = text.index(start)
    j = text.index(end, i)
    return text[i:j]


def tt_items(block):
    """Lines '* <tt>..</tt>...' -> list of (prefix_byte or None, string, rest)."""
    res = []
    for line in block.splitlines():
        m = re.match(r"\* (0x([0-9A-Fa-f]{2}) \+ )?<tt>(.*?)</tt>(.*)$", line)
        if m:
            pre = int(m.group(2), 16) if m.group(2) else None
            res.append((pre, m.group(3), m.group(4)))
    return res


def emit_strings(name, items):
    print("static const char *const %s[] = {" % name)
    for pre, s, rest in items:
        full = (chr(pre) if pre is not None else "") + s
        # "de1lg7wt + 0xFF": the suffix byte is part of the vector
        m = re.match(r"\s*\+ 0x([0-9A-Fa-f]{2})", rest)
        if m:
            full += chr(int(m.group(1), 16))
        print("    %s," % cstr(full))
    print("};")


b173 = rd("bip-0173.mediawiki")
b350 = rd("bip-0350.mediawiki")
tv173 = section(b173, "===Test vectors===", "===Checksum design===")
tv350 = section(b350, "===Test vectors for Bech32m===", "==Appendix")

print("/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */")
print("/* SPDX-License-Identifier: Apache-2.0 */")
print("/* test_web4_vectors.h — GENERATED by gen_web4_vectors.py from published")
print(" * documents (BIP-173, BIP-350, ERC-55, ethereumjs tx 3.5.2 eip1559.json).")
print(" * Do not edit by hand. */")
print("#ifndef TEST_WEB4_VECTORS_H")
print("#define TEST_WEB4_VECTORS_H")
print("#include <stdint.h>")

# --- BIP-173 ---
parts = tv173.split("The following string are not valid Bech32")
emit_strings("BIP173_VALID", tt_items(parts[0]))
rest = parts[1]
inv, rest = rest.split("The following list gives valid segwit addresses")
emit_strings("BIP173_INVALID", tt_items(inv))

# --- BIP-350 ---
p350 = tv350.split("The following string are not valid Bech32m")
emit_strings("BIP350_VALID", tt_items(p350[0]))
inv350, addr350 = p350[1].split("===Test vectors for v0-v16 native segregated witness addresses===")
emit_strings("BIP350_INVALID", tt_items(inv350))
valid_addr, invalid_addr = addr350.split("The following list gives invalid segwit addresses")
va = tt_items(valid_addr)
print("typedef struct { const char *addr; const char *spk_hex; } w4v_segwit_t;")
print("static const w4v_segwit_t BIP350_ADDR_VALID[] = {")
for _, a, rest in va:
    m = re.search(r"<tt>([0-9a-f]+)</tt>", rest)
    print("    {%s, %s}," % (cstr(a), cstr(m.group(1))))
print("};")
emit_strings("BIP350_ADDR_INVALID", tt_items(invalid_addr))

# --- ERC-55 ---
e55 = rd("erc-55.md")
addrs = []
for m in re.finditer(r"^(0x[0-9a-fA-F]{40})$", e55, re.M):
    if m.group(1) not in addrs:
        addrs.append(m.group(1))
print("static const char *const ERC55_VALID[] = {")
for a in addrs:
    print("    %s," % cstr(a))
print("};")

# --- EIP-1559 (ethereumjs) ---
txs = json.loads(rd("eip1559.json"))
print("typedef struct { uint64_t nonce, value, gas_limit, max_priority, max_fee;")
print("    const char *to, *sk, *signed_rlp; } w4v_1559_t;")
print("static const w4v_1559_t EIP1559_TX[] = {")
for t in txs:
    print("    {%du, %du, %du, %du, %du, %s, %s, %s}," % (
        t["nonce"], t["value"], t["gasLimit"], t["maxPriorityFeePerGas"], t["maxFeePerGas"],
        cstr(t["to"]), cstr(t["privateKey"]), cstr(t["signedTransactionRLP"])))
print("};")
print("#endif")
