/* macgyver.h — MacGyver Synchronized Build System (MCG0)
 *
 * MacGyver compiles tri-space (S+/S-/S0) source artifacts atomically through
 * three synchronized components: Forge (positive), Counterforge (negative),
 * and Mediatrix (neutral). It produces signed container triads bound to
 * validation evidence.
 *
 * MCG0 implements:
 *   - Shared AST node registry for cross-component semantic sharing
 *   - Event IR emission for tri-space obligations
 *   - Triad link protocol binding S+/S-/S0 artifacts cryptographically
 *
 * Referenced by:
 *   - Tri-Space Programming Spec: MacGyver synchronized compilation
 *   - RCE Spec: MacGyver compiles model S+/S-/S0 artifacts atomically
 *   - Root Computing Spec: MacGyver polyglot compilation
 *   - UBH Spec: MacGyver build pipeline
 *   - Telecom Event Fabric: MacGyver telecom compilation
 *   - Master Roadmap: build system and release pipeline
 *
 * Author: 36N9 Genetics, LLC
 * License: SEL-3.3 (kernel component)
 */
#ifndef MACGYVER_H
#define MACGYVER_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "event_space.h"

/* ===== MCG0 Constants ===== */

#define MCG_MAX_NODES        256
#define MCG_MAX_OBLIGATIONS  128
#define MCG_MAX_TRIADS        64
#define MCG_MAX_NAME_LEN      32
#define MCG_MAX_DIGEST_LEN    32
#define MCG_MAX_LABEL_LEN     64

/* ===== Tri-Space Component IDs ===== */

typedef enum {
    MCG_COMPONENT_FORGE        = 0,  /* S+ constructive behavior */
    MCG_COMPONENT_COUNTERFORGE = 1,  /* S- failure/compensation/guards */
    MCG_COMPONENT_MEDIATRIX    = 2,  /* S0 uncertainty/quarantine/resolution */
} mcg_component_t;

/* ===== AST Node Types ===== */

typedef enum {
    MCG_NODE_MODULE       = 0,
    MCG_NODE_FUNCTION     = 1,
    MCG_NODE_VARIABLE     = 2,
    MCG_NODE_TYPE         = 3,
    MCG_NODE_EVENT        = 4,
    MCG_NODE_CAPABILITY   = 5,
    MCG_NODE_CONTRACT     = 6,
    MCG_NODE_OBLIGATION   = 7,
    MCG_NODE_EFFECT       = 8,
    MCG_NODE_PARAMETER    = 9,
    MCG_NODE_RECORD       = 10,
    MCG_NODE_ARRAY        = 11,
    MCG_NODE_CALL         = 12,
    MCG_NODE_BLOCK        = 13,
} mcg_node_type_t;

/* ===== Tri-Space Role ===== */

typedef enum {
    MCG_ROLE_S_PLUS  = 0,
    MCG_ROLE_S_MINUS = 1,
    MCG_ROLE_S_ZERO  = 2,
} mcg_role_t;

/* ===== Build Status ===== */

typedef enum {
    MCG_STATUS_PENDING    = 0,
    MCG_STATUS_COMPILING  = 1,
    MCG_STATUS_COMPILED   = 2,
    MCG_STATUS_FAILED     = 3,
    MCG_STATUS_QUARANTINED = 4,
    MCG_STATUS_LINKED     = 5,
} mcg_status_t;

/* ===== AST Node ===== */

typedef struct mcg_node {
    uint32_t id;
    mcg_node_type_t type;
    mcg_role_t role;
    char name[MCG_MAX_NAME_LEN];
    uint32_t parent_id;        /* 0 = root */
    uint32_t child_ids[16];
    uint32_t child_count;
    uint8_t digest[MCG_MAX_DIGEST_LEN];
    uint32_t digest_len;
    bool reviewed;             /* human-reviewed for S-/S0 */
    bool generated;            /* generated by compiler (not human-authored) */
} mcg_node_t;

/* ===== Obligation ===== */

typedef struct mcg_obligation {
    uint32_t id;
    mcg_role_t role;
    char label[MCG_MAX_LABEL_LEN];
    uint32_t source_node_id;   /* AST node that generated this obligation */
    uint32_t target_node_id;   /* AST node that must satisfy it */
    bool satisfied;
    bool verified;
    char description[MCG_MAX_LABEL_LEN];
} mcg_obligation_t;

/* ===== Triad Link ===== */

typedef struct mcg_triad {
    uint32_t triad_id;
    char name[MCG_MAX_NAME_LEN];

    /* S+ artifact */
    uint32_t forge_node_id;
    uint8_t forge_digest[MCG_MAX_DIGEST_LEN];
    uint32_t forge_digest_len;
    mcg_status_t forge_status;

    /* S- artifact */
    uint32_t counterforge_node_id;
    uint8_t counterforge_digest[MCG_MAX_DIGEST_LEN];
    uint32_t counterforge_digest_len;
    mcg_status_t counterforge_status;

    /* S0 artifact */
    uint32_t mediatrix_node_id;
    uint8_t mediatrix_digest[MCG_MAX_DIGEST_LEN];
    uint32_t mediatrix_digest_len;
    mcg_status_t mediatrix_status;

    /* Triad binding */
    uint8_t triad_digest[MCG_MAX_DIGEST_LEN];
    uint32_t triad_digest_len;
    bool linked;               /* all three components compiled and bound */
    bool atomic;               /* all-or-nothing: if any fails, triad fails */
} mcg_triad_t;

/* ===== MCG0 Registry ===== */

typedef struct mcg_registry {
    mcg_node_t nodes[MCG_MAX_NODES];
    uint32_t node_count;
    uint32_t next_node_id;

    mcg_obligation_t obligations[MCG_MAX_OBLIGATIONS];
    uint32_t obligation_count;
    uint32_t next_obligation_id;

    mcg_triad_t triads[MCG_MAX_TRIADS];
    uint32_t triad_count;
    uint32_t next_triad_id;
} mcg_registry_t;

/* ===== API ===== */

void mcg_registry_init(mcg_registry_t *reg);

/* AST Node Management */
int32_t mcg_add_node(mcg_registry_t *reg, mcg_node_type_t type, mcg_role_t role,
                     const char *name, uint32_t parent_id);
bool mcg_add_child(mcg_registry_t *reg, uint32_t parent_id, uint32_t child_id);
mcg_node_t *mcg_get_node(mcg_registry_t *reg, uint32_t id);
bool mcg_set_node_digest(mcg_registry_t *reg, uint32_t id,
                         const uint8_t *digest, uint32_t len);
bool mcg_mark_reviewed(mcg_registry_t *reg, uint32_t id, bool reviewed);
bool mcg_mark_generated(mcg_registry_t *reg, uint32_t id, bool generated);

/* Obligation Management */
int32_t mcg_add_obligation(mcg_registry_t *reg, mcg_role_t role,
                           const char *label, const char *description,
                           uint32_t source_node, uint32_t target_node);
bool mcg_satisfy_obligation(mcg_registry_t *reg, uint32_t idx);
bool mcg_verify_obligation(mcg_registry_t *reg, uint32_t idx);
uint32_t mcg_count_unsatisfied(mcg_registry_t *reg, mcg_role_t role);
uint32_t mcg_count_unverified(mcg_registry_t *reg);

/* Triad Link Protocol */
int32_t mcg_create_triad(mcg_registry_t *reg, const char *name,
                         uint32_t forge_node, uint32_t counterforge_node,
                         uint32_t mediatrix_node);
bool mcg_set_component_status(mcg_registry_t *reg, uint32_t triad_idx,
                              mcg_component_t comp, mcg_status_t status);
bool mcg_set_component_digest(mcg_registry_t *reg, uint32_t triad_idx,
                              mcg_component_t comp,
                              const uint8_t *digest, uint32_t len);
bool mcg_link_triad(mcg_registry_t *reg, uint32_t triad_idx);
bool mcg_is_triad_complete(mcg_registry_t *reg, uint32_t triad_idx);
bool mcg_compute_triad_digest(mcg_registry_t *reg, uint32_t triad_idx);

/* Build Orchestration */
bool mcg_compile_component(mcg_registry_t *reg, uint32_t triad_idx,
                           mcg_component_t comp);
bool mcg_build_triad(mcg_registry_t *reg, uint32_t triad_idx);
uint32_t mcg_count_by_status(mcg_registry_t *reg, mcg_status_t status);

/* Name Functions */
const char *mcg_component_name(mcg_component_t comp);
const char *mcg_node_type_name(mcg_node_type_t type);
const char *mcg_role_name(mcg_role_t role);
const char *mcg_status_name(mcg_status_t status);

#endif /* MACGYVER_H */
