/* sephirot.h — L13 OS Hypervisor: Kabbalistic Multi-Valued Logic Engine
 *
 * Treats the Kabbalistic Tree of Life as a formal frame of reference for
 * a 13-phase logic system sitting above the existing L6 kernel (trit_t,
 * m5_types.h) -- the same way Belnap's 4-valued logic names its states
 * True/False/Both/Neither. No claim is made that this module provides
 * cryptographic security or distributed-consensus guarantees; those are
 * separately provided by kernel/src/mlkem (real ML-KEM-768) and would
 * require a real consensus protocol (Raft/PBFT-style) respectively.
 *
 * ---- The formal mapping ----
 *
 *   Phases 1-10  : the 10 Sephirot (Keter..Malkuth) -- "light" states.
 *   Da'at        : NOT a numbered phase. A two-way switch/decision
 *                  function (see daat_switch) -- consistent with its
 *                  traditional description as "the non-Sephirah",
 *                  the Abyss gateway between the lower 10 and the
 *                  transcendent phases above.
 *   Phases 11-13 : the 3 Veils of Negative Existence (Ain, Ain Soph,
 *                  Ain Soph Aur) -- these have NO shadow.
 *   Qliphoth     : the 10 shadow states of phases 1-10, related to
 *                  their light counterpart by literal endianness
 *                  inversion (nibble swap) -- a real, reversible,
 *                  testable bit operation, not a metaphor.
 *
 * ---- The algebra ----
 *
 * Phase values are represented as elements of the group ring
 * Q[Z/13Z] (13 exact-rational coefficients indexed by Z/13), rather
 * than the reduced 12-dimensional power basis of Q(zeta_13). This is
 * a deliberate simplification: since x^13-1 = (x-1)*Phi_13(x) over Q
 * with Phi_13 irreducible of degree 12, we have the ring isomorphism
 * Q[x]/(x^13-1) = Q x Q(zeta_13). Working in the full 13-dim
 * permutation representation makes the Galois action sigma_a: zeta
 * -> zeta^a a PURE INDEX PERMUTATION (c'[(a*k) mod 13] = c[k]),
 * eliminating an entire class of Phi_13(x)-reduction bugs, while
 * still faithfully containing Q(zeta_13) as the codimension-1
 * subspace orthogonal to the all-ones vector.
 *
 * Because 13 is prime, Gal(Q(zeta_13)/Q) = (Z/13Z)* is cyclic of
 * order 12, generated by 2 (a primitive root mod 13). Its subgroups
 * correspond (Galois correspondence) to the 6 divisors of 12, giving
 * the 6 "elastic" dimension levels: 1, 2, 3, 4, 6, 12.
 *
 * Author: H.M. Michael-Laurence: Curzi (c)
 * 36N9 Genetics, LLC
 */
#ifndef SEPHIROT_H
#define SEPHIROT_H

#include "m5_types.h"

/* ---- Phase enumeration ---- */

typedef enum {
    SEPH_KETER         = 1,  /* Crown            -- unified source */
    SEPH_CHOKMAH       = 2,  /* Wisdom           -- generative force */
    SEPH_BINAH         = 3,  /* Understanding    -- structuring/differentiation */
    SEPH_CHESED        = 4,  /* Mercy            -- expansive/permissive */
    SEPH_GEVURAH       = 5,  /* Severity         -- restrictive/bounding */
    SEPH_TIFERET       = 6,  /* Beauty           -- harmonizing balance (L6 kernel anchor) */
    SEPH_NETZACH       = 7,  /* Victory          -- persistence/endurance */
    SEPH_HOD           = 8,  /* Splendor         -- structured communication */
    SEPH_YESOD         = 9,  /* Foundation       -- accumulation/staging */
    SEPH_MALKUTH       = 10, /* Kingdom          -- grounded/manifest substrate */
    VEIL_AIN           = 11, /* No-Thing         -- negation of being, no shadow */
    VEIL_AIN_SOPH      = 12, /* The Limitless    -- unbounded potential, no shadow */
    VEIL_AIN_SOPH_AUR  = 13, /* The Limitless Light -- source of emanation, no shadow */
} l13_phase_t;

#define L13_NUM_SEPHIROT 10
#define L13_NUM_PHASES   13

/* ---- Light/Shadow state encoding ----
 * Light state for phase n (1..13): raw phase number in the low
 * nibble, high nibble zero. Shadow (Qliphothic) state exists ONLY
 * for the 10 Sephirot (1..10) and is the SAME value with nibbles
 * swapped (light n -> shadow n<<4). Veils 11-13 have no shadow.
 */
typedef uint8_t l13_state_t;

static inline l13_state_t l13_light(l13_phase_t phase) {
    return (l13_state_t)phase;
}
static inline bool l13_is_light(l13_state_t s) {
    return s >= 1 && s <= L13_NUM_PHASES;
}
static inline bool l13_is_shadow(l13_state_t s) {
    return s != 0 && (s & 0x0F) == 0 && (s >> 4) <= L13_NUM_SEPHIROT;
}
static inline bool l13_has_shadow(l13_phase_t phase) {
    return phase >= SEPH_KETER && phase <= SEPH_MALKUTH;
}
/* Returns 0 (invalid marker) if phase has no shadow (i.e. a veil). */
l13_state_t l13_to_shadow(l13_phase_t phase);
/* Returns 0 (invalid marker) if s is not a well-formed shadow state. */
l13_phase_t l13_to_light(l13_state_t shadow);

/* ---- Exact-rational cyclotomic group ring Q[Z/13Z] ---- */

typedef struct cyc13_t {
    rational_t c[L13_NUM_PHASES]; /* coefficient of zeta^k at index k, k=0..12 */
} cyc13_t;

cyc13_t cyc13_zero(void);
cyc13_t cyc13_basis(uint32_t k);          /* pure zeta^(k mod 13) state */
cyc13_t cyc13_from_phase(l13_phase_t p);  /* phase p -> zeta^(p mod 13) */
cyc13_t cyc13_add(cyc13_t a, cyc13_t b);
cyc13_t cyc13_sub(cyc13_t a, cyc13_t b);
cyc13_t cyc13_mul(cyc13_t a, cyc13_t b);  /* cyclic convolution mod 13 */
cyc13_t cyc13_scale(cyc13_t a, rational_t s);
bool    cyc13_equal(cyc13_t a, cyc13_t b);
bool    cyc13_is_zero(cyc13_t a);

/* Galois automorphism sigma_a: zeta -> zeta^a (a coprime to 13),
 * applied as the index permutation c'[(a*k) mod 13] = c[k]. */
cyc13_t cyc13_galois_apply(cyc13_t a, uint32_t exponent);

/* ---- Galois subfield projection (Dynamic Dimensionality) ----
 * Trace map Tr_H(x) = sum over g in subgroup H of sigma_g(x).
 * (Z/13Z)* = <2> (2 is a primitive root mod 13); the 6 divisors of
 * 12 give exactly the 6 dimension levels below.
 */
typedef enum {
    L13_DIM_1  = 1,   /* subfield = Q itself   : |H| = 12 (whole group) */
    L13_DIM_2  = 2,   /* K2  (quadratic)       : |H| = 6  */
    L13_DIM_3  = 3,   /* K3  (cubic)           : |H| = 4  */
    L13_DIM_4  = 4,   /* K4  (quartic)         : |H| = 3  */
    L13_DIM_6  = 6,   /* K6  (sextic)          : |H| = 2  */
    L13_DIM_12 = 12,  /* full field Q(zeta_13) : |H| = 1 (trivial, identity) */
} l13_dim_t;

cyc13_t l13_project(cyc13_t x, l13_dim_t target_dim);  /* Galois trace projection */

/* ---- Da'at: the two-way switch ----
 * Evaluated on a collapsed cyc13_t state. If the state is exactly
 * the zero vector ("substrate zero"), Da'at resets to Malkuth
 * (grounded base state); otherwise it opens onward to the Veils.
 */
typedef enum { DAAT_RESET = 0, DAAT_CONTINUE = 1 } daat_decision_t;
daat_decision_t daat_switch(cyc13_t collapsed_state);

/* ---- Naming ---- */
const char *l13_phase_name(l13_phase_t phase);
const char *l13_qliphah_name(l13_phase_t sephirah); /* shadow name, 1..10 only */

#endif /* SEPHIROT_H */
