# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate test_speech_fixture.h: Whisper log-mel references for test_speech.c.

The test signals are made from integer formulas (an LCG and a triangle-wave
phase accumulator) that test_speech.c reproduces bit for bit, so the fixture
holds only the reference spectrogram, not the audio. The reference is the
Whisper front end (openai/whisper audio.py log_mel_spectrogram, padding 0)
re-implemented in float64 numpy:

    stft(audio / 32768, n_fft 400, hop 160, periodic Hann, center, reflect)
    magnitudes = |stft[:, :-1]|^2
    mel = filters @ magnitudes      (Slaney, from gen_speech_tables.py)
    log_spec = log10(max(mel, 1e-10))
    log_spec = max(log_spec, log_spec.max() - 8);  (log_spec + 4) / 4

Values are written as Q16 integers (round(x * 65536)). Usage:
    python3 gen_speech_fixture.py test_speech_fixture.h
"""
import os
import shutil
import subprocess
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_speech_tables import slaney_mel_filters, hann_periodic  # noqa: E402

M32 = 0xFFFFFFFF


def lcg(s):
    return (s * 1664525 + 1013904223) & M32


def tri(ph):
    t = ph >> 16
    return 2 * t - 32768 if t < 32768 else 2 * (65535 - t) - 32767


def sat(v):
    return max(-32768, min(32767, v))


def signal_a():
    """1 s: 0.25 s digital silence, a 200 -> 6000 Hz chirp with noise, then a
    quiet 440 Hz tone."""
    out, s, ph = [], 12345, 0
    for i in range(16000):
        s = lcg(s)
        noise = ((s >> 16) & 0x7FF) - 1024
        if i < 4000:
            x = 0
        elif i < 12000:
            f = 200 + (5800 * (i - 4000)) // 8000
            ph = (ph + f * 268435) & M32
            x = ((tri(ph) * 12000) >> 15) + noise
        else:
            ph = (ph + 440 * 268435) & M32
            x = ((tri(ph) * 300) >> 15) + (noise >> 4)
        out.append(sat(x))
    return out


def signal_b():
    """0.5 s of very quiet noise plus a 1 kHz triangle (dynamic-range test)."""
    out, s, ph = [], 999, 0
    for _ in range(8000):
        s = lcg(s)
        ph = (ph + 1000 * 268435) & M32
        out.append(sat(((s >> 16) & 0x3F) - 32 + ((tri(ph) * 40) >> 15)))
    return out


def whisper_logmel(pcm):
    audio = np.asarray(pcm, dtype=np.float64) / 32768.0
    pad = 200
    padded = np.pad(audio, (pad, pad), mode='reflect')
    n_frames = 1 + len(audio) // 160
    win = hann_periodic()
    frames = np.stack([padded[t * 160:t * 160 + 400] * win for t in range(n_frames)])
    spec = np.fft.rfft(frames, axis=1)
    mag = (np.abs(spec) ** 2)[:-1].T            # (201, n_frames - 1)
    mel = slaney_mel_filters() @ mag             # (80, frames)
    log_spec = np.log10(np.maximum(mel, 1e-10))
    log_spec = np.maximum(log_spec, log_spec.max() - 8.0)
    return ((log_spec + 4.0) / 4.0).T            # frame-major (frames, 80)


def emit(name, sig, out):
    ref = whisper_logmel(sig)
    vals = [int(np.round(v * 65536)) for v in ref.reshape(-1)]
    out.append('#define %s_N      %du' % (name, len(sig)))
    out.append('#define %s_FRAMES %du' % (name, ref.shape[0]))
    h = 2166136261
    for v in sig:
        h = ((h ^ (v & 0xFFFF)) * 16777619) & M32
    out.append('#define %s_FNV    0x%08xu /* FNV-1a of the samples: checks the C generator */'
               % (name, h))
    out.append('static const int32_t %s_REF_Q16[%d] = {' % (name, len(vals)))
    for i in range(0, len(vals), 10):
        out.append('    ' + ', '.join(str(v) for v in vals[i:i + 10]) + ',')
    out.append('};')


def main():
    path = sys.argv[1]
    out = ['/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */',
           '/* SPDX-License-Identifier: Apache-2.0 AND '
           'LicenseRef-Royal-Writ-Sicilian-Crown-1.0 AND LicenseRef-SEL-3.3 */',
           '/* test_speech_fixture.h — generated by gen_speech_fixture.py. Do not edit.',
           ' * Float64 numpy Whisper log-mel references, Q16, frame-major. */',
           '#ifndef ZXV_TEST_SPEECH_FIXTURE_H', '#define ZXV_TEST_SPEECH_FIXTURE_H',
           '#include <stdint.h>']
    emit('FIX_A', signal_a(), out)
    emit('FIX_B', signal_b(), out)
    out.append('#endif')
    open(path, 'w').write('\n'.join(out) + '\n')
    cf = shutil.which('clang-format-18') or shutil.which('clang-format')
    if cf:
        subprocess.run([cf, '-i', path], check=True)
        subprocess.run([cf, '-i', path], check=True)


if __name__ == '__main__':
    main()
