# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate speech_tables.h for speech_dsp.c.

Every table the integer front end needs is computed here, offline, in float64
(numpy), then rounded once:

  SPEECH_HANN_Q30[400]   periodic Hann window (torch.hann_window(400) default)
  SPEECH_COS_Q30[400]    cos(2 pi j / 400)
  SPEECH_SIN_Q30[400]    sin(2 pi j / 400)
  SPEECH_MEL_*           80-band Slaney mel filterbank for sr 16000, n_fft 400
                         (the librosa.filters.mel(sr=16000, n_fft=400,
                         n_mels=80) matrix Whisper ships as mel_filters.npz),
                         stored sparse: first bin, bin count, Q32 weights
  SPEECH_LOG2_Q30[1025]  log2(1 + i/1024)
  SPEECH_RS_PROTO_Q24[]  Kaiser-windowed sinc prototype for the resampler

The mel filterbank is re-derived here from the published Slaney formulas so no
librosa install is needed; pass --check-librosa to compare against librosa
when it is installed. Usage:
    python3 gen_speech_tables.py speech_tables.h [--check-librosa]
"""
import shutil
import subprocess
import sys

import numpy as np

SR = 16000
N_FFT = 400
N_MELS = 80
N_BINS = N_FFT // 2 + 1
RS_L = 256       # prototype samples per zero crossing
RS_NZ = 16       # zero crossings on each side
RS_ROLLOFF = 0.90
RS_BETA = 8.0    # Kaiser beta


def hz_to_mel(f):
    f = np.asanyarray(f, dtype=np.float64)
    f_sp = 200.0 / 3
    mels = f / f_sp
    min_log_hz = 1000.0
    min_log_mel = min_log_hz / f_sp
    logstep = np.log(6.4) / 27.0
    return np.where(f >= min_log_hz,
                    min_log_mel + np.log(np.maximum(f, 1e-300) / min_log_hz) / logstep, mels)


def mel_to_hz(m):
    m = np.asanyarray(m, dtype=np.float64)
    f_sp = 200.0 / 3
    freqs = f_sp * m
    min_log_hz = 1000.0
    min_log_mel = min_log_hz / f_sp
    logstep = np.log(6.4) / 27.0
    return np.where(m >= min_log_mel, min_log_hz * np.exp(logstep * (m - min_log_mel)), freqs)


def slaney_mel_filters():
    fftfreqs = np.linspace(0, SR / 2, N_BINS)
    mel_f = mel_to_hz(np.linspace(hz_to_mel(0.0), hz_to_mel(SR / 2.0), N_MELS + 2))
    fdiff = np.diff(mel_f)
    ramps = np.subtract.outer(mel_f, fftfreqs)
    w = np.zeros((N_MELS, N_BINS))
    for i in range(N_MELS):
        lower = -ramps[i] / fdiff[i]
        upper = ramps[i + 2] / fdiff[i + 1]
        w[i] = np.maximum(0, np.minimum(lower, upper))
    enorm = 2.0 / (mel_f[2:N_MELS + 2] - mel_f[:N_MELS])
    return w * enorm[:, None]


def hann_periodic():
    n = np.arange(N_FFT)
    return 0.5 - 0.5 * np.cos(2 * np.pi * n / N_FFT)


def rs_proto():
    t = np.arange(RS_L * RS_NZ + 1) / RS_L        # in zero crossings
    h = RS_ROLLOFF * np.sinc(RS_ROLLOFF * t)
    win = np.i0(RS_BETA * np.sqrt(np.maximum(0.0, 1 - (t / RS_NZ) ** 2))) / np.i0(RS_BETA)
    return h * win


def q(x, bits):
    return int(np.round(x * (1 << bits)))


def arr(name, ctype, vals, per=8):
    out = ['static const %s %s[%d] = {' % (ctype, name, len(vals))]
    for i in range(0, len(vals), per):
        out.append('    ' + ', '.join(str(v) for v in vals[i:i + per]) + ',')
    out.append('};')
    return out


def main():
    path = sys.argv[1]
    mel = slaney_mel_filters()
    if '--check-librosa' in sys.argv:
        import librosa  # noqa: only for the optional cross-check
        ref = librosa.filters.mel(sr=SR, n_fft=N_FFT, n_mels=N_MELS)
        err = float(np.abs(ref.astype(np.float64) - mel).max())
        print('max |librosa - derived| = %.3g' % err)
        assert err < 1e-6
    first, count, weights = [], [], []
    for m in range(N_MELS):
        nz = np.nonzero(mel[m] > 0)[0]
        a, b = int(nz[0]), int(nz[-1])
        first.append(a)
        count.append(b - a + 1)
        weights += [q(mel[m, k], 32) for k in range(a, b + 1)]
    assert max(weights) < (1 << 32)
    for m in range(N_MELS):
        assert sum(mel[m]) < 2.0  # keeps the uint64 mel accumulator in range
    offs, o = [], 0
    for c in count:
        offs.append(o)
        o += c

    out = ['/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */',
           '/* SPDX-License-Identifier: Apache-2.0 AND '
           'LicenseRef-Royal-Writ-Sicilian-Crown-1.0 AND LicenseRef-SEL-3.3 */',
           '/* speech_tables.h — generated by gen_speech_tables.py. Do not edit. */',
           '#ifndef ZXV_SPEECH_TABLES_H', '#define ZXV_SPEECH_TABLES_H', '#include <stdint.h>']
    out += arr('SPEECH_HANN_Q30', 'int32_t', [q(v, 30) for v in hann_periodic()])
    j = np.arange(N_FFT)
    out += arr('SPEECH_COS_Q30', 'int32_t', [q(v, 30) for v in np.cos(2 * np.pi * j / N_FFT)])
    out += arr('SPEECH_SIN_Q30', 'int32_t', [q(v, 30) for v in np.sin(2 * np.pi * j / N_FFT)])
    out += arr('SPEECH_MEL_FIRST', 'uint8_t', first, 16)
    out += arr('SPEECH_MEL_COUNT', 'uint8_t', count, 16)
    out += arr('SPEECH_MEL_OFFSET', 'uint16_t', offs, 12)
    out.append('#define SPEECH_MEL_NWEIGHTS %du' % len(weights))
    out += arr('SPEECH_MEL_W_Q32', 'uint32_t', ['%du' % w for w in weights])
    lg = [q(np.log2(1 + i / 1024.0), 30) for i in range(1025)]
    out += arr('SPEECH_LOG2_Q30', 'uint32_t', ['%du' % v for v in lg])
    out.append('#define SPEECH_LOG10_2_Q30 %d' % q(np.log10(2.0), 30))
    out.append('#define SPEECH_RS_L  %du' % RS_L)
    out.append('#define SPEECH_RS_NZ %du' % RS_NZ)
    out += arr('SPEECH_RS_PROTO_Q24', 'int32_t', [q(v, 24) for v in rs_proto()])
    out.append('#endif /* ZXV_SPEECH_TABLES_H */')
    open(path, 'w').write('\n'.join(out) + '\n')
    cf = shutil.which('clang-format-18') or shutil.which('clang-format')
    if cf:
        subprocess.run([cf, '-i', path], check=True)
        subprocess.run([cf, '-i', path], check=True)


if __name__ == '__main__':
    main()
