/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/* cb_ccy_tbl.c - GENERATED by gen_cb_tables.py. Do not edit by hand.
 * ISO 4217 list one Pblshd=2026-01-01 (SIX Financial Information);
 * ISO 3166-1 from Debian iso-codes 4.16.0; AU membership as of 2026-10-09. */
#include "cb_ccy.h"

const char cb_iso4217_published[] = "2026-01-01";
const char cb_au_asof[] = "2026-10-09";

const cb_ccy_t cb_ccy_tbl[CB_CCY_COUNT] = {
    {"AED", 784, 2, 0, "UAE Dirham"},
    {"AFN", 971, 2, 0, "Afghani"},
    {"ALL", 8, 2, 0, "Lek"},
    {"AMD", 51, 2, 0, "Armenian Dram"},
    {"AOA", 973, 2, 0, "Kwanza"},
    {"ARS", 32, 2, 0, "Argentine Peso"},
    {"AUD", 36, 2, 0, "Australian Dollar"},
    {"AWG", 533, 2, 0, "Aruban Florin"},
    {"AZN", 944, 2, 0, "Azerbaijan Manat"},
    {"BAM", 977, 2, 0, "Convertible Mark"},
    {"BBD", 52, 2, 0, "Barbados Dollar"},
    {"BDT", 50, 2, 0, "Taka"},
    {"BHD", 48, 3, 0, "Bahraini Dinar"},
    {"BIF", 108, 0, 0, "Burundi Franc"},
    {"BMD", 60, 2, 0, "Bermudian Dollar"},
    {"BND", 96, 2, 0, "Brunei Dollar"},
    {"BOB", 68, 2, 0, "Boliviano"},
    {"BOV", 984, 2, CB_CCYF_FUND, "Mvdol"},
    {"BRL", 986, 2, 0, "Brazilian Real"},
    {"BSD", 44, 2, 0, "Bahamian Dollar"},
    {"BTN", 64, 2, 0, "Ngultrum"},
    {"BWP", 72, 2, 0, "Pula"},
    {"BYN", 933, 2, 0, "Belarusian Ruble"},
    {"BZD", 84, 2, 0, "Belize Dollar"},
    {"CAD", 124, 2, 0, "Canadian Dollar"},
    {"CDF", 976, 2, 0, "Congolese Franc"},
    {"CHE", 947, 2, CB_CCYF_FUND, "WIR Euro"},
    {"CHF", 756, 2, 0, "Swiss Franc"},
    {"CHW", 948, 2, CB_CCYF_FUND, "WIR Franc"},
    {"CLF", 990, 4, CB_CCYF_FUND, "Unidad de Fomento"},
    {"CLP", 152, 0, 0, "Chilean Peso"},
    {"CNY", 156, 2, 0, "Yuan Renminbi"},
    {"COP", 170, 2, 0, "Colombian Peso"},
    {"COU", 970, 2, CB_CCYF_FUND, "Unidad de Valor Real"},
    {"CRC", 188, 2, 0, "Costa Rican Colon"},
    {"CUP", 192, 2, 0, "Cuban Peso"},
    {"CVE", 132, 2, 0, "Cabo Verde Escudo"},
    {"CZK", 203, 2, 0, "Czech Koruna"},
    {"DJF", 262, 0, 0, "Djibouti Franc"},
    {"DKK", 208, 2, 0, "Danish Krone"},
    {"DOP", 214, 2, 0, "Dominican Peso"},
    {"DZD", 12, 2, 0, "Algerian Dinar"},
    {"EGP", 818, 2, 0, "Egyptian Pound"},
    {"ERN", 232, 2, 0, "Nakfa"},
    {"ETB", 230, 2, 0, "Ethiopian Birr"},
    {"EUR", 978, 2, 0, "Euro"},
    {"FJD", 242, 2, 0, "Fiji Dollar"},
    {"FKP", 238, 2, 0, "Falkland Islands Pound"},
    {"GBP", 826, 2, 0, "Pound Sterling"},
    {"GEL", 981, 2, 0, "Lari"},
    {"GHS", 936, 2, 0, "Ghana Cedi"},
    {"GIP", 292, 2, 0, "Gibraltar Pound"},
    {"GMD", 270, 2, 0, "Dalasi"},
    {"GNF", 324, 0, 0, "Guinean Franc"},
    {"GTQ", 320, 2, 0, "Quetzal"},
    {"GYD", 328, 2, 0, "Guyana Dollar"},
    {"HKD", 344, 2, 0, "Hong Kong Dollar"},
    {"HNL", 340, 2, 0, "Lempira"},
    {"HTG", 332, 2, 0, "Gourde"},
    {"HUF", 348, 2, 0, "Forint"},
    {"IDR", 360, 2, 0, "Rupiah"},
    {"ILS", 376, 2, 0, "New Israeli Sheqel"},
    {"INR", 356, 2, 0, "Indian Rupee"},
    {"IQD", 368, 3, 0, "Iraqi Dinar"},
    {"IRR", 364, 2, 0, "Iranian Rial"},
    {"ISK", 352, 0, 0, "Iceland Krona"},
    {"JMD", 388, 2, 0, "Jamaican Dollar"},
    {"JOD", 400, 3, 0, "Jordanian Dinar"},
    {"JPY", 392, 0, 0, "Yen"},
    {"KES", 404, 2, 0, "Kenyan Shilling"},
    {"KGS", 417, 2, 0, "Som"},
    {"KHR", 116, 2, 0, "Riel"},
    {"KMF", 174, 0, 0, "Comorian Franc"},
    {"KPW", 408, 2, 0, "North Korean Won"},
    {"KRW", 410, 0, 0, "Won"},
    {"KWD", 414, 3, 0, "Kuwaiti Dinar"},
    {"KYD", 136, 2, 0, "Cayman Islands Dollar"},
    {"KZT", 398, 2, 0, "Tenge"},
    {"LAK", 418, 2, 0, "Lao Kip"},
    {"LBP", 422, 2, 0, "Lebanese Pound"},
    {"LKR", 144, 2, 0, "Sri Lanka Rupee"},
    {"LRD", 430, 2, 0, "Liberian Dollar"},
    {"LSL", 426, 2, 0, "Loti"},
    {"LYD", 434, 3, 0, "Libyan Dinar"},
    {"MAD", 504, 2, 0, "Moroccan Dirham"},
    {"MDL", 498, 2, 0, "Moldovan Leu"},
    {"MGA", 969, 2, 0, "Malagasy Ariary"},
    {"MKD", 807, 2, 0, "Denar"},
    {"MMK", 104, 2, 0, "Kyat"},
    {"MNT", 496, 2, 0, "Tugrik"},
    {"MOP", 446, 2, 0, "Pataca"},
    {"MRU", 929, 2, 0, "Ouguiya"},
    {"MUR", 480, 2, 0, "Mauritius Rupee"},
    {"MVR", 462, 2, 0, "Rufiyaa"},
    {"MWK", 454, 2, 0, "Malawi Kwacha"},
    {"MXN", 484, 2, 0, "Mexican Peso"},
    {"MXV", 979, 2, CB_CCYF_FUND, "Mexican Unidad de Inversion (UDI)"},
    {"MYR", 458, 2, 0, "Malaysian Ringgit"},
    {"MZN", 943, 2, 0, "Mozambique Metical"},
    {"NAD", 516, 2, 0, "Namibia Dollar"},
    {"NGN", 566, 2, 0, "Naira"},
    {"NIO", 558, 2, 0, "Cordoba Oro"},
    {"NOK", 578, 2, 0, "Norwegian Krone"},
    {"NPR", 524, 2, 0, "Nepalese Rupee"},
    {"NZD", 554, 2, 0, "New Zealand Dollar"},
    {"OMR", 512, 3, 0, "Rial Omani"},
    {"PAB", 590, 2, 0, "Balboa"},
    {"PEN", 604, 2, 0, "Sol"},
    {"PGK", 598, 2, 0, "Kina"},
    {"PHP", 608, 2, 0, "Philippine Peso"},
    {"PKR", 586, 2, 0, "Pakistan Rupee"},
    {"PLN", 985, 2, 0, "Zloty"},
    {"PYG", 600, 0, 0, "Guarani"},
    {"QAR", 634, 2, 0, "Qatari Rial"},
    {"RON", 946, 2, 0, "Romanian Leu"},
    {"RSD", 941, 2, 0, "Serbian Dinar"},
    {"RUB", 643, 2, 0, "Russian Ruble"},
    {"RWF", 646, 0, 0, "Rwanda Franc"},
    {"SAR", 682, 2, 0, "Saudi Riyal"},
    {"SBD", 90, 2, 0, "Solomon Islands Dollar"},
    {"SCR", 690, 2, 0, "Seychelles Rupee"},
    {"SDG", 938, 2, 0, "Sudanese Pound"},
    {"SEK", 752, 2, 0, "Swedish Krona"},
    {"SGD", 702, 2, 0, "Singapore Dollar"},
    {"SHP", 654, 2, 0, "Saint Helena Pound"},
    {"SLE", 925, 2, 0, "Leone"},
    {"SOS", 706, 2, 0, "Somali Shilling"},
    {"SRD", 968, 2, 0, "Surinam Dollar"},
    {"SSP", 728, 2, 0, "South Sudanese Pound"},
    {"STN", 930, 2, 0, "Dobra"},
    {"SVC", 222, 2, 0, "El Salvador Colon"},
    {"SYP", 760, 2, 0, "Syrian Pound"},
    {"SZL", 748, 2, 0, "Lilangeni"},
    {"THB", 764, 2, 0, "Baht"},
    {"TJS", 972, 2, 0, "Somoni"},
    {"TMT", 934, 2, 0, "Turkmenistan New Manat"},
    {"TND", 788, 3, 0, "Tunisian Dinar"},
    {"TOP", 776, 2, 0, "Paanga"},
    {"TRY", 949, 2, 0, "Turkish Lira"},
    {"TTD", 780, 2, 0, "Trinidad and Tobago Dollar"},
    {"TWD", 901, 2, 0, "New Taiwan Dollar"},
    {"TZS", 834, 2, 0, "Tanzanian Shilling"},
    {"UAH", 980, 2, 0, "Hryvnia"},
    {"UGX", 800, 0, 0, "Uganda Shilling"},
    {"USD", 840, 2, 0, "US Dollar"},
    {"USN", 997, 2, CB_CCYF_FUND, "US Dollar (Next day)"},
    {"UYI", 940, 0, CB_CCYF_FUND, "Uruguay Peso en Unidades Indexadas (UI)"},
    {"UYU", 858, 2, 0, "Peso Uruguayo"},
    {"UYW", 927, 4, 0, "Unidad Previsional"},
    {"UZS", 860, 2, 0, "Uzbekistan Sum"},
    {"VED", 926, 2, 0, "Bolivar Soberano"},
    {"VES", 928, 2, 0, "Bolivar Soberano"},
    {"VND", 704, 0, 0, "Dong"},
    {"VUV", 548, 0, 0, "Vatu"},
    {"WST", 882, 2, 0, "Tala"},
    {"XAD", 396, 2, CB_CCYF_NOCTRY, "Arab Accounting Dinar"},
    {"XAF", 950, 0, 0, "CFA Franc BEAC"},
    {"XAG", 961, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Silver"},
    {"XAU", 959, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Gold"},
    {"XBA", 955, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Bond Markets Unit European Composite Unit (EURCO)"},
    {"XBB", 956, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Bond Markets Unit European Monetary Unit (E.M.U.-6)"},
    {"XBC", 957, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"},
    {"XBD", 958, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"},
    {"XCD", 951, 2, 0, "East Caribbean Dollar"},
    {"XCG", 532, 2, 0, "Caribbean Guilder"},
    {"XDR", 960, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "SDR (Special Drawing Right)"},
    {"XOF", 952, 0, 0, "CFA Franc BCEAO"},
    {"XPD", 964, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Palladium"},
    {"XPF", 953, 0, 0, "CFP Franc"},
    {"XPT", 962, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Platinum"},
    {"XSU", 994, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Sucre"},
    {"XTS", 963, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "Codes specifically reserved for testing purposes"},
    {"XUA", 965, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "ADB Unit of Account"},
    {"XXX", 999, 255, CB_CCYF_NA|CB_CCYF_NOCTRY, "The codes assigned for transactions where no currency is involved"},
    {"YER", 886, 2, 0, "Yemeni Rial"},
    {"ZAR", 710, 2, 0, "Rand"},
    {"ZMW", 967, 2, 0, "Zambian Kwacha"},
    {"ZWG", 924, 2, 0, "Zimbabwe Gold"},
};

const uint16_t cb_ccy_by_num_idx[CB_CCY_COUNT] = {
    2, 41, 5, 6, 19, 12, 11, 3, 10, 14, 20, 16,
    21, 23, 119, 15, 88, 13, 71, 24, 36, 76, 80, 30,
    31, 32, 72, 34, 35, 37, 39, 40, 130, 44, 43, 47,
    46, 38, 52, 51, 54, 53, 55, 58, 57, 56, 59, 65,
    62, 60, 64, 63, 61, 66, 68, 155, 77, 67, 69, 73,
    74, 75, 70, 78, 79, 82, 81, 83, 90, 94, 97, 93,
    92, 95, 89, 85, 84, 105, 99, 103, 164, 7, 153, 104,
    101, 100, 102, 110, 106, 108, 112, 107, 109, 113, 116, 117,
    124, 118, 120, 123, 152, 126, 175, 128, 132, 122, 27, 131,
    133, 137, 139, 0, 136, 143, 87, 42, 48, 141, 144, 147,
    149, 154, 174, 140, 177, 125, 150, 148, 151, 91, 129, 22,
    135, 50, 121, 146, 115, 98, 8, 114, 26, 28, 138, 156,
    163, 166, 168, 159, 160, 161, 162, 158, 165, 157, 169, 171,
    167, 172, 176, 127, 86, 33, 1, 134, 4, 25, 9, 45,
    96, 142, 49, 17, 111, 18, 29, 170, 145, 173,
};

const cb_country_t cb_country_tbl[CB_COUNTRY_COUNT] = {
    {"AD", "AND", 20, "Andorra"},
    {"AE", "ARE", 784, "United Arab Emirates"},
    {"AF", "AFG", 4, "Afghanistan"},
    {"AG", "ATG", 28, "Antigua and Barbuda"},
    {"AI", "AIA", 660, "Anguilla"},
    {"AL", "ALB", 8, "Albania"},
    {"AM", "ARM", 51, "Armenia"},
    {"AO", "AGO", 24, "Angola"},
    {"AQ", "ATA", 10, "Antarctica"},
    {"AR", "ARG", 32, "Argentina"},
    {"AS", "ASM", 16, "American Samoa"},
    {"AT", "AUT", 40, "Austria"},
    {"AU", "AUS", 36, "Australia"},
    {"AW", "ABW", 533, "Aruba"},
    {"AX", "ALA", 248, "Aland Islands"},
    {"AZ", "AZE", 31, "Azerbaijan"},
    {"BA", "BIH", 70, "Bosnia and Herzegovina"},
    {"BB", "BRB", 52, "Barbados"},
    {"BD", "BGD", 50, "Bangladesh"},
    {"BE", "BEL", 56, "Belgium"},
    {"BF", "BFA", 854, "Burkina Faso"},
    {"BG", "BGR", 100, "Bulgaria"},
    {"BH", "BHR", 48, "Bahrain"},
    {"BI", "BDI", 108, "Burundi"},
    {"BJ", "BEN", 204, "Benin"},
    {"BL", "BLM", 652, "Saint Barthelemy"},
    {"BM", "BMU", 60, "Bermuda"},
    {"BN", "BRN", 96, "Brunei Darussalam"},
    {"BO", "BOL", 68, "Bolivia"},
    {"BQ", "BES", 535, "Bonaire, Sint Eustatius and Saba"},
    {"BR", "BRA", 76, "Brazil"},
    {"BS", "BHS", 44, "Bahamas"},
    {"BT", "BTN", 64, "Bhutan"},
    {"BV", "BVT", 74, "Bouvet Island"},
    {"BW", "BWA", 72, "Botswana"},
    {"BY", "BLR", 112, "Belarus"},
    {"BZ", "BLZ", 84, "Belize"},
    {"CA", "CAN", 124, "Canada"},
    {"CC", "CCK", 166, "Cocos (Keeling) Islands"},
    {"CD", "COD", 180, "Congo, The Democratic Republic of the"},
    {"CF", "CAF", 140, "Central African Republic"},
    {"CG", "COG", 178, "Congo"},
    {"CH", "CHE", 756, "Switzerland"},
    {"CI", "CIV", 384, "Cote d'Ivoire"},
    {"CK", "COK", 184, "Cook Islands"},
    {"CL", "CHL", 152, "Chile"},
    {"CM", "CMR", 120, "Cameroon"},
    {"CN", "CHN", 156, "China"},
    {"CO", "COL", 170, "Colombia"},
    {"CR", "CRI", 188, "Costa Rica"},
    {"CU", "CUB", 192, "Cuba"},
    {"CV", "CPV", 132, "Cabo Verde"},
    {"CW", "CUW", 531, "Curacao"},
    {"CX", "CXR", 162, "Christmas Island"},
    {"CY", "CYP", 196, "Cyprus"},
    {"CZ", "CZE", 203, "Czechia"},
    {"DE", "DEU", 276, "Germany"},
    {"DJ", "DJI", 262, "Djibouti"},
    {"DK", "DNK", 208, "Denmark"},
    {"DM", "DMA", 212, "Dominica"},
    {"DO", "DOM", 214, "Dominican Republic"},
    {"DZ", "DZA", 12, "Algeria"},
    {"EC", "ECU", 218, "Ecuador"},
    {"EE", "EST", 233, "Estonia"},
    {"EG", "EGY", 818, "Egypt"},
    {"EH", "ESH", 732, "Western Sahara"},
    {"ER", "ERI", 232, "Eritrea"},
    {"ES", "ESP", 724, "Spain"},
    {"ET", "ETH", 231, "Ethiopia"},
    {"FI", "FIN", 246, "Finland"},
    {"FJ", "FJI", 242, "Fiji"},
    {"FK", "FLK", 238, "Falkland Islands (Malvinas)"},
    {"FM", "FSM", 583, "Micronesia, Federated States of"},
    {"FO", "FRO", 234, "Faroe Islands"},
    {"FR", "FRA", 250, "France"},
    {"GA", "GAB", 266, "Gabon"},
    {"GB", "GBR", 826, "United Kingdom"},
    {"GD", "GRD", 308, "Grenada"},
    {"GE", "GEO", 268, "Georgia"},
    {"GF", "GUF", 254, "French Guiana"},
    {"GG", "GGY", 831, "Guernsey"},
    {"GH", "GHA", 288, "Ghana"},
    {"GI", "GIB", 292, "Gibraltar"},
    {"GL", "GRL", 304, "Greenland"},
    {"GM", "GMB", 270, "Gambia"},
    {"GN", "GIN", 324, "Guinea"},
    {"GP", "GLP", 312, "Guadeloupe"},
    {"GQ", "GNQ", 226, "Equatorial Guinea"},
    {"GR", "GRC", 300, "Greece"},
    {"GS", "SGS", 239, "South Georgia and the South Sandwich Islands"},
    {"GT", "GTM", 320, "Guatemala"},
    {"GU", "GUM", 316, "Guam"},
    {"GW", "GNB", 624, "Guinea-Bissau"},
    {"GY", "GUY", 328, "Guyana"},
    {"HK", "HKG", 344, "Hong Kong"},
    {"HM", "HMD", 334, "Heard Island and McDonald Islands"},
    {"HN", "HND", 340, "Honduras"},
    {"HR", "HRV", 191, "Croatia"},
    {"HT", "HTI", 332, "Haiti"},
    {"HU", "HUN", 348, "Hungary"},
    {"ID", "IDN", 360, "Indonesia"},
    {"IE", "IRL", 372, "Ireland"},
    {"IL", "ISR", 376, "Israel"},
    {"IM", "IMN", 833, "Isle of Man"},
    {"IN", "IND", 356, "India"},
    {"IO", "IOT", 86, "British Indian Ocean Territory"},
    {"IQ", "IRQ", 368, "Iraq"},
    {"IR", "IRN", 364, "Iran"},
    {"IS", "ISL", 352, "Iceland"},
    {"IT", "ITA", 380, "Italy"},
    {"JE", "JEY", 832, "Jersey"},
    {"JM", "JAM", 388, "Jamaica"},
    {"JO", "JOR", 400, "Jordan"},
    {"JP", "JPN", 392, "Japan"},
    {"KE", "KEN", 404, "Kenya"},
    {"KG", "KGZ", 417, "Kyrgyzstan"},
    {"KH", "KHM", 116, "Cambodia"},
    {"KI", "KIR", 296, "Kiribati"},
    {"KM", "COM", 174, "Comoros"},
    {"KN", "KNA", 659, "Saint Kitts and Nevis"},
    {"KP", "PRK", 408, "North Korea"},
    {"KR", "KOR", 410, "South Korea"},
    {"KW", "KWT", 414, "Kuwait"},
    {"KY", "CYM", 136, "Cayman Islands"},
    {"KZ", "KAZ", 398, "Kazakhstan"},
    {"LA", "LAO", 418, "Laos"},
    {"LB", "LBN", 422, "Lebanon"},
    {"LC", "LCA", 662, "Saint Lucia"},
    {"LI", "LIE", 438, "Liechtenstein"},
    {"LK", "LKA", 144, "Sri Lanka"},
    {"LR", "LBR", 430, "Liberia"},
    {"LS", "LSO", 426, "Lesotho"},
    {"LT", "LTU", 440, "Lithuania"},
    {"LU", "LUX", 442, "Luxembourg"},
    {"LV", "LVA", 428, "Latvia"},
    {"LY", "LBY", 434, "Libya"},
    {"MA", "MAR", 504, "Morocco"},
    {"MC", "MCO", 492, "Monaco"},
    {"MD", "MDA", 498, "Moldova"},
    {"ME", "MNE", 499, "Montenegro"},
    {"MF", "MAF", 663, "Saint Martin (French part)"},
    {"MG", "MDG", 450, "Madagascar"},
    {"MH", "MHL", 584, "Marshall Islands"},
    {"MK", "MKD", 807, "North Macedonia"},
    {"ML", "MLI", 466, "Mali"},
    {"MM", "MMR", 104, "Myanmar"},
    {"MN", "MNG", 496, "Mongolia"},
    {"MO", "MAC", 446, "Macao"},
    {"MP", "MNP", 580, "Northern Mariana Islands"},
    {"MQ", "MTQ", 474, "Martinique"},
    {"MR", "MRT", 478, "Mauritania"},
    {"MS", "MSR", 500, "Montserrat"},
    {"MT", "MLT", 470, "Malta"},
    {"MU", "MUS", 480, "Mauritius"},
    {"MV", "MDV", 462, "Maldives"},
    {"MW", "MWI", 454, "Malawi"},
    {"MX", "MEX", 484, "Mexico"},
    {"MY", "MYS", 458, "Malaysia"},
    {"MZ", "MOZ", 508, "Mozambique"},
    {"NA", "NAM", 516, "Namibia"},
    {"NC", "NCL", 540, "New Caledonia"},
    {"NE", "NER", 562, "Niger"},
    {"NF", "NFK", 574, "Norfolk Island"},
    {"NG", "NGA", 566, "Nigeria"},
    {"NI", "NIC", 558, "Nicaragua"},
    {"NL", "NLD", 528, "Netherlands"},
    {"NO", "NOR", 578, "Norway"},
    {"NP", "NPL", 524, "Nepal"},
    {"NR", "NRU", 520, "Nauru"},
    {"NU", "NIU", 570, "Niue"},
    {"NZ", "NZL", 554, "New Zealand"},
    {"OM", "OMN", 512, "Oman"},
    {"PA", "PAN", 591, "Panama"},
    {"PE", "PER", 604, "Peru"},
    {"PF", "PYF", 258, "French Polynesia"},
    {"PG", "PNG", 598, "Papua New Guinea"},
    {"PH", "PHL", 608, "Philippines"},
    {"PK", "PAK", 586, "Pakistan"},
    {"PL", "POL", 616, "Poland"},
    {"PM", "SPM", 666, "Saint Pierre and Miquelon"},
    {"PN", "PCN", 612, "Pitcairn"},
    {"PR", "PRI", 630, "Puerto Rico"},
    {"PS", "PSE", 275, "Palestine, State of"},
    {"PT", "PRT", 620, "Portugal"},
    {"PW", "PLW", 585, "Palau"},
    {"PY", "PRY", 600, "Paraguay"},
    {"QA", "QAT", 634, "Qatar"},
    {"RE", "REU", 638, "Reunion"},
    {"RO", "ROU", 642, "Romania"},
    {"RS", "SRB", 688, "Serbia"},
    {"RU", "RUS", 643, "Russian Federation"},
    {"RW", "RWA", 646, "Rwanda"},
    {"SA", "SAU", 682, "Saudi Arabia"},
    {"SB", "SLB", 90, "Solomon Islands"},
    {"SC", "SYC", 690, "Seychelles"},
    {"SD", "SDN", 729, "Sudan"},
    {"SE", "SWE", 752, "Sweden"},
    {"SG", "SGP", 702, "Singapore"},
    {"SH", "SHN", 654, "Saint Helena, Ascension and Tristan da Cunha"},
    {"SI", "SVN", 705, "Slovenia"},
    {"SJ", "SJM", 744, "Svalbard and Jan Mayen"},
    {"SK", "SVK", 703, "Slovakia"},
    {"SL", "SLE", 694, "Sierra Leone"},
    {"SM", "SMR", 674, "San Marino"},
    {"SN", "SEN", 686, "Senegal"},
    {"SO", "SOM", 706, "Somalia"},
    {"SR", "SUR", 740, "Suriname"},
    {"SS", "SSD", 728, "South Sudan"},
    {"ST", "STP", 678, "Sao Tome and Principe"},
    {"SV", "SLV", 222, "El Salvador"},
    {"SX", "SXM", 534, "Sint Maarten (Dutch part)"},
    {"SY", "SYR", 760, "Syria"},
    {"SZ", "SWZ", 748, "Eswatini"},
    {"TC", "TCA", 796, "Turks and Caicos Islands"},
    {"TD", "TCD", 148, "Chad"},
    {"TF", "ATF", 260, "French Southern Territories"},
    {"TG", "TGO", 768, "Togo"},
    {"TH", "THA", 764, "Thailand"},
    {"TJ", "TJK", 762, "Tajikistan"},
    {"TK", "TKL", 772, "Tokelau"},
    {"TL", "TLS", 626, "Timor-Leste"},
    {"TM", "TKM", 795, "Turkmenistan"},
    {"TN", "TUN", 788, "Tunisia"},
    {"TO", "TON", 776, "Tonga"},
    {"TR", "TUR", 792, "Turkiye"},
    {"TT", "TTO", 780, "Trinidad and Tobago"},
    {"TV", "TUV", 798, "Tuvalu"},
    {"TW", "TWN", 158, "Taiwan"},
    {"TZ", "TZA", 834, "Tanzania"},
    {"UA", "UKR", 804, "Ukraine"},
    {"UG", "UGA", 800, "Uganda"},
    {"UM", "UMI", 581, "United States Minor Outlying Islands"},
    {"US", "USA", 840, "United States"},
    {"UY", "URY", 858, "Uruguay"},
    {"UZ", "UZB", 860, "Uzbekistan"},
    {"VA", "VAT", 336, "Holy See (Vatican City State)"},
    {"VC", "VCT", 670, "Saint Vincent and the Grenadines"},
    {"VE", "VEN", 862, "Venezuela"},
    {"VG", "VGB", 92, "Virgin Islands, British"},
    {"VI", "VIR", 850, "Virgin Islands, U.S."},
    {"VN", "VNM", 704, "Vietnam"},
    {"VU", "VUT", 548, "Vanuatu"},
    {"WF", "WLF", 876, "Wallis and Futuna"},
    {"WS", "WSM", 882, "Samoa"},
    {"YE", "YEM", 887, "Yemen"},
    {"YT", "MYT", 175, "Mayotte"},
    {"ZA", "ZAF", 710, "South Africa"},
    {"ZM", "ZMB", 894, "Zambia"},
    {"ZW", "ZWE", 716, "Zimbabwe"},
};

const cb_ctry_ccy_t cb_ctry_ccy_tbl[CB_CTRY_CCY_COUNT] = {
    {"AD", 45}, /* EUR */
    {"AE", 0}, /* AED */
    {"AF", 1}, /* AFN */
    {"AG", 163}, /* XCD */
    {"AI", 163}, /* XCD */
    {"AL", 2}, /* ALL */
    {"AM", 3}, /* AMD */
    {"AO", 4}, /* AOA */
    {"AR", 5}, /* ARS */
    {"AS", 144}, /* USD */
    {"AT", 45}, /* EUR */
    {"AU", 6}, /* AUD */
    {"AW", 7}, /* AWG */
    {"AX", 45}, /* EUR */
    {"AZ", 8}, /* AZN */
    {"BA", 9}, /* BAM */
    {"BB", 10}, /* BBD */
    {"BD", 11}, /* BDT */
    {"BE", 45}, /* EUR */
    {"BF", 166}, /* XOF */
    {"BG", 45}, /* EUR */
    {"BH", 12}, /* BHD */
    {"BI", 13}, /* BIF */
    {"BJ", 166}, /* XOF */
    {"BL", 45}, /* EUR */
    {"BM", 14}, /* BMD */
    {"BN", 15}, /* BND */
    {"BO", 16}, /* BOB */
    {"BO", 17}, /* BOV */
    {"BQ", 144}, /* USD */
    {"BR", 18}, /* BRL */
    {"BS", 19}, /* BSD */
    {"BT", 20}, /* BTN */
    {"BT", 62}, /* INR */
    {"BV", 102}, /* NOK */
    {"BW", 21}, /* BWP */
    {"BY", 22}, /* BYN */
    {"BZ", 23}, /* BZD */
    {"CA", 24}, /* CAD */
    {"CC", 6}, /* AUD */
    {"CD", 25}, /* CDF */
    {"CF", 156}, /* XAF */
    {"CG", 156}, /* XAF */
    {"CH", 26}, /* CHE */
    {"CH", 27}, /* CHF */
    {"CH", 28}, /* CHW */
    {"CI", 166}, /* XOF */
    {"CK", 104}, /* NZD */
    {"CL", 29}, /* CLF */
    {"CL", 30}, /* CLP */
    {"CM", 156}, /* XAF */
    {"CN", 31}, /* CNY */
    {"CO", 32}, /* COP */
    {"CO", 33}, /* COU */
    {"CR", 34}, /* CRC */
    {"CU", 35}, /* CUP */
    {"CV", 36}, /* CVE */
    {"CW", 164}, /* XCG */
    {"CX", 6}, /* AUD */
    {"CY", 45}, /* EUR */
    {"CZ", 37}, /* CZK */
    {"DE", 45}, /* EUR */
    {"DJ", 38}, /* DJF */
    {"DK", 39}, /* DKK */
    {"DM", 163}, /* XCD */
    {"DO", 40}, /* DOP */
    {"DZ", 41}, /* DZD */
    {"EC", 144}, /* USD */
    {"EE", 45}, /* EUR */
    {"EG", 42}, /* EGP */
    {"EH", 84}, /* MAD */
    {"ER", 43}, /* ERN */
    {"ES", 45}, /* EUR */
    {"ET", 44}, /* ETB */
    {"FI", 45}, /* EUR */
    {"FJ", 46}, /* FJD */
    {"FK", 47}, /* FKP */
    {"FM", 144}, /* USD */
    {"FO", 39}, /* DKK */
    {"FR", 45}, /* EUR */
    {"GA", 156}, /* XAF */
    {"GB", 48}, /* GBP */
    {"GD", 163}, /* XCD */
    {"GE", 49}, /* GEL */
    {"GF", 45}, /* EUR */
    {"GG", 48}, /* GBP */
    {"GH", 50}, /* GHS */
    {"GI", 51}, /* GIP */
    {"GL", 39}, /* DKK */
    {"GM", 52}, /* GMD */
    {"GN", 53}, /* GNF */
    {"GP", 45}, /* EUR */
    {"GQ", 156}, /* XAF */
    {"GR", 45}, /* EUR */
    {"GT", 54}, /* GTQ */
    {"GU", 144}, /* USD */
    {"GW", 166}, /* XOF */
    {"GY", 55}, /* GYD */
    {"HK", 56}, /* HKD */
    {"HM", 6}, /* AUD */
    {"HN", 57}, /* HNL */
    {"HR", 45}, /* EUR */
    {"HT", 58}, /* HTG */
    {"HT", 144}, /* USD */
    {"HU", 59}, /* HUF */
    {"ID", 60}, /* IDR */
    {"IE", 45}, /* EUR */
    {"IL", 61}, /* ILS */
    {"IM", 48}, /* GBP */
    {"IN", 62}, /* INR */
    {"IO", 144}, /* USD */
    {"IQ", 63}, /* IQD */
    {"IR", 64}, /* IRR */
    {"IS", 65}, /* ISK */
    {"IT", 45}, /* EUR */
    {"JE", 48}, /* GBP */
    {"JM", 66}, /* JMD */
    {"JO", 67}, /* JOD */
    {"JP", 68}, /* JPY */
    {"KE", 69}, /* KES */
    {"KG", 70}, /* KGS */
    {"KH", 71}, /* KHR */
    {"KI", 6}, /* AUD */
    {"KM", 72}, /* KMF */
    {"KN", 163}, /* XCD */
    {"KP", 73}, /* KPW */
    {"KR", 74}, /* KRW */
    {"KW", 75}, /* KWD */
    {"KY", 76}, /* KYD */
    {"KZ", 77}, /* KZT */
    {"LA", 78}, /* LAK */
    {"LB", 79}, /* LBP */
    {"LC", 163}, /* XCD */
    {"LI", 27}, /* CHF */
    {"LK", 80}, /* LKR */
    {"LR", 81}, /* LRD */
    {"LS", 82}, /* LSL */
    {"LS", 175}, /* ZAR */
    {"LT", 45}, /* EUR */
    {"LU", 45}, /* EUR */
    {"LV", 45}, /* EUR */
    {"LY", 83}, /* LYD */
    {"MA", 84}, /* MAD */
    {"MC", 45}, /* EUR */
    {"MD", 85}, /* MDL */
    {"ME", 45}, /* EUR */
    {"MF", 45}, /* EUR */
    {"MG", 86}, /* MGA */
    {"MH", 144}, /* USD */
    {"MK", 87}, /* MKD */
    {"ML", 166}, /* XOF */
    {"MM", 88}, /* MMK */
    {"MN", 89}, /* MNT */
    {"MO", 90}, /* MOP */
    {"MP", 144}, /* USD */
    {"MQ", 45}, /* EUR */
    {"MR", 91}, /* MRU */
    {"MS", 163}, /* XCD */
    {"MT", 45}, /* EUR */
    {"MU", 92}, /* MUR */
    {"MV", 93}, /* MVR */
    {"MW", 94}, /* MWK */
    {"MX", 95}, /* MXN */
    {"MX", 96}, /* MXV */
    {"MY", 97}, /* MYR */
    {"MZ", 98}, /* MZN */
    {"NA", 99}, /* NAD */
    {"NA", 175}, /* ZAR */
    {"NC", 168}, /* XPF */
    {"NE", 166}, /* XOF */
    {"NF", 6}, /* AUD */
    {"NG", 100}, /* NGN */
    {"NI", 101}, /* NIO */
    {"NL", 45}, /* EUR */
    {"NO", 102}, /* NOK */
    {"NP", 103}, /* NPR */
    {"NR", 6}, /* AUD */
    {"NU", 104}, /* NZD */
    {"NZ", 104}, /* NZD */
    {"OM", 105}, /* OMR */
    {"PA", 106}, /* PAB */
    {"PA", 144}, /* USD */
    {"PE", 107}, /* PEN */
    {"PF", 168}, /* XPF */
    {"PG", 108}, /* PGK */
    {"PH", 109}, /* PHP */
    {"PK", 110}, /* PKR */
    {"PL", 111}, /* PLN */
    {"PM", 45}, /* EUR */
    {"PN", 104}, /* NZD */
    {"PR", 144}, /* USD */
    {"PT", 45}, /* EUR */
    {"PW", 144}, /* USD */
    {"PY", 112}, /* PYG */
    {"QA", 113}, /* QAR */
    {"RE", 45}, /* EUR */
    {"RO", 114}, /* RON */
    {"RS", 115}, /* RSD */
    {"RU", 116}, /* RUB */
    {"RW", 117}, /* RWF */
    {"SA", 118}, /* SAR */
    {"SB", 119}, /* SBD */
    {"SC", 120}, /* SCR */
    {"SD", 121}, /* SDG */
    {"SE", 122}, /* SEK */
    {"SG", 123}, /* SGD */
    {"SH", 124}, /* SHP */
    {"SI", 45}, /* EUR */
    {"SJ", 102}, /* NOK */
    {"SK", 45}, /* EUR */
    {"SL", 125}, /* SLE */
    {"SM", 45}, /* EUR */
    {"SN", 166}, /* XOF */
    {"SO", 126}, /* SOS */
    {"SR", 127}, /* SRD */
    {"SS", 128}, /* SSP */
    {"ST", 129}, /* STN */
    {"SV", 130}, /* SVC */
    {"SV", 144}, /* USD */
    {"SX", 164}, /* XCG */
    {"SY", 131}, /* SYP */
    {"SZ", 132}, /* SZL */
    {"TC", 144}, /* USD */
    {"TD", 156}, /* XAF */
    {"TF", 45}, /* EUR */
    {"TG", 166}, /* XOF */
    {"TH", 133}, /* THB */
    {"TJ", 134}, /* TJS */
    {"TK", 104}, /* NZD */
    {"TL", 144}, /* USD */
    {"TM", 135}, /* TMT */
    {"TN", 136}, /* TND */
    {"TO", 137}, /* TOP */
    {"TR", 138}, /* TRY */
    {"TT", 139}, /* TTD */
    {"TV", 6}, /* AUD */
    {"TW", 140}, /* TWD */
    {"TZ", 141}, /* TZS */
    {"UA", 142}, /* UAH */
    {"UG", 143}, /* UGX */
    {"UM", 144}, /* USD */
    {"US", 144}, /* USD */
    {"US", 145}, /* USN */
    {"UY", 146}, /* UYI */
    {"UY", 147}, /* UYU */
    {"UY", 148}, /* UYW */
    {"UZ", 149}, /* UZS */
    {"VA", 45}, /* EUR */
    {"VC", 163}, /* XCD */
    {"VE", 150}, /* VED */
    {"VE", 151}, /* VES */
    {"VG", 144}, /* USD */
    {"VI", 144}, /* USD */
    {"VN", 152}, /* VND */
    {"VU", 153}, /* VUV */
    {"WF", 168}, /* XPF */
    {"WS", 154}, /* WST */
    {"YE", 174}, /* YER */
    {"YT", 45}, /* EUR */
    {"ZA", 175}, /* ZAR */
    {"ZM", 176}, /* ZMW */
    {"ZW", 177}, /* ZWG */
};

const cb_au_member_t cb_au_tbl[CB_AU_COUNT] = {
    {"AO", CB_AU_SOUTHERN, CB_MU_NONE, "Angola"},
    {"BF", CB_AU_WEST, CB_MU_WAEMU, "Burkina Faso"},
    {"BI", CB_AU_CENTRAL, CB_MU_NONE, "Burundi"},
    {"BJ", CB_AU_WEST, CB_MU_WAEMU, "Benin"},
    {"BW", CB_AU_SOUTHERN, CB_MU_NONE, "Botswana"},
    {"CD", CB_AU_CENTRAL, CB_MU_NONE, "Democratic Republic of the Congo"},
    {"CF", CB_AU_CENTRAL, CB_MU_CEMAC, "Central African Republic"},
    {"CG", CB_AU_CENTRAL, CB_MU_CEMAC, "Congo"},
    {"CI", CB_AU_WEST, CB_MU_WAEMU, "Cote d'Ivoire"},
    {"CM", CB_AU_CENTRAL, CB_MU_CEMAC, "Cameroon"},
    {"CV", CB_AU_WEST, CB_MU_NONE, "Cabo Verde"},
    {"DJ", CB_AU_EAST, CB_MU_NONE, "Djibouti"},
    {"DZ", CB_AU_NORTH, CB_MU_NONE, "Algeria"},
    {"EG", CB_AU_NORTH, CB_MU_NONE, "Egypt"},
    {"EH", CB_AU_NORTH, CB_MU_NONE, "Sahrawi Arab Democratic Republic"},
    {"ER", CB_AU_EAST, CB_MU_NONE, "Eritrea"},
    {"ET", CB_AU_EAST, CB_MU_NONE, "Ethiopia"},
    {"GA", CB_AU_CENTRAL, CB_MU_CEMAC, "Gabon"},
    {"GH", CB_AU_WEST, CB_MU_NONE, "Ghana"},
    {"GM", CB_AU_WEST, CB_MU_NONE, "Gambia"},
    {"GN", CB_AU_WEST, CB_MU_NONE, "Guinea"},
    {"GQ", CB_AU_CENTRAL, CB_MU_CEMAC, "Equatorial Guinea"},
    {"GW", CB_AU_WEST, CB_MU_WAEMU, "Guinea-Bissau"},
    {"KE", CB_AU_EAST, CB_MU_NONE, "Kenya"},
    {"KM", CB_AU_EAST, CB_MU_NONE, "Comoros"},
    {"LR", CB_AU_WEST, CB_MU_NONE, "Liberia"},
    {"LS", CB_AU_SOUTHERN, CB_MU_CMA, "Lesotho"},
    {"LY", CB_AU_NORTH, CB_MU_NONE, "Libya"},
    {"MA", CB_AU_NORTH, CB_MU_NONE, "Morocco"},
    {"MG", CB_AU_EAST, CB_MU_NONE, "Madagascar"},
    {"ML", CB_AU_WEST, CB_MU_WAEMU, "Mali"},
    {"MR", CB_AU_NORTH, CB_MU_NONE, "Mauritania"},
    {"MU", CB_AU_EAST, CB_MU_NONE, "Mauritius"},
    {"MW", CB_AU_SOUTHERN, CB_MU_NONE, "Malawi"},
    {"MZ", CB_AU_SOUTHERN, CB_MU_NONE, "Mozambique"},
    {"NA", CB_AU_SOUTHERN, CB_MU_CMA, "Namibia"},
    {"NE", CB_AU_WEST, CB_MU_WAEMU, "Niger"},
    {"NG", CB_AU_WEST, CB_MU_NONE, "Nigeria"},
    {"RW", CB_AU_EAST, CB_MU_NONE, "Rwanda"},
    {"SC", CB_AU_EAST, CB_MU_NONE, "Seychelles"},
    {"SD", CB_AU_EAST, CB_MU_NONE, "Sudan"},
    {"SL", CB_AU_WEST, CB_MU_NONE, "Sierra Leone"},
    {"SN", CB_AU_WEST, CB_MU_WAEMU, "Senegal"},
    {"SO", CB_AU_EAST, CB_MU_NONE, "Somalia"},
    {"SS", CB_AU_EAST, CB_MU_NONE, "South Sudan"},
    {"ST", CB_AU_CENTRAL, CB_MU_NONE, "Sao Tome and Principe"},
    {"SZ", CB_AU_SOUTHERN, CB_MU_CMA, "Eswatini"},
    {"TD", CB_AU_CENTRAL, CB_MU_CEMAC, "Chad"},
    {"TG", CB_AU_WEST, CB_MU_WAEMU, "Togo"},
    {"TN", CB_AU_NORTH, CB_MU_NONE, "Tunisia"},
    {"TZ", CB_AU_EAST, CB_MU_NONE, "Tanzania"},
    {"UG", CB_AU_EAST, CB_MU_NONE, "Uganda"},
    {"ZA", CB_AU_SOUTHERN, CB_MU_CMA, "South Africa"},
    {"ZM", CB_AU_SOUTHERN, CB_MU_NONE, "Zambia"},
    {"ZW", CB_AU_SOUTHERN, CB_MU_NONE, "Zimbabwe"},
};
