/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/* cb_ccy.h — ISO 4217 currencies, ISO 3166-1 countries and the African Union
 * member list, with lookup by alpha code, numeric code and country.
 *
 * The tables live in cb_ccy_tbl.c, GENERATED by gen_cb_tables.py from the
 * ISO 4217 "List One" published by SIX Financial Information (the ISO 4217
 * maintenance agency; the copy used is dated in cb_iso4217_published) and
 * the ISO 3166-1 data of Debian iso-codes. Every currency, numeric code,
 * minor unit and name comes from those files; nothing is typed by hand
 * except the AU member list, its five AU regions and monetary-union tags.
 *
 * The Vino Floating Voucher (VFV) is NOT an ISO 4217 currency and is not in
 * these tables; neither are the Vino rail numerics 846, 810, 888 (846 and
 * 888 are unassigned, 810 is the withdrawn RUR code). cb_ccy_by_alpha("VFV")
 * and cb_ccy_by_num(810) return NULL on purpose.
 *
 * HONEST LIMITS. ISO 4217 changes several times a year; the table is only as
 * current as the list-one.xml it was generated from (see data/PROVENANCE.txt
 * and regenerate when SIX publishes an amendment). AU membership and its
 * regions were written from general knowledge as of cb_au_asof; suspension
 * of a member from AU activities is a political status this table does not
 * record, so an operator must check the current AU position. A code being in
 * ISO 4217 says nothing about convertibility, capital controls or whether
 * any settlement system will accept it.
 */
#ifndef ZXV_CB_CCY_H
#define ZXV_CB_CCY_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define CB_CCY_COUNT      178u
#define CB_COUNTRY_COUNT  249u
#define CB_CTRY_CCY_COUNT 262u
#define CB_AU_COUNT       55u

#define CB_MINOR_NA 255u /* ISO 4217 minor unit "N.A." */

#define CB_CCYF_FUND   0x01u /* IsFund="true" in list one (e.g. CLF, USN) */
#define CB_CCYF_NA     0x02u /* minor unit N.A. (metals, bond units, XDR, XTS, XXX) */
#define CB_CCYF_NOCTRY 0x04u /* listed for no ISO 3166 country (XDR, XUA, XSU...) */

typedef struct {
    char alpha[4];
    uint16_t num;
    uint8_t minor;
    uint8_t flags;
    const char *name;
} cb_ccy_t;

typedef struct {
    char a2[3];
    char a3[4];
    uint16_t num;
    const char *name;
} cb_country_t;

typedef struct {
    char a2[3];
    uint16_t ccy; /* index into cb_ccy_tbl */
} cb_ctry_ccy_t;

typedef enum {
    CB_AU_NORTH = 1,
    CB_AU_WEST = 2,
    CB_AU_CENTRAL = 3,
    CB_AU_EAST = 4,
    CB_AU_SOUTHERN = 5
} cb_au_region;

typedef enum {
    CB_MU_NONE = 0,
    CB_MU_WAEMU = 1, /* West African Economic and Monetary Union, XOF, BCEAO */
    CB_MU_CEMAC = 2, /* Central African Economic and Monetary Community, XAF, BEAC */
    CB_MU_CMA = 3    /* Common Monetary Area (ZAR with LSL, NAD, SZL) */
} cb_monetary_union;

typedef struct {
    char a2[3];
    uint8_t region; /* cb_au_region */
    uint8_t mu;     /* cb_monetary_union */
    const char *name;
} cb_au_member_t;

extern const char cb_iso4217_published[];
extern const char cb_au_asof[];
extern const cb_ccy_t cb_ccy_tbl[CB_CCY_COUNT];             /* sorted by alpha */
extern const uint16_t cb_ccy_by_num_idx[CB_CCY_COUNT];      /* indices sorted by numeric */
extern const cb_country_t cb_country_tbl[CB_COUNTRY_COUNT]; /* sorted by a2 */
extern const cb_ctry_ccy_t cb_ctry_ccy_tbl[CB_CTRY_CCY_COUNT];
extern const cb_au_member_t cb_au_tbl[CB_AU_COUNT]; /* sorted by a2 */

const cb_ccy_t *cb_ccy_by_alpha(const char *alpha);
const cb_ccy_t *cb_ccy_by_num(uint16_t num);
/* Usable for a payment amount: in the table, minor unit defined, not XTS/XXX. */
bool cb_ccy_payable(const cb_ccy_t *c);

const cb_country_t *cb_country_by_a2(const char *a2);
const cb_country_t *cb_country_by_a3(const char *a3);
const cb_country_t *cb_country_by_num(uint16_t num);

/* Currencies list one gives for a country (ISO 3166 alpha-2). Writes up to
 * max pointers into out and returns the total number found. */
size_t cb_ccy_for_country(const char *a2, const cb_ccy_t **out, size_t max);
/* True if list one gives ccy for country a2. */
bool cb_ccy_used_in(const char *a2, const char *alpha);

const cb_au_member_t *cb_au_by_a2(const char *a2);
bool cb_is_au_member(const char *a2);

#endif /* ZXV_CB_CCY_H */
