#!/usr/bin/env python3
# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate kernel/src/cbank/test_cb_rate_vectors.h: Ed25519-signed FX rate
records for the cbank tests (the kernel has a verifier but no signer).

Keys are derived from fixed TEST seeds and are worthless outside the tests.
Rates are round illustrative numbers, NOT market data.

Usage: python3 -I gen_cb_test_vectors.py > test_cb_rate_vectors.h
Requires the Python 'cryptography' package.
"""
import struct
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization

NOW = 1791367200  # 2026-10-07T10:00:00Z, a Wednesday
PUB = NOW - 600
VALID = NOW + 86400
UNIT = "USD"

# (ccy, mant, scale): 1 major ccy = mant / 10^scale USD
RATES = [
    ("XOF", 17, 4), ("XAF", 17, 4), ("NGN", 65, 5), ("KES", 77, 4), ("GHS", 65, 3),
    ("ZAR", 55, 3), ("EGP", 2, 2), ("TND", 33, 2), ("ETB", 7, 3), ("MAD", 1, 1),
]


def canon(ccy, unit, mant, scale, pub, valid, seq, src):
    return (b"ZXV-CBRATE-1" + ccy.encode() + unit.encode() + struct.pack(">Q", mant) +
            bytes([scale]) + struct.pack(">QQI", pub, valid, seq) + bytes([src]))


def key(seed_byte):
    return Ed25519PrivateKey.from_private_bytes(bytes([seed_byte]) * 32)


def raw_pub(k):
    return k.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)


def carr(b):
    return "{" + ", ".join("0x%02x" % x for x in b) + "}"


def rec(k, ccy, mant, scale, pub, valid, seq, src):
    sig = k.sign(canon(ccy, UNIT, mant, scale, pub, valid, seq, src))
    return '    {"%s", "%s", %du, %du, %du, %du, %du, %du, %s},' % (
        ccy, UNIT, mant, scale, pub, valid, seq, src, carr(sig))


def main():
    k1, k2 = key(0x11), key(0x22)
    out = []
    w = out.append
    w("/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */")
    w("/* SPDX-License-Identifier: Apache-2.0 */")
    w("/* test_cb_rate_vectors.h - GENERATED by gen_cb_test_vectors.py. TEST keys and")
    w(" * illustrative rates only (not market data). */")
    w("#ifndef ZXV_TEST_CB_RATE_VECTORS_H")
    w("#define ZXV_TEST_CB_RATE_VECTORS_H")
    w("#include \"cb_config.h\"")
    w("#define TV_NOW %du" % NOW)
    w("static const uint8_t tv_pk_src1[32] = %s;" % carr(raw_pub(k1)))
    w("static const uint8_t tv_pk_src2[32] = %s;" % carr(raw_pub(k2)))
    w("static const cb_rate_rec tv_rates[] = {")
    for c, m, s in RATES:
        w(rec(k1, c, m, s, PUB, VALID, 1, 1))
    w("};")
    w("#define TV_N_RATES %d" % len(RATES))
    w("/* seq 2 update for KES from source 1 (1 KES = 0.0080 USD) */")
    w("static const cb_rate_rec tv_kes_seq2 = %s" % rec(k1, "KES", 80, 4, PUB + 60, VALID, 2, 1)[4:-1] + ";")
    w("/* XOF record signed by source 2's key but claiming source 1 */")
    w("static const cb_rate_rec tv_xof_wrongkey = %s" % rec(k2, "XOF", 17, 4, PUB, VALID, 3, 1)[4:-1] + ";")
    w("/* XOF record from source 2 published two hours before TV_NOW (stale) */")
    w("static const cb_rate_rec tv_xof_stale = %s" % rec(k2, "XOF", 17, 4, NOW - 7200, VALID, 1, 2)[4:-1] + ";")
    w("#endif")
    print("\n".join(out))


if __name__ == "__main__":
    main()
