# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Cross-implementation vectors for test_prov_chain.c.

An independent Python implementation of the provider receipt body and
digest (prov_receipt.c layout), signed with the `cryptography` package's
Ed25519 and secp256k1 ECDSA, so the C adapters are checked against code
they share nothing with. Bech32 and base58 are the BIP-173 / Bitcoin
reference algorithms; the script first reproduces the BIP-173 P2WPKH
vector (bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4) before trusting them.

ECDSA signatures from `cryptography` are randomised, so re-running gives
different (equally valid) secp256k1 vectors; Ed25519 output is
deterministic. Usage: python3 -I gen_prov_chain_vectors.py > test_prov_chain_vectors.h
"""
import hashlib
import struct
import sys

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, utils

N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141


def receipt_body():
    b = struct.pack("<I", 1)
    for v in range(1, 8):  # job, provider, user, desc, fee schedule, request, response
        b += bytes([v]) * 32
    b += bytes([5, 0, 0, 1])  # rclass INFERENCE, unit TOKEN, SLA met, flags NO_TRAIN
    b += struct.pack("<H", 0)
    b += b"VFV".ljust(12, b"\0")
    for v in (700, 10, 7000, 0, 113, 6887, 3000, 10000):
        b += struct.pack("<Q", v)
    b += struct.pack("<I", 120) + struct.pack("<Q", 100) + struct.pack("<Q", 160)
    assert len(b) == 330
    return b


def receipt_digest():
    dom = b"zxv-prov-receipt-v1"
    return hashlib.sha3_256(struct.pack("<I", len(dom)) + dom + receipt_body()).digest()


CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"


def polymod(values):
    gen = [0x3B6A57B2, 0x26508E6D, 0x1EA119FA, 0x3D4233DD, 0x2A1462B3]
    chk = 1
    for v in values:
        b = chk >> 25
        chk = (chk & 0x1FFFFFF) << 5 ^ v
        for i in range(5):
            chk ^= gen[i] if ((b >> i) & 1) else 0
    return chk


def bech32_encode(hrp, data):
    exp = [ord(x) >> 5 for x in hrp] + [0] + [ord(x) & 31 for x in hrp]
    pm = polymod(exp + data + [0] * 6) ^ 1
    return hrp + "1" + "".join(CHARSET[d] for d in data + [(pm >> 5 * (5 - i)) & 31 for i in range(6)])


def convertbits(data, frm, to):
    acc = bits = 0
    out = []
    for v in data:
        acc = (acc << frm) | v
        bits += frm
        while bits >= to:
            bits -= to
            out.append((acc >> bits) & ((1 << to) - 1))
    if bits:
        out.append((acc << (to - bits)) & ((1 << to) - 1))
    return out


def b58(data):
    alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
    n = int.from_bytes(data, "big")
    s = ""
    while n:
        n, r = divmod(n, 58)
        s = alphabet[r] + s
    return "1" * (len(data) - len(data.lstrip(b"\0"))) + s


def hash160(b):
    return hashlib.new("ripemd160", hashlib.sha256(b).digest()).digest()


def compressed(pub):
    return pub.public_bytes(serialization.Encoding.X962, serialization.PublicFormat.CompressedPoint)


def sign_prehashed(priv, digest):
    der = priv.sign(digest, ec.ECDSA(utils.Prehashed(hashes.SHA256())))
    r, s = utils.decode_dss_signature(der)
    if s > N // 2:
        s = N - s
    return r.to_bytes(32, "big") + s.to_bytes(32, "big")


def c_bytes(name, b):
    return "static const uint8_t %s[%d] = {%s};\n" % (name, len(b), ", ".join("0x%02x" % x for x in b))


def main():
    # Self-check of bech32 + HASH160 against BIP-173 (G = 1 * generator).
    g = ec.derive_private_key(1, ec.SECP256K1()).public_key()
    kh = hash160(compressed(g))
    assert kh.hex() == "751e76e8199196d454941c45d1b3a323f1433bd6"
    assert bech32_encode("bc", [0] + convertbits(kh, 8, 5)) == "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4"

    d = receipt_digest()
    text = b"zxv-prov-receipt:" + d.hex().encode()
    out = sys.stdout
    out.write("/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC\n")
    out.write(" * SPDX-License-Identifier: Apache-2.0 */\n")
    out.write("/* Generated by gen_prov_chain_vectors.py (independent Python implementation). */\n")
    out.write(c_bytes("V_RECEIPT_DIGEST", d))
    out.write('static const char V_COSMOS_G_ADDR[] = "%s";\n' % bech32_encode("cosmos", convertbits(kh, 8, 5)))

    ek = ed25519.Ed25519PrivateKey.from_private_bytes(bytes(range(32)))
    epub = ek.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    out.write(c_bytes("V_ED_PUB", epub))
    out.write(c_bytes("V_ED_SIG", ek.sign(text)))
    out.write('static const char V_ED_ADDR[] = "%s";\n' % b58(epub))

    ck = ec.derive_private_key(0x1D6D6D9E5C7B1A2F3E4D5C6B7A8998ABBCCDDEEFF00112233445566778899AA, ec.SECP256K1())
    out.write(c_bytes("V_COSMOS_PUB", compressed(ck.public_key())))
    out.write(c_bytes("V_COSMOS_SIG", sign_prehashed(ck, hashlib.sha256(text).digest())))

    bk = ec.derive_private_key(0x0BADC0FFEE0DDF00D1234567890ABCDEF1234567890ABCDEF1234567890ABCD, ec.SECP256K1())
    magic = b"\x18Bitcoin Signed Message:\n"
    mh = hashlib.sha256(hashlib.sha256(magic + bytes([len(text)]) + text).digest()).digest()
    out.write(c_bytes("V_BTC_HASH", mh))
    out.write(c_bytes("V_BTC_KEYHASH", hash160(compressed(bk.public_key()))))
    out.write(c_bytes("V_BTC_RS", sign_prehashed(bk, mh)))


if __name__ == "__main__":
    main()
