/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
 * SPDX-License-Identifier: Apache-2.0 */
/* zt_bench.c -- hosted benchmark driver for the integer tensor engine.
 *
 * Loads a GGUF file with kernel/src/tensor (zt_gguf, zt_tok, zt_model), encodes
 * a prompt, runs the prompt through the model (prefill), then generates N
 * tokens greedily (argmax, lowest id on ties) and reports:
 *
 *   zt.n_prompt=<tokens>  zt.prefill_s=<seconds>  zt.prefill_tps=<tokens/s>
 *   zt.n_gen=<tokens>     zt.gen_s=<seconds>      zt.gen_tps=<tokens/s>
 *   zt.ids=<comma-separated generated token ids>
 *   zt.stop=eos|max
 *   zt.logits_fnv=<FNV-1a 64 of every logit vector computed, in order>
 *
 * and, with --text FILE, writes the decoded generated bytes to FILE.
 * It is a measuring tool for bench/run_tensor_bench.py; it claims nothing by
 * itself. Hosted only (libc, malloc, clock_gettime).
 *
 * Usage: zt_bench MODEL.gguf [--prompt TEXT] [-n N] [--ctx C] [--batch B]
 *                 [--kv q16|q8] [--text FILE] [--kern NAME] [--threads T]
 *                 [--special]
 * --special parses special-token text in the prompt (a chat template such as
 * "<|im_start|>user\n...<|im_end|>\n<|im_start|>assistant\n").
 * zt.logits_fnv lets two machines check they computed the same bits, not
 * only the same argmax.
 * --kern picks the matrix kernels (zt_simd.h: c, avx2, avx512, neon; default
 * the fastest this CPU runs), --threads the thread count (default 1). Every
 * choice gives the same token ids; only the speed differs. It prints
 * zt.kern=<name> zt.threads=<T>.
 * Exit: 0 ok, 2 usage, 3 cannot read file, 4 model or tokenizer not loadable,
 *       5 run failed. */
#define _POSIX_C_SOURCE 200809L
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "zt_gguf.h"
#include "zt_model.h"
#include "zt_simd.h"
#include "zt_tok.h"

static double now_s(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double) ts.tv_sec + (double) ts.tv_nsec * 1e-9;
}

static uint8_t *read_file(const char *path, uint64_t *size)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return NULL;
    }
    long n = ftell(f);
    if (n <= 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return NULL;
    }
    uint8_t *buf = malloc((size_t) n);
    if (buf && fread(buf, 1, (size_t) n, f) != (size_t) n) {
        free(buf);
        buf = NULL;
    }
    fclose(f);
    *size = (uint64_t) n;
    return buf;
}

static void *alloc64(uint64_t bytes)
{
    void *p = NULL;
    if (posix_memalign(&p, 64, bytes ? (size_t) bytes : 64) != 0) return NULL;
    return p;
}

static uint64_t fnv_logits(uint64_t h, const zt_fx *v, uint32_t n)
{
    for (uint32_t i = 0; i < n; i++) {
        uint32_t x = (uint32_t) v[i];
        for (int b = 0; b < 4; b++) h = (h ^ (uint8_t) (x >> (8 * b))) * 0x100000001b3ull;
    }
    return h;
}

int main(int argc, char **argv)
{
    bool special = false;
    const char *path = NULL, *prompt = "The capital of France is", *text_out = NULL;
    const char *kern_name = NULL;
    uint32_t n_gen = 32, n_ctx = 0, n_batch = 32, kv = ZT_KV_Q16, n_threads = 1;
    for (int i = 1; i < argc; i++) {
        const char *a = argv[i];
        const char *v = i + 1 < argc ? argv[i + 1] : NULL;
        if (!strcmp(a, "--prompt") && v)
            prompt = argv[++i];
        else if (!strcmp(a, "-n") && v)
            n_gen = (uint32_t) strtoul(argv[++i], NULL, 10);
        else if (!strcmp(a, "--ctx") && v)
            n_ctx = (uint32_t) strtoul(argv[++i], NULL, 10);
        else if (!strcmp(a, "--batch") && v)
            n_batch = (uint32_t) strtoul(argv[++i], NULL, 10);
        else if (!strcmp(a, "--kv") && v)
            kv = !strcmp(argv[++i], "q8") ? ZT_KV_Q8 : ZT_KV_Q16;
        else if (!strcmp(a, "--text") && v)
            text_out = argv[++i];
        else if (!strcmp(a, "--kern") && v)
            kern_name = argv[++i];
        else if (!strcmp(a, "--threads") && v)
            n_threads = (uint32_t) strtoul(argv[++i], NULL, 10);
        else if (!strcmp(a, "--special"))
            special = true;
        else if (a[0] != '-' && !path)
            path = a;
        else {
            fprintf(stderr,
                    "usage: %s MODEL.gguf [--prompt TEXT] [-n N] [--ctx C] [--batch B] "
                    "[--kv q16|q8] [--text FILE] [--kern NAME] [--threads T] [--special]\n",
                    argv[0]);
            return 2;
        }
    }
    if (!path || n_gen == 0 || n_batch == 0) {
        fprintf(stderr, "zt_bench: a model path and N >= 1 are required\n");
        return 2;
    }

    uint64_t size = 0;
    uint8_t *file = read_file(path, &size);
    if (!file) {
        fprintf(stderr, "zt_bench: cannot read %s\n", path);
        return 3;
    }
    zt_gguf_t g;
    int32_t r = zt_gguf_open(&g, file, size);
    if (r != 0) {
        fprintf(stderr, "zt_bench: not a readable GGUF file (error %d)\n", r);
        return 4;
    }

    zt_model_err_t err;
    memset(&err, 0, sizeof err);
    uint64_t mbytes = zt_model_arena_bytes(&g);
    if (!mbytes) {
        zt_model_cfg_t cfg;
        zt_model_config(&g, &cfg, &err);
        fprintf(stderr, "zt_bench: the engine cannot load this model: %s%s%s (code %d)\n",
                err.what ? err.what : "unknown", err.name[0] ? ": " : "", err.name, err.code);
        return 4;
    }
    void *marena = alloc64(mbytes);
    zt_model_t m;
    if (!marena || zt_model_load(&m, &g, marena, mbytes, &err) != 0) {
        fprintf(stderr, "zt_bench: model load failed: %s %s\n", err.what ? err.what : "", err.name);
        return 4;
    }
    const zt_kern_t *kb = kern_name ? zt_simd_find(kern_name) : zt_simd_best();
    if (!kb) {
        fprintf(stderr, "zt_bench: kernel set '%s' is not available on this CPU\n", kern_name);
        return 2;
    }
    zt_pool_t *pool = n_threads > 1 ? zt_pool_new(n_threads) : NULL;
    zt_kern_t kern;
    zt_kern_threaded(&kern, kb, pool);
    m.kern = &kern;
    uint64_t tbytes = zt_tok_arena_bytes(&g);
    void *tarena = tbytes ? alloc64(tbytes) : NULL;
    zt_tok_t tok;
    if (!tarena || zt_tok_load(&tok, &g, tarena, tbytes) != 0) {
        fprintf(stderr, "zt_bench: the file has no tokenizer the engine can load\n");
        return 4;
    }

    /* Prompt -> ids (BOS first when the file asks for it, as llama.cpp does). */
    uint64_t plen = strlen(prompt);
    uint64_t cap = plen + 8;
    int32_t *ids = malloc((size_t) (cap + n_gen) * sizeof(int32_t));
    uint64_t wb = zt_tok_work_bytes(plen);
    void *work = alloc64(wb);
    uint64_t n_ids = 0, got = 0;
    if (!ids || !work) return 5;
    if (tok.add_bos && tok.bos >= 0) ids[n_ids++] = tok.bos;
    if (zt_tok_encode(&tok, (const uint8_t *) prompt, plen, special, ids + n_ids, cap - n_ids, &got,
                      work, wb) != 0) {
        fprintf(stderr, "zt_bench: prompt encoding failed\n");
        return 5;
    }
    n_ids += got;
    if (n_ids == 0) return 5;

    if (n_ctx == 0) n_ctx = (uint32_t) n_ids + n_gen + 1;
    uint64_t sbytes = zt_model_state_bytes(&m, n_ctx, n_batch, kv);
    void *smem = alloc64(sbytes);
    zt_model_state_t st;
    if (!smem || zt_model_state_init(&st, &m, n_ctx, n_batch, kv, smem, sbytes) != 0) {
        fprintf(stderr, "zt_bench: cannot set up a %u-token context\n", n_ctx);
        return 5;
    }
    uint32_t nv = m.cfg.n_vocab;
    zt_fx *logits = malloc((size_t) nv * sizeof(zt_fx));
    if (!logits) return 5;

    double t0 = now_s();
    r = zt_model_eval(&m, &st, ids, (uint32_t) n_ids, logits, 0);
    double t1 = now_s();
    if (r != 0) {
        fprintf(stderr, "zt_bench: prefill failed (%d)\n", r);
        return 5;
    }
    uint64_t lh = fnv_logits(0xcbf29ce484222325ull, logits, nv);
    int32_t *gen = ids + n_ids;
    uint32_t n_out = 0;
    const char *stop = "max";
    for (;;) {
        int32_t id = zt_argmax(logits, nv);
        if (id == tok.eos) {
            stop = "eos";
            break;
        }
        gen[n_out++] = id;
        if (n_out == n_gen) break;
        r = zt_model_decode(&m, &st, id, logits);
        if (r != 0) {
            fprintf(stderr, "zt_bench: decode failed at token %u (%d)\n", n_out, r);
            return 5;
        }
        lh = fnv_logits(lh, logits, nv);
    }
    double t2 = now_s();

    printf("zt.kern=%s\nzt.threads=%u\n", kb->name, pool ? n_threads : 1);
    printf("zt.n_prompt=%llu\n", (unsigned long long) n_ids);
    printf("zt.prefill_s=%.6f\nzt.prefill_tps=%.3f\n", t1 - t0,
           (t1 - t0) > 0 ? (double) n_ids / (t1 - t0) : 0.0);
    printf("zt.n_gen=%u\nzt.gen_s=%.6f\nzt.gen_tps=%.3f\n", n_out, t2 - t1,
           (t2 - t1) > 0 ? (double) n_out / (t2 - t1) : 0.0);
    printf("zt.stop=%s\nzt.ids=", stop);
    for (uint32_t i = 0; i < n_out; i++) printf(i ? ",%d" : "%d", gen[i]);
    printf("\n");
    printf("zt.logits_fnv=%016llx\n", (unsigned long long) lh);

    if (text_out) {
        uint64_t tcap = (uint64_t) n_out * 64 + 16, n_txt = 0;
        uint8_t *txt = malloc((size_t) tcap);
        FILE *f = fopen(text_out, "wb");
        if (!txt || !f || zt_tok_decode(&tok, gen, n_out, txt, tcap, &n_txt) != 0 ||
            fwrite(txt, 1, (size_t) n_txt, f) != n_txt) {
            fprintf(stderr, "zt_bench: could not write the decoded text\n");
            if (f) fclose(f);
            return 5;
        }
        fclose(f);
        free(txt);
    }
    zt_pool_free(pool);
    free(logits);
    free(smem);
    free(work);
    free(ids);
    free(tarena);
    free(marena);
    free(file);
    return 0;
}
