# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# Regenerate pq_matrix_kat_vectors.h for test_pq_matrix.c from
#   - a checkout of NIST's ACVP-Server (vectors used: commit
#     975de31eb83d87039ec88934fdc47d8c312b892d), gen-val/json-files, and
#   - the official HQC KAT file kats/ref/hqc-5/PQCkemKAT_7333.rsp from
#     gitlab.com/pqc-hqc/hqc release v5.0.0 (commit f46e5422).
#   python3 -I gen_pq_matrix_kat.py pq_matrix_kat_vectors.h \
#       <ACVP-Server>/gen-val/json-files <hqc>/kats/ref/hqc-5/PQCkemKAT_7333.rsp
# Large expected outputs are stored as their SHA3-256 digest; all byte
# strings are stored as hex text (lengths in the table are in bytes).
import json, hashlib, sys
D = sys.argv[2].rstrip('/') + '/'
RSP = sys.argv[3]


def L(d):
    return json.load(open(D + d + '/internalProjection.json'))['testGroups']


def grp(d, ps, **kw):
    for g in L(d):
        if g['parameterSet'] == ps and all(g.get(k) == v for k, v in kw.items()):
            # shortest messages first keeps the header small; the fixed-size
            # API cannot express wrong-length signatures, so skip those.
            g['tests'] = sorted([t for t in g['tests']
                                 if not t.get('reason', '').startswith('invalid signature - too')],
                                key=lambda t: len(t.get('message', '')))
            return g
    raise SystemExit('no group %s %s %s' % (d, ps, kw))


def h(x):
    return hashlib.sha3_256(bytes.fromhex(x)).hexdigest()


def carr(name, hx):
    # Hex text, two characters per byte; test_pq_matrix.c decodes it. This
    # keeps the header a third the size of a 0x.. byte array.
    hx = hx.lower()
    rows = ['"%s"' % hx[i:i + 96] for i in range(0, len(hx), 96)] or ['""']
    return 'static const char %s[] =\n    %s;\n' % (name, '\n    '.join(rows))


out = ['/* pq_matrix_kat_vectors.h — generated by gen_pq_matrix_kat.py from NIST',
       ' * ACVP-Server gen-val/json-files (internalProjection.json) and the HQC',
       ' * v5.0.0 PQCkemKAT_7333.rsp. Large expected outputs are stored as their',
       ' * SHA3-256 digest; byte strings are hex text. Do not edit. */',
       '#include <stdint.h>', '']
cases = []


def add(kind, fields, meta):
    i = len(cases)
    s = ''
    for k, v in fields.items():
        s += carr('m%d_%s' % (i, k), v)
    out.append(s)
    cases.append((kind, meta, list(fields.keys()), {k: len(bytes.fromhex(v)) for k, v in fields.items()}))


P = 'ML-KEM-1024'
# keyGen: d, z -> H(ek), H(dk)
for t in grp('ML-KEM-keyGen-FIPS203', P)['tests'][:5]:
    add('PQM_KAT_MLKEM_KEYGEN', {'d': t['d'], 'z': t['z'], 'hek': h(t['ek']), 'hdk': h(t['dk'])}, t['tcId'])
# encapsulation: ek, m -> H(c), k
for t in grp('ML-KEM-encapDecap-FIPS203', P, function='encapsulation')['tests'][:5]:
    add('PQM_KAT_MLKEM_ENCAP', {'ek': t['ek'], 'm': t['m'], 'hc': h(t['c']), 'k': t['k']}, t['tcId'])
# decapsulation (valid and modified ciphertexts): dk, c -> k
for t in grp('ML-KEM-encapDecap-FIPS203', P, function='decapsulation')['tests'][:6]:
    add('PQM_KAT_MLKEM_DECAP', {'dk': t['dk'], 'c': t['c'], 'k': t['k']}, (t['tcId'], 1, t.get('reason', '')))
# input checks: 2 pass + 2 fail each
for fn, kind, key in (('encapsulationKeyCheck', 'PQM_KAT_MLKEM_EKCHECK', 'ek'),
                      ('decapsulationKeyCheck', 'PQM_KAT_MLKEM_DKCHECK', 'dk')):
    g = grp('ML-KEM-encapDecap-FIPS203', P, function=fn)['tests']
    sel = [t for t in g if t['testPassed']][:2] + [t for t in g if not t['testPassed']][:2]
    for t in sel:
        add(kind, {key: t[key]}, (t['tcId'], int(t['testPassed']), t.get('reason', '')))

P = 'ML-DSA-87'
for t in grp('ML-DSA-keyGen-FIPS204', P)['tests'][:5]:
    add('PQM_KAT_MLDSA_KEYGEN', {'seed': t['seed'], 'hpk': h(t['pk']), 'hsk': h(t['sk'])}, t['tcId'])
for t in grp('ML-DSA-sigGen-FIPS204', P, deterministic=True, signatureInterface='external', preHash='pure')['tests'][:3]:
    add('PQM_KAT_MLDSA_SIGN', {'sk': t['sk'], 'msg': t['message'], 'ctx': t['context'], 'rnd': '',
                               'hsig': h(t['signature'])}, t['tcId'])
for t in grp('ML-DSA-sigGen-FIPS204', P, deterministic=False, signatureInterface='external', preHash='pure')['tests'][:2]:
    add('PQM_KAT_MLDSA_SIGN', {'sk': t['sk'], 'msg': t['message'], 'ctx': t['context'], 'rnd': t['rnd'],
                               'hsig': h(t['signature'])}, t['tcId'])
g = grp('ML-DSA-sigVer-FIPS204', P, signatureInterface='external', preHash='pure')['tests']
sel = [t for t in g if t['testPassed']][:2] + [t for t in g if not t['testPassed']][:3]
for t in sel:
    add('PQM_KAT_MLDSA_VERIFY', {'pk': t['pk'], 'msg': t['message'], 'ctx': t['context'], 'sig': t['signature']},
        (t['tcId'], int(t['testPassed']), t['reason']))

P = 'SLH-DSA-SHAKE-256s'
for t in grp('SLH-DSA-keyGen-FIPS205', P)['tests'][:3]:
    add('PQM_KAT_SLH_KEYGEN', {'seed': t['skSeed'] + t['skPrf'] + t['pkSeed'], 'pk': t['pk'], 'sk': t['sk']}, t['tcId'])
t = grp('SLH-DSA-sigGen-FIPS205', P, deterministic=True, signatureInterface='external', preHash='pure')['tests'][0]
add('PQM_KAT_SLH_SIGN', {'sk': t['sk'], 'msg': t['message'], 'ctx': t['context'], 'rnd': '',
                         'hsig': h(t['signature'])}, t['tcId'])
t = grp('SLH-DSA-sigGen-FIPS205', P, deterministic=False, signatureInterface='external', preHash='pure')['tests'][0]
add('PQM_KAT_SLH_SIGN', {'sk': t['sk'], 'msg': t['message'], 'ctx': t['context'], 'rnd': t['additionalRandomness'],
                         'hsig': h(t['signature'])}, t['tcId'])
g = grp('SLH-DSA-sigVer-FIPS205', P, signatureInterface='external', preHash='pure')['tests']
sel = [t for t in g if t['testPassed']][:1] + [t for t in g if not t['testPassed']][:1]
for t in sel:
    add('PQM_KAT_SLH_VERIFY', {'pk': t['pk'], 'msg': t['message'], 'ctx': t['context'], 'sig': t['signature']},
        (t['tcId'], int(t['testPassed']), t['reason']))

# HQC-5: the official KAT file. Each record's 48-byte seed initialises the
# reference SHAKE-256 PRNG; the test re-derives seed_kem, m, salt from it.
recs, cur = [], {}
for line in open(RSP):
    line = line.strip()
    if ' = ' in line:
        k, v = line.split(' = ', 1)
        cur[k] = v
        if k == 'ss':
            recs.append(cur)
            cur = {}
for r in recs[:10]:
    add('PQM_KAT_HQC', {'seed': r['seed'], 'hpk': h(r['pk']), 'hsk': h(r['sk']), 'hct': h(r['ct']),
                        'ss': r['ss']}, int(r['count']))

out.append('typedef enum {\n    PQM_KAT_MLKEM_KEYGEN, PQM_KAT_MLKEM_ENCAP, PQM_KAT_MLKEM_DECAP,\n'
           '    PQM_KAT_MLKEM_EKCHECK, PQM_KAT_MLKEM_DKCHECK, PQM_KAT_MLDSA_KEYGEN,\n'
           '    PQM_KAT_MLDSA_SIGN, PQM_KAT_MLDSA_VERIFY, PQM_KAT_SLH_KEYGEN, PQM_KAT_SLH_SIGN,\n'
           '    PQM_KAT_SLH_VERIFY, PQM_KAT_HQC\n} pqm_kat_kind_t;')
out.append('typedef struct { pqm_kat_kind_t kind; uint32_t tc; int32_t expect; const char *why;\n'
           '    const char *a, *b, *c, *d, *e; uint32_t na, nb, nc, nd, ne; } pqm_kat_t;')
out.append('static const pqm_kat_t PQM_KATS[] = {')
for i, (kind, meta, keys, lens) in enumerate(cases):
    tc, exp, why = (meta, 1, '') if not isinstance(meta, tuple) else meta
    names = ['m%d_%s' % (i, k) for k in keys] + ['0'] * (5 - len(keys))
    ls = [str(lens[k]) for k in keys] + ['0'] * (5 - len(keys))
    out.append('    { %s, %d, %d, "%s", %s, %s },' % (kind, tc, exp, why.replace('"', "'"), ', '.join(names), ', '.join(ls)))
out.append('};')
out.append('#define PQM_KAT_COUNT (sizeof(PQM_KATS) / sizeof(PQM_KATS[0]))')
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
print(len(cases))
