#!/usr/bin/env python3
# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate kernel/src/pay/pay_tables.c from the Debian iso-codes package.

Source: /usr/share/iso-codes/json/iso_3166-1.json from the Debian/Ubuntu
package iso-codes (4.16.0 when this file was generated). Only ISO 3166-1
alpha-2 is generated: the platform ISO 4217 table belongs to kernel/src/cbank.

Usage: python3 -I gen_pay_tables.py > pay_tables.c
"""
import json
import sys

ISO = "/usr/share/iso-codes/json/"
c3166 = json.load(open(ISO + "iso_3166-1.json"))["3166-1"]

TAIL = r"""
/* ===== Lookups  ===== */
#include "pay_util.h"

bool pay_iso3166_valid(const char *cc)
{
    if (!cc || pay_strnlen(cc, 3) != 2 || !pay_is_upper(cc[0]) || !pay_is_upper(cc[1]))
        return false;
    for (uint32_t i = 0; i < PAY_ISO3166_COUNT; i++)
        if (pay_iso3166_a2[i][0] == cc[0] && pay_iso3166_a2[i][1] == cc[1]) return true;
    return false;
}
"""

out = sys.stdout
out.write("/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */\n")
out.write("/* SPDX-License-Identifier: Apache-2.0 AND "
          "LicenseRef-Royal-Writ-Sicilian-Crown-1.0 AND LicenseRef-SEL-3.3 */\n")
out.write("/* pay_tables.c — GENERATED by gen_pay_tables.py from Debian iso-codes 4.16.0.\n"
          " * Do not edit by hand. ISO 3166-1 alpha-2 code table. */\n")
out.write('#include "pay_tables.h"\n\n')
a2 = sorted(x["alpha_2"] for x in c3166)
out.write("const char pay_iso3166_a2[PAY_ISO3166_COUNT][3] = {\n")
for i in range(0, len(a2), 12):
    out.write("    " + ", ".join('"%s"' % c for c in a2[i:i + 12]) + ",\n")
out.write("};\n\n")
out.write(TAIL)
sys.stderr.write("PAY_ISO3166_COUNT %d\n" % len(a2))
