/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/* pay_equity.h — equity rails and an integer order book for any platform
 * object, plus the non-voting equity that every minted VFV carries.
 *
 * SECURITIES NOTE. Equity offerings, share trading and order matching fall
 * under securities regulation in most jurisdictions (registration or an
 * exemption for the offering, licensing for the venue and for brokers,
 * market-abuse and disclosure rules). This module is OFF unless the operator
 * enables it, and it can be disabled per jurisdiction and per role. Enabling
 * it is a legal decision, not a technical one.
 *
 * INSTRUMENTS. Any platform object (dataset CID, model, post, group,
 * syndicate, farm, the VFV currency itself, other) identified by a kind and a
 * 32-byte id may be given an equity instrument: a share asset in pay_ledger
 * with a FIXED supply (all issued at creation) or an ISSUABLE supply (issued
 * later by the issuer, up to an optional maximum). Shares live on the EQUITY
 * rail: the issuer account carries the CREDIT claim for shares outstanding,
 * each holder's share count is its EQUITY balance (pay_ledger.h).
 *
 * VOTING VS NON-VOTING (a type-level distinction). An instrument is created
 * with a class, and the handle type differs: pay_eq_voting_t for voting
 * shares, pay_eq_nonvoting_t for non-voting shares. Only a pay_eq_voting_t
 * can be passed to pay_equity_votes; there is no conversion from a
 * non-voting handle to a voting one. The VFV currency equity is always
 * non-voting: pay_equity_create_voting refuses PAY_OBJ_CURRENCY, and the VFV
 * instrument is created only through pay_vfv_equity_init. Voting equity may
 * be assigned in other things, never in the currency itself.
 *
 * THE ORDER BOOK. Deterministic, integer, price-time priority. Limit and
 * market orders; price in quote-asset minor units per share; quantity in
 * whole shares. Incoming orders match against the best resting price, oldest
 * first, and trade at the RESTING order's price. Market orders never rest
 * (unfilled remainder is cancelled). Funds and shares are reserved when an
 * order is placed, so a fill can always settle.
 *   E1 SETTLEMENT is ONE pay_ledger posting per fill touching the DEBIT and
 *      EQUITY rails of both the quote asset and the share asset: buyer money
 *      down, seller money up, seller shares down, buyer shares up. It is
 *      all-or-nothing; there is no partial ledger state.
 *   E2 NO SELF-TRADE: when the best resting order belongs to the incoming
 *      order's owner, the RESTING order is cancelled (cancel-oldest) and
 *      matching continues.
 *   E3 ANTI-MONOPOLY: no holder other than the issuer may hold more than
 *      cap.num/cap.den of the instrument's supply (default 8/21, the
 *      cooperative cap of docs/SWARM_ECONOMY.md section 6). A fill is cut to
 *      the buyer's remaining room; a buyer with no room has its order
 *      cancelled (incoming or resting), so a capped buyer never rests on a
 *      crossed book.
 *   E4 CONSERVATION: shares and money are only moved, never created, by
 *      trading; sum of holder shares == supply outstanding; the ledger
 *      invariants L1-L3 hold after every fill.
 *   E5 AUDIT: every create, issue, order, cancel, self-trade cancel, cap cut
 *      and fill is appended to a SHA3-256 hash-chained audit trail.
 *   No margin, no short selling, no share lending, no interest of any kind.
 *
 * VFV CURRENCY EQUITY (the fractal reserve). Every VFV minted carries the same
 * number of non-voting VFV-equity units, generated by the fractal-reserve
 * shape of kernel/src/swarm (swarm_reserve.h F1-F3) over the Count House
 * tiers of kernel/src/count_house (Scale-0 node, Alliance, Global):
 *   V1 For a mint of m VFV to holder H on reserve path (node, alliance,
 *      global), m equity units are split over the levels d = 0..L-1 (0 = H)
 *      by the Fibonacci level weights F(L-d+1) of swarm_budget.h (5:3:2:1
 *      for four levels), largest remainder, exactly.
 *   V2 Each level records what it received, so a level's summary is exactly
 *      the sum of its parts (F2), and V3 holds.
 *   V3 FULL RESERVE: equity units outstanding == VFV ever minted through
 *      pay_vfv_equity_on_mint == the sum of the level totals (F3). Redeeming
 *      VFV does not cancel the equity already generated.
 *   The units trade on the order book like any non-voting share, for
 *   derivative (market) returns. They carry no vote and no interest.
 *
 * HONEST LIMITS. Securities regulation applies (above). Schema validity is
 * not certification; there is no SWIFT or CIPS connectivity; operating a
 * venue, a bank or a money transmitter needs licences; VFV's store-credit
 * classification is a legal question for counsel. Freestanding: no libc, no
 * allocation, no floating point, no 64-bit division (zt_udiv64).
 */
#ifndef ZXV_PAY_EQUITY_H
#define ZXV_PAY_EQUITY_H

#include <stdint.h>
#include <stdbool.h>
#include "pay_util.h"
#include "pay_ledger.h"
#include "pay_tithe.h"
#include "pay_roles.h"

typedef enum {
    PAY_OBJ_DATASET = 0,
    PAY_OBJ_MODEL,
    PAY_OBJ_POST,
    PAY_OBJ_GROUP,
    PAY_OBJ_SYNDICATE,
    PAY_OBJ_FARM,
    PAY_OBJ_CURRENCY,
    PAY_OBJ_OTHER
} pay_obj_kind_t;

typedef struct {
    pay_obj_kind_t kind;
    uint8_t id[32];
} pay_obj_ref_t;

typedef enum { PAY_EQ_NONVOTING = 0, PAY_EQ_VOTING = 1 } pay_eq_class_t;
typedef enum { PAY_SUPPLY_FIXED = 0, PAY_SUPPLY_ISSUABLE = 1 } pay_supply_t;

/* Distinct handle types: the class is in the type. */
typedef struct {
    uint32_t idx;
} pay_eq_voting_t;
typedef struct {
    uint32_t idx;
} pay_eq_nonvoting_t;

typedef enum { PAY_SIDE_BUY = 0, PAY_SIDE_SELL = 1 } pay_side_t;
typedef enum { PAY_ORD_LIMIT = 0, PAY_ORD_MARKET = 1 } pay_ord_type_t;

#define PAY_EQ_MAX_INST    16u
#define PAY_EQ_MAX_ORDERS  512u
#define PAY_EQ_MAX_HOLDERS 128u
#define PAY_EQ_AUDIT       1024u
#define PAY_EQ_MAX_PART    128u
#define PAY_EQ_MAX_JURIS   8u
#define PAY_EQ_LEVELS      4u

typedef struct {
    bool active;
    pay_obj_ref_t obj;
    pay_eq_class_t cls;
    pay_supply_t supply_mode;
    uint64_t supply;     /* outstanding */
    uint64_t max_supply; /* ISSUABLE: 0 = unlimited */
    uint16_t share_asset;
    uint16_t quote_asset;
    uint32_t issuer_owner;
    uint32_t issuer_acct; /* share asset, ISSUER flag */
    pay_rat_t cap;
    uint32_t holder_owner[PAY_EQ_MAX_HOLDERS];
    uint32_t holder_acct[PAY_EQ_MAX_HOLDERS];
    uint32_t n_holders;
    uint64_t last_price; /* last trade price, 0 = none */
} pay_eq_inst_t;

typedef struct {
    bool active;
    uint64_t id;
    uint64_t seq; /* time priority */
    uint32_t inst;
    uint32_t owner;
    uint32_t money_acct;
    uint32_t share_acct;
    uint8_t side;
    uint8_t type;
    uint64_t price;     /* limit price (0 for market) */
    uint64_t remaining; /* shares */
    uint64_t reserved;  /* money (buy) or shares (sell) still reserved */
} pay_eq_order_t;

typedef enum {
    PAY_EQ_EV_CREATE = 0,
    PAY_EQ_EV_ISSUE,
    PAY_EQ_EV_ORDER,
    PAY_EQ_EV_CANCEL,
    PAY_EQ_EV_STP_CANCEL,
    PAY_EQ_EV_CAP_CUT,
    PAY_EQ_EV_FILL,
    PAY_EQ_EV_VFV_MINT
} pay_eq_event_kind_t;

typedef struct {
    uint64_t seq;
    uint8_t kind;
    uint32_t inst;
    uint64_t order_a, order_b;
    uint32_t owner_a, owner_b;
    uint64_t qty, price;
    uint8_t hash[PAY_HASH_LEN];
} pay_eq_event_t;

typedef struct {
    bool enabled;
    uint8_t role_mask; /* bit r set: pay_role_t r may participate */
    char disabled_juris[PAY_EQ_MAX_JURIS][8];
    uint32_t n_disabled;
    pay_rat_t default_cap; /* 8/21 */
} pay_equity_cfg_t;

typedef struct {
    bool active;
    uint32_t owner;
    uint8_t role;
    char juris[8];
} pay_eq_part_t;

typedef struct {
    bool ready;
    uint32_t inst; /* the VFV-EQ instrument */
    uint32_t n_levels;
    uint64_t weights[PAY_EQ_LEVELS];
    uint64_t level_total[PAY_EQ_LEVELS];
    uint64_t minted_seen; /* VFV minted and reported */
} pay_vfv_equity_t;

typedef struct {
    pay_ledger_t *L;
    pay_equity_cfg_t cfg;
    pay_eq_part_t part[PAY_EQ_MAX_PART];
    uint32_t n_part;
    pay_eq_inst_t inst[PAY_EQ_MAX_INST];
    uint32_t n_inst;
    pay_eq_order_t ord[PAY_EQ_MAX_ORDERS];
    uint64_t next_order_id;
    uint64_t seq;
    uint64_t reserved[PAY_MAX_ACCOUNTS]; /* per ledger account */
    pay_eq_event_t audit[PAY_EQ_AUDIT];  /* ring */
    uint64_t n_events;
    uint8_t audit_head[PAY_HASH_LEN];
    uint64_t fills;
    pay_vfv_equity_t vfv;
} pay_equity_t;

void pay_equity_cfg_default(pay_equity_cfg_t *c); /* disabled, no roles, cap 8/21 */
pay_status_t pay_equity_init(pay_equity_t *ex, pay_ledger_t *L, const pay_equity_cfg_t *cfg);

/* Participants: refused when equity is disabled, the role is not in the
 * mask, or the jurisdiction is disabled. */
pay_status_t pay_equity_register(pay_equity_t *ex, uint32_t owner, pay_role_t role,
                                 const char *jurisdiction);

/* Create an instrument. FIXED: `supply` is issued to the issuer at once.
 * ISSUABLE: `supply` is issued now and up to `max_supply` (0 = no maximum)
 * later. `cap` NULL = cfg.default_cap. */
pay_status_t pay_equity_create_voting(pay_equity_t *ex, const pay_obj_ref_t *obj,
                                      uint32_t issuer_owner, uint16_t quote_asset,
                                      pay_supply_t mode, uint64_t supply, uint64_t max_supply,
                                      const pay_rat_t *cap, pay_eq_voting_t *out);
pay_status_t pay_equity_create_nonvoting(pay_equity_t *ex, const pay_obj_ref_t *obj,
                                         uint32_t issuer_owner, uint16_t quote_asset,
                                         pay_supply_t mode, uint64_t supply, uint64_t max_supply,
                                         const pay_rat_t *cap, pay_eq_nonvoting_t *out);
uint32_t pay_eq_v_index(pay_eq_voting_t h);
uint32_t pay_eq_nv_index(pay_eq_nonvoting_t h);

/* ISSUABLE only: issue `qty` more shares to the issuer. */
pay_status_t pay_equity_issue(pay_equity_t *ex, uint32_t inst, uint64_t qty);
/* Move shares from the issuer to a holder outside the book (an allocation),
 * still subject to E3. */
pay_status_t pay_equity_allocate(pay_equity_t *ex, uint32_t inst, uint32_t to_owner, uint64_t qty);

/* Orders. For a market buy, `price` is the maximum total spend. Returns the
 * order id in *order_id (0 if the order did not rest). */
pay_status_t pay_equity_order(pay_equity_t *ex, uint32_t inst, uint32_t owner, uint32_t money_acct,
                              pay_side_t side, pay_ord_type_t type, uint64_t price, uint64_t qty,
                              uint64_t *order_id);
pay_status_t pay_equity_cancel(pay_equity_t *ex, uint64_t order_id, uint32_t owner);

/* Ownership records. */
uint64_t pay_equity_holding(const pay_equity_t *ex, uint32_t inst, uint32_t owner);
const pay_eq_inst_t *pay_equity_inst(const pay_equity_t *ex, uint32_t inst);
uint64_t pay_equity_reserved(const pay_equity_t *ex, uint32_t acct);
/* Voting weight: only for a voting handle. */
uint64_t pay_equity_votes(const pay_equity_t *ex, pay_eq_voting_t h, uint32_t owner);
/* True iff the instrument's shares carry votes (false for VFV equity). */
bool pay_equity_has_votes(const pay_equity_t *ex, uint32_t inst);

/* E4 + book consistency: holders sum to supply, issuer credit == supply,
 * reservations match resting orders, ledger invariants hold. */
bool pay_equity_check(const pay_equity_t *ex);
bool pay_equity_verify_audit(const pay_equity_t *ex);

/* ===== VFV currency equity (V1-V3) ===== */
/* Create the VFV-EQ non-voting instrument, issued by `platform_owner`, quoted
 * in `quote_asset` (VFV itself by default), with `n_levels` fractal levels
 * (2..4). */
pay_status_t pay_vfv_equity_init(pay_equity_t *ex, uint32_t platform_owner, uint16_t quote_asset,
                                 uint32_t n_levels, pay_eq_nonvoting_t *out);
/* Generate equity for `amount` VFV just minted to `holder`; `path` holds the
 * owner ids of levels 1..n_levels-1 (node, alliance, global). */
pay_status_t pay_vfv_equity_on_mint(pay_equity_t *ex, uint32_t holder, const uint32_t *path,
                                    uint64_t amount);
/* V3. */
bool pay_vfv_equity_audit(const pay_equity_t *ex);

#endif /* ZXV_PAY_EQUITY_H */
