#!/usr/bin/env python3
"""make_chime.py — convert the ZEDEC jingle into an embeddable boot chime.

The kernel plays a startup chime while booting (like a Mac). The source
jingle is 48 kHz stereo 16-bit (2.6 MB) — far too large to embed in a
227 KB kernel — so this downsamples to mono and quantises, then emits a
C header with the PCM data plus its format.

Encodings:
  u8     unsigned 8-bit PCM      (1 byte/sample, simple, a little hissy)
  ulaw   G.711 mu-law            (1 byte/sample, ~12-bit perceived range)
  adpcm  IMA ADPCM 4-bit         (0.5 byte/sample, best size/quality)

Usage:
  make_chime.py <in.wav> <out.h> [--rate 16000] [--enc ulaw]
                [--seconds N] [--gain 1.0] [--symbol boot_chime]
"""
import sys, wave, array, argparse, os

def load_mono(path, want_rate, seconds=None, gain=1.0):
    w = wave.open(path, "rb")
    ch, sw, sr, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
    if sw != 2:
        raise SystemExit(f"only 16-bit input supported (got {sw*8}-bit)")
    raw = w.readframes(n); w.close()
    a = array.array('h'); a.frombytes(raw)
    # to mono
    if ch == 2:
        mono = [(a[i] + a[i+1]) // 2 for i in range(0, len(a) - 1, 2)]
    else:
        mono = list(a)
    if seconds:
        mono = mono[:int(sr * seconds)]
    # linear-interpolating resample to want_rate
    ratio = want_rate / sr
    out_n = int(len(mono) * ratio)
    out = []
    for i in range(out_n):
        p = i / ratio
        i0 = int(p); i1 = min(i0 + 1, len(mono) - 1)
        f = p - i0
        s = mono[i0] * (1.0 - f) + mono[i1] * f
        s *= gain
        out.append(max(-32768, min(32767, int(s))))
    return out, sr

# ---- encoders ----
def enc_u8(s):
    return bytes(((x + 32768) >> 8) & 0xFF for x in s)

_ULAW_BIAS, _ULAW_CLIP = 0x84, 32635
def enc_ulaw(s):
    out = bytearray()
    for x in s:
        sign = 0x80 if x < 0 else 0
        if x < 0: x = -x
        if x > _ULAW_CLIP: x = _ULAW_CLIP
        x += _ULAW_BIAS
        exp = 7
        mask = 0x4000
        while exp > 0 and not (x & mask):
            exp -= 1; mask >>= 1
        mant = (x >> (exp + 3)) & 0x0F
        out.append(~(sign | (exp << 4) | mant) & 0xFF)
    return bytes(out)

_STEP = [7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,50,55,60,66,
         73,80,88,97,107,118,130,143,157,173,190,209,230,253,279,307,337,371,
         408,449,494,544,598,658,724,796,876,963,1060,1166,1282,1411,1552,
         1707,1878,2066,2272,2499,2749,3024,3327,3660,4026,4428,4871,5358,
         5894,6484,7132,7845,8630,9493,10442,11487,12635,13899,15289,16818,
         18500,20350,22385,24623,27086,29794,32767]
_IDX = [-1,-1,-1,-1,2,4,6,8,-1,-1,-1,-1,2,4,6,8]
def enc_adpcm(s):
    """IMA ADPCM, 4 bits/sample, two samples packed per byte (low nibble first)."""
    pred, idx, out, buf, have = 0, 0, bytearray(), 0, False
    for x in s:
        step = _STEP[idx]
        diff = x - pred
        code = 0
        if diff < 0: code = 8; diff = -diff
        t = step
        if diff >= t: code |= 4; diff -= t
        t >>= 1
        if diff >= t: code |= 2; diff -= t
        t >>= 1
        if diff >= t: code |= 1
        # mirror the decoder to keep predictor in sync
        d = step >> 3
        if code & 4: d += step
        if code & 2: d += step >> 1
        if code & 1: d += step >> 2
        pred = pred - d if (code & 8) else pred + d
        pred = max(-32768, min(32767, pred))
        idx = max(0, min(88, idx + _IDX[code]))
        if have:
            out.append(buf | (code << 4)); have = False
        else:
            buf = code & 0x0F; have = True
    if have: out.append(buf)
    return bytes(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("infile"); ap.add_argument("outfile")
    ap.add_argument("--rate", type=int, default=16000)
    ap.add_argument("--enc", choices=["u8","ulaw","adpcm"], default="adpcm")
    ap.add_argument("--seconds", type=float, default=None)
    ap.add_argument("--gain", type=float, default=1.0)
    ap.add_argument("--symbol", default="boot_chime")
    a = ap.parse_args()

    samples, src_rate = load_mono(a.infile, a.rate, a.seconds, a.gain)
    data = {"u8": enc_u8, "ulaw": enc_ulaw, "adpcm": enc_adpcm}[a.enc](samples)
    dur = len(samples) / a.rate
    enc_id = {"u8": 0, "ulaw": 1, "adpcm": 2}[a.enc]

    with open(a.outfile, "w") as f:
        f.write(f"/* {os.path.basename(a.outfile)} — GENERATED by build_system/make_chime.py\n")
        f.write(f" * source: {os.path.basename(a.infile)} ({src_rate} Hz)\n")
        f.write(f" * boot chime: {a.rate} Hz mono, {a.enc}, {dur:.2f}s, {len(data)} bytes\n */\n")
        g = a.symbol.upper()
        f.write(f"#ifndef {g}_H\n#define {g}_H\n")
        f.write(f"#define {g}_RATE      {a.rate}\n")
        f.write(f"#define {g}_ENCODING  {enc_id}   /* 0=u8 1=ulaw 2=ima-adpcm */\n")
        f.write(f"#define {g}_SAMPLES   {len(samples)}\n")
        f.write(f"static const unsigned char {a.symbol}[] = {{\n")
        for i in range(0, len(data), 16):
            f.write("  " + "".join(f"0x{b:02x}," for b in data[i:i+16]) + "\n")
        f.write("};\n")
        f.write(f"static const unsigned int {a.symbol}_len = sizeof({a.symbol});\n")
        f.write(f"#endif /* {g}_H */\n")
    print(f"{a.enc:5s} {a.rate:6d}Hz {dur:6.2f}s -> {len(data):8d} bytes  {a.outfile}")

if __name__ == "__main__":
    main()
