#!/usr/bin/env bash
# mk_deliverable_zip.sh — assemble the COMPLETE ZXV / ZEDEC pqOS five-arch
# multikernel as a self-contained folder tree and ZIP it for testing.
#
# Run on the Linux build box from the tree root's build_system/ dir:
#     bash build_system/mk_deliverable_zip.sh
#
# Produces:  dist/ZXV_ZEDEC_pqOS/           (the tree)
#            dist/ZXV_ZEDEC_pqOS.zip         (the shippable archive)
#
# Nothing here is hardcoded that can be discovered: shas are computed, the arm32
# .bin is objcopy'd from the real ELF, the manifest is generated by walking the
# tree. Signing keys are DELIBERATELY EXCLUDED (never ship build_system/keys).
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)      # ~/zxv (the buildable tree root)
OUT="$ROOT/dist/ZXV_ZEDEC_pqOS"
ZIP="$ROOT/dist/ZXV_ZEDEC_pqOS.zip"

echo "ROOT = $ROOT"
echo "OUT  = $OUT"
rm -rf "$OUT" "$ZIP"
mkdir -p "$OUT"/{src,build,bin,discs,screendumps,docs}

# ---------------------------------------------------------------------------
# 1. src/  — the COMPLETE buildable tree: kernel/ and build_system/ as REAL
#    siblings (the canonical scripts do `find kernel ...` and expect them side
#    by side; symlinks would break gen_phase_table.sh). No objects/vcs/backups,
#    no signing keys.
# ---------------------------------------------------------------------------
echo "[1] src/kernel ..."
rsync -a \
  --exclude='*.o' --exclude='*.d' --exclude='*.orig' \
  --exclude='build/' --exclude='.git' --exclude='__pycache__' \
  --exclude='.DS_Store' \
  "$ROOT/kernel" "$OUT/src/"

echo "[1b] src/build_system ..."
mkdir -p "$OUT/src/build_system"
rsync -a \
  --exclude='*.o' --exclude='*.d' --exclude='__pycache__' \
  --exclude='keys' --exclude='.DS_Store' --exclude='_deliv_*' \
  "$ROOT/build_system/" "$OUT/src/build_system/"

# ---------------------------------------------------------------------------
# 2. build/ — the build ENTRY POINT. `build/build_all.sh` is a plain cd-wrapper
#    that runs the canonical, UNMODIFIED build system in ../src/build_system
#    (where kernel/ is a real sibling, so `find kernel` and gen_phase_table.sh
#    work). No symlinks, no path magic.
# ---------------------------------------------------------------------------
echo "[2] build/ entry ..."
cat > "$OUT/build/build_all.sh" <<'WRAP'
#!/usr/bin/env bash
# build_all.sh — packaged-tree entry point for the ZXV / ZEDEC pqOS build+verify.
#
# The canonical build system lives in ../src/build_system, alongside the real
# kernel/ tree (../src/kernel). It expects to run from a ROOT that has kernel/
# and build_system/ as siblings and emits kernel_*.elf there — which is exactly
# ../src. So this just cd's there and runs it unmodified. Fresh ELF/.bin and the
# object tree land under ../src/ (kernel_*.elf, build/<arch>/).
set -eu
here=$(cd "$(dirname "$0")" && pwd)          # <pkg>/build
pkg=$(dirname "$here")                        # <pkg>
cd "$pkg/src"
exec build_system/build_all.sh "$@"
WRAP
chmod +x "$OUT/build/build_all.sh"

cat > "$OUT/build/README.md" <<'BR'
# build/ — entry point

`build/build_all.sh` is the one command a tester runs to reproduce the build +
verification matrix:

```bash
bash build/build_all.sh
```

It is a thin cd-wrapper. The **canonical, unmodified build system** — the five
Makefiles, `build_all.sh`, `mk_efi_disc.sh`, `gen_phase_table.sh`,
`verify_layers.sh`, `verify_banners.sh`, and the rest — lives in
**`../src/build_system/`**, because those scripts do `find kernel …` and expect
`kernel/` and `build_system/` to be **real siblings** (which they are, under
`src/`). Running them from `src/` is the supported path; the wrapper does exactly
that. Build artifacts (`kernel_*.elf/.bin`, the `build/<arch>/` object tree) are
written under `../src/`.

To rebuild the UEFI discs (optional; prebuilt copies are in `../discs/`):

```bash
cd ../src && bash build_system/mk_efi_disc.sh x86_64   # -> BOOTX64.EFI + disc
cd ../src && bash build_system/mk_efi_disc.sh arm64    # -> BOOTAA64.EFI + disc
```
BR

# ---------------------------------------------------------------------------
# 3. bin/ — the five kernel ELF + .bin
#    arm32 has no canonical .bin (Makefile.arm32 BIN=-); objcopy it from the
#    real fresh ELF so bin/ is complete.
# ---------------------------------------------------------------------------
echo "[3] bin/ ..."
cp "$ROOT/kernel_arm64.elf"  "$ROOT/kernel_arm64.bin"  "$OUT/bin/"
cp "$ROOT/kernel_x86_64.elf" "$ROOT/kernel_x86_64.bin" "$OUT/bin/"
cp "$ROOT/kernel_riscv.elf"  "$ROOT/kernel_riscv.bin"  "$OUT/bin/"    # riscv64
cp "$ROOT/kernel_riscv32.elf" "$ROOT/kernel_riscv32.bin" "$OUT/bin/"
cp "$ROOT/zedec_xero_arm32.elf" "$OUT/bin/"
arm-linux-gnueabihf-objcopy -O binary "$ROOT/zedec_xero_arm32.elf" "$OUT/bin/zedec_xero_arm32.bin"

# ---------------------------------------------------------------------------
# 4. discs/ — the two UEFI disc images + MEGAROM.TVL + firmware + per-arch
#    firmware-media payloads + the discs README. Base on the assembled
#    deliverable/discs payload, refresh the two UEFI imgs + MEGAROM.TVL from
#    dist/discs (the freshest, matching the verified shas).
# ---------------------------------------------------------------------------
echo "[4] discs/ ..."
rsync -a "$ROOT/deliverable/discs/" "$OUT/discs/"
cp "$ROOT/dist/discs/zxv-arm64-uefi.img"  "$OUT/discs/"
cp "$ROOT/dist/discs/zxv-x86_64-uefi.img" "$OUT/discs/"
cp "$ROOT/dist/discs/MEGAROM.TVL"         "$OUT/discs/"
rm -f "$OUT/discs/SHA256SUMS"   # stale; the top-level MANIFEST.txt is authoritative

# ---------------------------------------------------------------------------
# 5. screendumps/ — the per-platform render PNGs, honestly named.
# ---------------------------------------------------------------------------
echo "[5] screendumps/ ..."
cp "$ROOT/icap_out/icap_arm64.png"   "$OUT/screendumps/arm64_ramfb_RENDERED_2560x1440.png"
cp "$ROOT/icap_out/icap_riscv64.png" "$OUT/screendumps/riscv64_ramfb_RENDERED_1920x1080.png"
cp "$ROOT/icap_out/icap_riscv32.png" "$OUT/screendumps/riscv32_ramfb_RENDERED_1920x1080.png"
cp "$ROOT/icap_out/icap_arm32.png"   "$OUT/screendumps/arm32_ramfb_RENDERED_1920x1080.png"
cp "$ROOT/icap_out/uefi_arm64.png"   "$OUT/screendumps/arm64_uefi_gop_BLTONLY_blank.png"
cp "$ROOT/icap_out/uefi_x86_64.png"  "$OUT/screendumps/x86_64_uefi_ovmf_firmware_console.png"

# ---------------------------------------------------------------------------
# 6. docs/ — all PROVENANCE/*.md + two matrices + key top-level context docs +
#    the capture scripts used to produce the screendumps (reference).
# ---------------------------------------------------------------------------
echo "[6] docs/ ..."
mkdir -p "$OUT/docs/PROVENANCE" "$OUT/docs/capture"
cp "$ROOT"/PROVENANCE/*.md "$OUT/docs/PROVENANCE/"
cp "$ROOT/ARCHITECTURE_WHITEPAPER.md" "$OUT/docs/" 2>/dev/null || true
cp "$ROOT/SUBSYSTEM_INDEX.md"         "$OUT/docs/" 2>/dev/null || true
cp "$ROOT/SOURCE_CODE_NAVIGATION_GUIDE.md" "$OUT/docs/" 2>/dev/null || true
cp "$ROOT/icap.py"      "$OUT/docs/capture/" 2>/dev/null || true
cp "$ROOT/icap_uefi.py" "$OUT/docs/capture/" 2>/dev/null || true

# The matrices are written by the caller (heredocs pushed alongside) into
# $OUT/docs/ before zipping — see mk_deliverable_docs below if present.
if [ -f "$ROOT/build_system/_deliv_VERIFICATION_MATRIX.md" ]; then
  cp "$ROOT/build_system/_deliv_VERIFICATION_MATRIX.md" "$OUT/docs/VERIFICATION_MATRIX.md"
fi
if [ -f "$ROOT/build_system/_deliv_RENDER_MATRIX.md" ]; then
  cp "$ROOT/build_system/_deliv_RENDER_MATRIX.md" "$OUT/docs/RENDER_MATRIX.md"
fi
if [ -f "$ROOT/build_system/_deliv_README.md" ]; then
  cp "$ROOT/build_system/_deliv_README.md" "$OUT/README.md"
fi

# ---------------------------------------------------------------------------
# 7. MANIFEST.txt — every file with sha256 (walk the finished tree).
# ---------------------------------------------------------------------------
echo "[7] MANIFEST.txt ..."
( cd "$OUT" && find . -type f -not -name MANIFEST.txt | LC_ALL=C sort \
    | while read -r f; do sha256sum "$f"; done ) > "$OUT/MANIFEST.txt"

# ---------------------------------------------------------------------------
# 8. ZIP + report
# ---------------------------------------------------------------------------
echo "[8] zip ..."
( cd "$ROOT/dist" && zip -rq ZXV_ZEDEC_pqOS.zip ZXV_ZEDEC_pqOS )

echo "=================================================================="
echo "ZIP:   $ZIP"
echo "SIZE:  $(du -h "$ZIP" | cut -f1)  ($(stat -c%s "$ZIP") bytes)"
echo "SHA:   $(sha256sum "$ZIP" | cut -d' ' -f1)"
echo "FILES: $(find "$OUT" -type f | wc -l)"
echo "------------------------------------------------------------------"
echo "TREE (top two levels):"
( cd "$ROOT/dist" && find ZXV_ZEDEC_pqOS -maxdepth 2 | LC_ALL=C sort )
echo "=================================================================="
