#!/usr/bin/env python3
"""sign_package.py — build an Ed25519-signed ZXV package (.zsp) and emit a
C header the kernel embeds (root public key + signed package bytes).

A .zsp binds a payload (an ELF) to a signature over its SHA-256 under an
offline root key, so the kernel loads code only if BOTH integrity
(hash) and authenticity (signature) check out. This is the on-target
half of the audit's trust chain (P0-3): a root key gates what executes.

Layout (little-endian, then payload):
    magic[4]   = b"ZSP1"
    payload_len: u32
    sha256[32] : SHA-256(payload)
    sig[64]    : Ed25519(magic || payload_len || sha256)  <- 40-byte preimage
    payload    : the ELF bytes

Usage:
    sign_package.py <payload.elf> <root_priv.pem> <root_pub.bin>
                    <out.zsp> <out_header.h> <symbol_prefix>
"""
import sys, struct, hashlib, subprocess, os

def main():
    if len(sys.argv) != 7:
        print(__doc__); sys.exit(2)
    payload_path, priv_pem, pub_bin, out_zsp, out_h, sym = sys.argv[1:7]

    payload = open(payload_path, "rb").read()
    sha = hashlib.sha256(payload).digest()
    magic = b"ZSP1"
    preimage = magic + struct.pack("<I", len(payload)) + sha  # 40 bytes

    # Sign the 40-byte preimage with Ed25519 (pure, raw input).
    pre_tmp = out_zsp + ".pre"
    sig_tmp = out_zsp + ".sig"
    open(pre_tmp, "wb").write(preimage)
    subprocess.run(["openssl", "pkeyutl", "-sign", "-inkey", priv_pem,
                    "-rawin", "-in", pre_tmp, "-out", sig_tmp], check=True)
    sig = open(sig_tmp, "rb").read()
    assert len(sig) == 64, f"bad sig len {len(sig)}"
    os.remove(pre_tmp); os.remove(sig_tmp)

    pkg = preimage + sig + payload
    open(out_zsp, "wb").write(pkg)

    pub = open(pub_bin, "rb").read()
    assert len(pub) == 32, f"bad pubkey len {len(pub)}"

    def carr(name, data):
        out = [f"static const unsigned char {name}[] = {{"]
        for i in range(0, len(data), 16):
            out.append("  " + "".join(f"0x{b:02x}," for b in data[i:i+16]))
        out.append("};")
        out.append(f"static const unsigned int {name}_len = sizeof({name});")
        return "\n".join(out)

    with open(out_h, "w") as f:
        f.write(f"/* {os.path.basename(out_h)} — GENERATED by sign_package.py. Do not edit.\n")
        f.write(" * Root Ed25519 public key + the signed package the kernel seeds\n")
        f.write(" * to disk. Rebuild via build_system/build_signed_app.sh.\n */\n")
        f.write(f"#ifndef {sym.upper()}_SIGNED_H\n#define {sym.upper()}_SIGNED_H\n")
        f.write(carr(f"{sym}_root_pubkey", pub) + "\n")
        f.write(carr(f"{sym}_zsp", pkg) + "\n")
        f.write(f"#endif /* {sym.upper()}_SIGNED_H */\n")

    print(f"signed {payload_path}: payload={len(payload)}B pkg={len(pkg)}B -> {out_zsp}, {out_h}")

if __name__ == "__main__":
    main()
