#!/usr/bin/env python3
"""sign_package.py — build an Ed25519-signed ZXV package (.zsp) and emit a
C header the kernel embeds (root public key + signed package bytes).

A .zsp binds a payload (an ELF) to a signature over its SHA-256 under an
offline root key, so the kernel loads code only if BOTH integrity
(hash) and authenticity (signature) check out. This is the on-target
half of the audit's trust chain (P0-3): a root key gates what executes.

Layout (little-endian, then payload):
    magic[4]   = b"ZSP1"
    payload_len: u32
    sha256[32] : SHA-256(payload)
    sig[64]    : Ed25519(magic || payload_len || sha256)  <- 40-byte preimage
    payload    : the ELF bytes

Usage:
    sign_package.py <payload.elf> <root_priv.pem> <root_pub.bin>
                    <out.zsp> <out_header.h> <symbol_prefix>
"""
import sys, struct, hashlib, subprocess, os

ARCH_IDS = {"any":0,"arm64":1,"x86_64":2,"riscv64":3,"riscv32":4,"arm32":5}

def build_preimage_v2(payload, pub, version, arch, abi, caps, name):
    """ZSP v2 signed preimage (96 bytes) — see zsp.h."""
    sha = hashlib.sha256(payload).digest()
    key_id = hashlib.sha256(pub).digest()[:8]
    identity = hashlib.sha256(b"zxv-package:" + name.encode()).digest()
    hdr = b"ZSP2"
    hdr += struct.pack("<H", 96)               # hdr_len (preimage length)
    hdr += struct.pack("<H", abi)              # abi
    hdr += struct.pack("<I", version)          # version (anti-rollback)
    hdr += struct.pack("<H", arch)             # arch
    hdr += struct.pack("<H", 0)                # reserved
    hdr += struct.pack("<I", caps)             # caps
    hdr += struct.pack("<I", len(payload))     # payload_len
    hdr += key_id                              # key_id[8]
    hdr += identity                            # identity[32]
    hdr += sha                                 # sha256[32]
    assert len(hdr) == 96, len(hdr)
    return hdr

def main():
    argv = sys.argv[1:]
    # optional flags (v2): --v2 --version=N --arch=NAME --caps=N --abi=N --name=STR
    v2 = False; version = 1; arch = 0; caps = 0; abi = 1; name = "app"
    pos = []
    for a in argv:
        if a == "--v2": v2 = True
        elif a.startswith("--version="): version = int(a.split("=",1)[1], 0)
        elif a.startswith("--arch="):
            v = a.split("=",1)[1]; arch = ARCH_IDS.get(v, int(v,0) if v.isdigit() else 0); v2 = True
        elif a.startswith("--caps="): caps = int(a.split("=",1)[1], 0)
        elif a.startswith("--abi="): abi = int(a.split("=",1)[1], 0)
        elif a.startswith("--name="): name = a.split("=",1)[1]
        else: pos.append(a)
    if len(pos) != 6:
        print(__doc__); sys.exit(2)
    payload_path, priv_pem, pub_bin, out_zsp, out_h, sym = pos

    payload = open(payload_path, "rb").read()
    pub = open(pub_bin, "rb").read()
    assert len(pub) == 32, f"bad pubkey len {len(pub)}"

    if v2:
        preimage = build_preimage_v2(payload, pub, version, arch, abi, caps, name)
    else:
        sha = hashlib.sha256(payload).digest()
        magic = b"ZSP1"
        preimage = magic + struct.pack("<I", len(payload)) + sha  # 40 bytes

    # Sign the 40-byte preimage with Ed25519 (pure, raw input).
    pre_tmp = out_zsp + ".pre"
    sig_tmp = out_zsp + ".sig"
    open(pre_tmp, "wb").write(preimage)
    subprocess.run(["openssl", "pkeyutl", "-sign", "-inkey", priv_pem,
                    "-rawin", "-in", pre_tmp, "-out", sig_tmp], check=True)
    sig = open(sig_tmp, "rb").read()
    assert len(sig) == 64, f"bad sig len {len(sig)}"
    os.remove(pre_tmp); os.remove(sig_tmp)

    pkg = preimage + sig + payload
    open(out_zsp, "wb").write(pkg)

    def carr(name, data):
        out = [f"static const unsigned char {name}[] = {{"]
        for i in range(0, len(data), 16):
            out.append("  " + "".join(f"0x{b:02x}," for b in data[i:i+16]))
        out.append("};")
        out.append(f"static const unsigned int {name}_len = sizeof({name});")
        return "\n".join(out)

    with open(out_h, "w") as f:
        f.write(f"/* {os.path.basename(out_h)} — GENERATED by sign_package.py. Do not edit.\n")
        f.write(" * Root Ed25519 public key + the signed package the kernel seeds\n")
        f.write(" * to disk. Rebuild via build_system/build_signed_app.sh.\n */\n")
        f.write(f"#ifndef {sym.upper()}_SIGNED_H\n#define {sym.upper()}_SIGNED_H\n")
        f.write(carr(f"{sym}_root_pubkey", pub) + "\n")
        f.write(carr(f"{sym}_zsp", pkg) + "\n")
        f.write(f"#endif /* {sym.upper()}_SIGNED_H */\n")

    print(f"signed {payload_path}: payload={len(payload)}B pkg={len(pkg)}B -> {out_zsp}, {out_h}")

if __name__ == "__main__":
    main()
