# Generate test_tok_fixture.h: a byte-level BPE tokenizer trained with the
# reference Hugging Face `tokenizers` library on the repo's docs, stored in a
# GGUF file by gguf-py (pre-tokenizer "qwen2"), plus the reference token ids
# for a set of test strings under both the "qwen2" and "llama-bpe" splits
# (training uses the llama-bpe split so that multi-digit merges exist). Usage:
#   python3 -m pip install tokenizers gguf numpy
#   python3 gen_tok_fixture.py test_tok_fixture.h
import sys, os, glob, json, tempfile
import gguf
from tokenizers import Tokenizer, models, pre_tokenizers, trainers, decoders, Regex

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = sorted(glob.glob(os.path.join(HERE, '..', '..', '..', 'docs', '*.md')))[:40]
PAT = {
    'qwen2': r"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+",
    'llama-bpe': r"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+",
}
SPECIAL = ['<|endoftext|>', '<|im_start|>', '<|im_end|>']

def make(pre):
    t = Tokenizer(models.BPE())
    t.pre_tokenizer = pre_tokenizers.Sequence([
        pre_tokenizers.Split(Regex(PAT[pre]), behavior='isolated', invert=False),
        pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=False)])
    t.decoder = decoders.ByteLevel()
    return t

base = make('llama-bpe')
base.train(DOCS, trainers.BpeTrainer(vocab_size=1200, special_tokens=SPECIAL,
           initial_alphabet=pre_tokenizers.ByteLevel.alphabet(), show_progress=False))
model = json.loads(base.to_str())['model']
vocab = sorted(model['vocab'].items(), key=lambda kv: kv[1])
tokens = [k for k, _ in vocab]
assert [i for _, i in vocab] == list(range(len(tokens)))
merges = [' '.join(m) if isinstance(m, list) else m for m in model['merges']]
types = [3 if tok in SPECIAL else 1 for tok in tokens]

TEXTS = [
    "it'\u017f fine and Kelvin \u212a",
    "x\x01\x1f\x7f\u0085y \u2028z",
    "Hello world",
    "The ZXV kernel boots the swarm; it's what we've built, isn't it?",
    "I'M SURE THEY'LL SAY WE'D DONE IT'S DONE",
    "numbers 1234567 and 3.14159, 2026-10-09",
    "  leading spaces and trailing   ",
    "tabs\tand\nnewlines\r\n\r\nmixed \n\n  \n end",
    "punctuation!!! ... ??? (brackets) [x] {y} <z> --> ==>",
    "café naïve résumé über Straße",
    "世界你好，这是一个测试。",
    "emoji \U0001F600\U0001F680 and ✨ sparkle",
    "<|im_start|>user\nHi there<|im_end|>\n<|im_start|>assistant\n",
    "end of text<|endoftext|>next",
    "x" * 60 + " " + "ab" * 30,
    "١٢٣ Arabic digits and Ⅷ roman",
    "nbsp here and　ideographic space",
    "a'b 'S 'tis o'clock ''",
    "",
    " ",
    "\n",
    "code: int main(void) { return 0; } // done",
]

# plus seeded random strings over an alphabet chosen to hit every regex branch
import random
rng = random.Random(20261009)
ALPHA = (list("abcXYZ019 '") * 3 + [" ", "  ", "\n", "\r\n", "\t", "'s", "'LL", "'re", "!", "...", "(", "-", "\u00a0",
         "\u3000", "\u2028", "\u0085", "\u00e9", "\u0301", "\u4e16", "\U0001F600", "\u0661", "\u2167", "\u212a",
         "\u017f", "\x0b", "\x1c", "_", "\"", "<|im_end|>", "<|im", "1234"])
for _ in range(150):
    TEXTS.append(''.join(rng.choice(ALPHA) for _ in range(rng.randint(1, 30))))

def esc(s):
    b = s.encode('utf-8')
    return '"' + ''.join('\\x%02x' % c for c in b) + '"', len(b)

out = ['/* test_tok_fixture.h — generated by gen_tok_fixture.py. A byte-level BPE',
       ' * tokenizer trained by Hugging Face tokenizers %s on the repo docs, written' % __import__('tokenizers').__version__,
       ' * to GGUF by gguf-py, and the reference encodings of TOK_TEXTS. Do not edit. */',
       '#include <stdint.h>']
def cstr(blob):
    # octal escapes for everything but plain ASCII; ? is escaped (trigraphs)
    lines, cur = [], ''
    for b in blob:
        ch = chr(b)
        cur += ch if (32 <= b < 127 and ch not in '"\\?') else '\\%03o' % b
        if len(cur) >= 96: lines.append('    "%s"' % cur); cur = ''
    if cur: lines.append('    "%s"' % cur)
    return lines

path = os.path.join(tempfile.mkdtemp(), 'tok.gguf')
w = gguf.GGUFWriter(path, 'qwen2')
w.add_tokenizer_model('gpt2')
w.add_tokenizer_pre('qwen2')
w.add_token_list(tokens)
w.add_token_merges(merges)
w.add_token_types(types)
w.add_bos_token_id(tokens.index('<|endoftext|>'))
w.add_eos_token_id(tokens.index('<|im_end|>'))
w.write_header_to_file(); w.write_kv_data_to_file(); w.write_tensors_to_file(); w.close()
blob = open(path, 'rb').read()
out.append('#define TOK_GGUF_LEN %du' % len(blob))
out.append('static const char TOK_GGUF[TOK_GGUF_LEN + 1] =')
out += cstr(blob)
out[-1] += ';'
for pre in ('qwen2', 'llama-bpe'):
    c = pre.replace('-', '_').upper()
    t = make(pre)
    t.model = models.BPE(vocab=dict(model['vocab']), merges=[tuple(m.split(' ')) for m in merges],
                         ignore_merges=(pre == 'llama-bpe'))
    t.add_special_tokens(SPECIAL)
    ids = []
    for s in TEXTS:
        e = t.encode(s).ids
        assert t.decode(e, skip_special_tokens=False) == s, (pre, s)
        ids.append(e)
    flat = [i for e in ids for i in e]
    out.append('static const int32_t TOK_IDS_%s[%d] = {' % (c, max(1, len(flat))))
    for i in range(0, len(flat), 16):
        out.append('    ' + ', '.join(str(v) for v in flat[i:i + 16]) + ',')
    out.append('};')
    out.append('static const uint32_t TOK_NIDS_%s[%d] = { %s };' % (c, len(ids), ', '.join(str(len(e)) for e in ids)))
out.append('static const struct { const char *s; uint32_t len; } TOK_TEXTS[%d] = {' % len(TEXTS))
for s in TEXTS:
    e, n = esc(s)
    out.append('    { %s, %d },' % (e, n))
out.append('};')
out.append('#define TOK_N_TEXTS %du' % len(TEXTS))
out.append('#define TOK_N_VOCAB %du' % len(tokens))
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
print(len(tokens), len(merges), os.path.getsize(sys.argv[1]))
