# Generate test_gguf_fixture.h: a small GGUF file written by the reference
# gguf-py writer (llama.cpp's own Python package) plus the reference
# dequantised values, rounded to Q16. Usage:
#   python3 -m pip install gguf numpy
#   python3 gen_gguf_fixture.py test_gguf_fixture.h
import sys, os, tempfile
import numpy as np
import gguf
from gguf import GGMLQuantizationType as T
from gguf import quants

rng = np.random.default_rng(20261009)
path = os.path.join(tempfile.mkdtemp(), 'fixture.gguf')
w = gguf.GGUFWriter(path, 'qwen3')
w.add_uint32('test.u32', 4000000000)
w.add_int32('test.i32', -123456)
w.add_float32('test.f32', -2.5)
w.add_bool('test.bool', True)
w.add_string('test.str', 'ZXV tensor engine')
w.add_array('tokenizer.ggml.tokens', ['<|endoftext|>', 'a', 'b', 'ab', 'Ġhello', '世'])
w.add_array('test.ints', [1, -2, 3])
w.add_array('test.floats', [0.5, -1.25, 3.0])
w.add_uint32('qwen3.context_length', 40960)

def f16_block_fix(raw, block_bytes, d_offsets):
    raw = raw.reshape(-1, block_bytes)
    for off in d_offsets:
        d = rng.uniform(1e-4, 4e-2, raw.shape[0]).astype(np.float16)
        raw[:, off:off + 2] = d.view(np.uint8).reshape(-1, 2)
    return raw.reshape(-1)

tensors = []
def add(name, typ, data_f32=None, nrow=2, ncol=256):
    if typ == T.F32:
        arr = data_f32.astype(np.float32)
        w.add_tensor(name, arr)
        ref = arr.astype(np.float64)
    elif typ == T.F16:
        arr = data_f32.astype(np.float16)
        w.add_tensor(name, arr)
        ref = arr.astype(np.float64)
    else:
        bs, tb = gguf.GGML_QUANT_SIZES[typ]
        if typ in (T.Q8_0, T.Q4_0, T.BF16):
            q = quants.quantize(data_f32.astype(np.float32), typ)
        else:
            nb = data_f32.size // bs
            q = rng.integers(0, 256, nb * tb, dtype=np.uint8)
            if typ == T.Q4_K: q = f16_block_fix(q, tb, [0, 2])
            if typ == T.Q6_K: q = f16_block_fix(q, tb, [208])
            q = q.reshape(data_f32.shape[0], -1)
        w.add_tensor(name, q, raw_dtype=typ)
        ref = quants.dequantize(q, typ).astype(np.float64).reshape(-1)
    tensors.append((name, int(typ), np.rint(ref.reshape(-1) * 65536).astype(np.int64)))

x = rng.normal(0, 0.05, (2, 256)).astype(np.float32)
x[0, 0] = 1.5; x[0, 1] = -3.25
add('t.f32', T.F32, x)
add('t.f16', T.F16, x)
add('t.bf16', T.BF16, x)
add('t.q8_0', T.Q8_0, x)
add('t.q4_0', T.Q4_0, x)
add('t.q4_k', T.Q4_K, x)
add('t.q6_k', T.Q6_K, x)
w.write_header_to_file(); w.write_kv_data_to_file(); w.write_tensors_to_file(); w.close()
blob = open(path, 'rb').read()

out = ['/* test_gguf_fixture.h — generated by gen_gguf_fixture.py with gguf-py %s.' % getattr(gguf, '__version__', ''),
       ' * A GGUF file from the reference writer, and reference dequantised values', ' * (gguf.quants.dequantize) rounded to Q16. Do not edit. */', '#include <stdint.h>']
out.append('static const uint8_t GGUF_FIXTURE[%d] = {' % len(blob))
for i in range(0, len(blob), 16):
    out.append('    ' + ', '.join('0x%02x' % b for b in blob[i:i + 16]) + ',')
out.append('};')
for name, typ, ref in tensors:
    c = name.replace('.', '_')
    out.append('static const int32_t REF_%s[%d] = {' % (c, ref.size))
    for i in range(0, ref.size, 8):
        out.append('    ' + ', '.join(str(int(v)) for v in ref[i:i + 8]) + ',')
    out.append('};')
out.append('typedef struct { const char *name; uint32_t type; const int32_t *ref; uint32_t n; } gguf_ref_t;')
out.append('static const gguf_ref_t GGUF_REFS[] = {')
for name, typ, ref in tensors:
    out.append('    { "%s", %d, REF_%s, %d },' % (name, typ, name.replace('.', '_'), ref.size))
out.append('};')
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
print(len(blob), 'bytes;', len(tensors), 'tensors')
