# Generate zt_rope_tables.h for zt_rope.c: a 1024-step sine table in Q30
# and the constants 2^(-2^-k) in Q64 (k = 1..56), computed with 80-digit
# decimal arithmetic so every entry is correctly rounded. Usage:
#   python3 gen_rope_tables.py zt_rope_tables.h
import sys
from decimal import Decimal, getcontext
getcontext().prec = 80
LN2 = Decimal(2).ln()
def pi():
    # Machin: pi = 16 atan(1/5) - 4 atan(1/239)
    def atan_inv(x):
        x = Decimal(x); t = 1 / x; s = t; n = 1; x2 = x * x
        while True:
            t /= -x2; n += 2; d = t / n
            if abs(d) < Decimal(10) ** -78: return s
            s += d
    return 16 * atan_inv(5) - 4 * atan_inv(239)
PI = pi()
def sin(x):
    s, t, n = Decimal(0), x, 1
    while abs(t) > Decimal(10) ** -78:
        s += t; t = -t * x * x / ((n + 1) * (n + 2)); n += 2
    return s
def rnd(d): return int(d.to_integral_value(rounding='ROUND_HALF_EVEN'))
out = ['/* zt_rope_tables.h — generated by gen_rope_tables.py. Do not edit. */', '#include <stdint.h>']
out.append('static const int32_t ZT_ROPE_SIN[1024] = {')
vals = [rnd(sin(2 * PI * j / 1024) * 2 ** 30) for j in range(1024)]
for i in range(0, 1024, 8): out.append('    ' + ', '.join(str(v) for v in vals[i:i + 8]) + ',')
out.append('};')
out.append('/* ZT_ROPE_EXP2N[k] = 2^(-2^-k) in Q64, k = 1..56 (entry 0 unused) */')
out.append('static const uint64_t ZT_ROPE_EXP2N[57] = {')
ex = [0] + [rnd((-LN2 / Decimal(2) ** k).exp() * 2 ** 64) for k in range(1, 57)]
for i in range(0, 57, 4): out.append('    ' + ', '.join('0x%016xull' % v for v in ex[i:i + 4]) + ',')
out.append('};')
out.append('#define ZT_ROPE_INV_2PI_Q64 0x%016xull /* 1/(2 pi) */' % rnd(2 ** 64 / (2 * PI)))
out.append('#define ZT_ROPE_HALF_PI_Q62 0x%016xull /* pi/2 */' % rnd(PI / 2 * 2 ** 62))
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
