# Generate zt_tok_unicode.h: code point ranges of Unicode letters (L*) and
# numbers (N*), and white space, from Python's unicodedata, for the
# tokenizer's pre-split (the \p{L}, \p{N} and \s of the Qwen2/GPT-4 pattern).
#   python3 gen_tok_unicode.py zt_tok_unicode.h
import sys, unicodedata
def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(cp)
        if ok and start is None: start = cp
        if not ok and start is not None: out.append((start, cp - 1)); start = None
    if start is not None: out.append((start, 0x10FFFF))
    return out
L = ranges(lambda c: unicodedata.category(chr(c)).startswith('L'))
N = ranges(lambda c: unicodedata.category(chr(c)).startswith('N'))
# \s as Oniguruma and PCRE read it under Unicode: TAB..CR, NEL and the
# Z* separators. Not str.isspace, which also counts U+001C..U+001F.
S = ranges(lambda c: 0x9 <= c <= 0xd or c == 0x85 or unicodedata.category(chr(c)) in ('Zs', 'Zl', 'Zp'))
def emit(name, rs):
    s = 'static const uint32_t %s[%d][2] = {\n' % (name, len(rs))
    for i in range(0, len(rs), 4):
        s += '    ' + ' '.join('{0x%x, 0x%x},' % r for r in rs[i:i+4]) + '\n'
    return s + '};\n'
h = ['/* zt_tok_unicode.h — generated by gen_tok_unicode.py from Python %s' % sys.version.split()[0],
     ' * unicodedata (Unicode %s). Do not edit. */' % unicodedata.unidata_version, '#include <stdint.h>',
     emit('ZT_UNI_L', L), emit('ZT_UNI_N', N), emit('ZT_UNI_S', S)]
open(sys.argv[1], 'w').write('\n'.join(h))
print(len(L), len(N), len(S))
