/* zxv_phase_table.h — GENERATED by build_system/gen_phase_table.sh.
 * DO NOT EDIT AND DO NOT COMMIT A HAND-WRITTEN COPY.
 *
 * One #define per declared module: its l13 phase, derived from its DRC
 * layer (verify_layers.sh layer_of), and where layer_of is silent, from
 * the floor its own local includes impose -- the DRC layer rule read
 * backwards. No number in this file was chosen by a person.
 *
 * A module with NO entry here fails to compile at its ZXV_DECLARE with
 * "'ZXV_PHASE_OF_<name>' undeclared". That is deliberate: a module whose
 * phase cannot be derived must not silently acquire one.
 *
 * src=DRC   layer_of() classified the file or its directory
 * src=FLOOR layer_of() was silent; this is max(layer of local includes)
 */
#ifndef ZXV_PHASE_TABLE_H
#define ZXV_PHASE_TABLE_H

#define ZXV_PHASE_OF_acpi                         4   /* DRC   kernel/src/acpi/acpi.c */
#define ZXV_PHASE_OF_alloc                        2   /* DRC   kernel/src/alloc/alloc.c */
#define ZXV_PHASE_OF_arm32_mmu                    0   /* FLOOR kernel/arch/arm32/arm32_mmu.c */
#define ZXV_PHASE_OF_arm64_mmu                    0   /* FLOOR kernel/arch/arm64/arm64_mmu.c */
#define ZXV_PHASE_OF_audio                        4   /* DRC   kernel/src/audio/audio.c */
#define ZXV_PHASE_OF_bluetooth                    4   /* DRC   kernel/src/bluetooth/bluetooth.c */
#define ZXV_PHASE_OF_bodhi                        5   /* DRC   kernel/src/dharma/bodhi.c */
#define ZXV_PHASE_OF_bootlegger                   8   /* DRC   kernel/src/bootlegger/bootlegger.c */
#define ZXV_PHASE_OF_broker                       3   /* FLOOR kernel/src/broker/broker.c */
#define ZXV_PHASE_OF_browser                      7   /* DRC   kernel/src/browser/browser.c */
#define ZXV_PHASE_OF_chakra                       5   /* DRC   kernel/src/dharma/chakra.c */
#define ZXV_PHASE_OF_chiglet                      5   /* DRC   kernel/src/chiglet/chiglet.c */
#define ZXV_PHASE_OF_choice                       1   /* DRC   kernel/src/choice/choice.c */
#define ZXV_PHASE_OF_concord                      5   /* FLOOR kernel/src/concord/concord.c */
#define ZXV_PHASE_OF_constellation                0   /* FLOOR kernel/src/constellation/constellation_coordinator.c */
#define ZXV_PHASE_OF_cpu_z80                      5   /* DRC   kernel/src/emu/cpu_z80.c */
#define ZXV_PHASE_OF_crit168_os                   0   /* DRC   kernel/src/crit168/crit168_os.c */
#define ZXV_PHASE_OF_crypto_verify                0   /* DRC   kernel/src/robin_debanks/crypto_verify.c */
#define ZXV_PHASE_OF_curzi8889a                   3   /* FLOOR kernel/src/curzi/curzi8889a.c */
#define ZXV_PHASE_OF_denconnect                   0   /* FLOOR kernel/src/denconnect/denconnect.c */
#define ZXV_PHASE_OF_desktop                      7   /* DRC   kernel/src/desktop/desktop.c */
#define ZXV_PHASE_OF_dharana                      0   /* DRC   kernel/src/dharana/dharana.c */
#define ZXV_PHASE_OF_dharma_core                  5   /* DRC   kernel/src/dharma/dharma.c */
#define ZXV_PHASE_OF_display                      5   /* DRC   kernel/src/display/display.c */
#define ZXV_PHASE_OF_dtmf                         4   /* DRC   kernel/src/net/dtmf.c */
#define ZXV_PHASE_OF_ed25519                      0   /* FLOOR kernel/src/robin_debanks/ed25519_verify.c */
#define ZXV_PHASE_OF_edp_risk                     0   /* FLOOR kernel/src/edp_risk/edp_risk.c */
#define ZXV_PHASE_OF_epu                          5   /* DRC   kernel/src/epu/epu_device.c */
#define ZXV_PHASE_OF_event_clock                  1   /* DRC   kernel/src/clock/event_clock.c */
#define ZXV_PHASE_OF_event_transport              0   /* FLOOR kernel/src/event_transport/event_transport.c */
#define ZXV_PHASE_OF_fs                           2   /* DRC   kernel/src/fs/fs.c */
#define ZXV_PHASE_OF_genomic_codon                3   /* DRC   kernel/src/mlkem/genomic_codon.c */
#define ZXV_PHASE_OF_hkdf                         3   /* DRC   kernel/src/tls/hkdf.c */
#define ZXV_PHASE_OF_ipfs                         0   /* FLOOR kernel/src/ipfs/ipfs.c */
#define ZXV_PHASE_OF_iphase                       4   /* DRC   kernel/src/iphase/iphase.c */
#define ZXV_PHASE_OF_karma                        5   /* DRC   kernel/src/dharma/karma.c */
#define ZXV_PHASE_OF_keccak                       3   /* DRC   kernel/src/mlkem/keccak.c */
#define ZXV_PHASE_OF_legal_engine                 11  /* DRC   kernel/src/legal_engine/legal_engine.c */
#define ZXV_PHASE_OF_lpres_attest                 1   /* DRC   kernel/src/lpres/lpres.c */
#define ZXV_PHASE_OF_lpres_core                   1   /* DRC   kernel/src/lpres/lpres_core.c */
#define ZXV_PHASE_OF_m5route                      4   /* DRC   kernel/src/net/m5route.c */
#define ZXV_PHASE_OF_macgyver                     9   /* DRC   kernel/src/macgyver/macgyver.c */
#define ZXV_PHASE_OF_mantra                       5   /* DRC   kernel/src/dharma/mantra.c */
#define ZXV_PHASE_OF_naga_raja                    5   /* DRC   kernel/src/dharma/naga_raja.c */
#define ZXV_PHASE_OF_negtest_cycle_a              3   /* DRC   kernel/src/modbind/modbind.c */
#define ZXV_PHASE_OF_negtest_cycle_b              3   /* DRC   kernel/src/modbind/modbind.c */
#define ZXV_PHASE_OF_negtest_unprovided           3   /* DRC   kernel/src/modbind/modbind.c */
#define ZXV_PHASE_OF_oseq                         1   /* DRC   kernel/src/oseq/oseq_core.c */
#define ZXV_PHASE_OF_panopticon                   5   /* DRC   kernel/src/panopticon/panopticon.c */
#define ZXV_PHASE_OF_panopticon_vpn               5   /* DRC   kernel/src/panopticon/panopticon_vpn.c */
#define ZXV_PHASE_OF_phase_coord                  3   /* DRC   kernel/src/phase_coord/phase_coord.c */
#define ZXV_PHASE_OF_pirate_apps                  6   /* FLOOR kernel/src/pirate_apps/pirate_apps.c */
#define ZXV_PHASE_OF_predictive                   0   /* FLOOR kernel/src/predictive/predictive_model.c */
#define ZXV_PHASE_OF_radio                        4   /* DRC   kernel/src/net/radio.c */
#define ZXV_PHASE_OF_ramdisk                      4   /* FLOOR kernel/arch/arm64/ramdisk.c */
#define ZXV_PHASE_OF_rce_units                    5   /* DRC   kernel/src/rce/rce_units.c */
#define ZXV_PHASE_OF_riscv_mmu                    0   /* FLOOR kernel/arch/riscv/riscv_mmu.c */
#define ZXV_PHASE_OF_rmag                         0   /* DRC   kernel/src/rmag/rmag_core.c */
#define ZXV_PHASE_OF_rur                          9   /* DRC   kernel/src/rur/rur.c */
#define ZXV_PHASE_OF_sephirot                     0   /* DRC   kernel/src/sephirot/sephirot.c */
#define ZXV_PHASE_OF_sha256                       0   /* DRC   kernel/src/robin_debanks/sha256.c */
#define ZXV_PHASE_OF_situation                    0   /* FLOOR kernel/src/situation/situation_model.c */
#define ZXV_PHASE_OF_sms                          5   /* DRC   kernel/src/emu/sms.c */
#define ZXV_PHASE_OF_social                       5   /* FLOOR kernel/src/social_spaces/social.c */
#define ZXV_PHASE_OF_surplus                      0   /* DRC   kernel/src/surplus/surplus.c */
#define ZXV_PHASE_OF_sutra_capital                7   /* DRC   kernel/src/sutra/sutra_capital.c */
#define ZXV_PHASE_OF_sutra_chiglet                7   /* DRC   kernel/src/sutra/sutra_chiglet.c */
#define ZXV_PHASE_OF_sutra_lexer                  7   /* DRC   kernel/src/sutra/sutra_lexer.c */
#define ZXV_PHASE_OF_sutra_parser                 7   /* DRC   kernel/src/sutra/sutra_parser.c */
#define ZXV_PHASE_OF_sutra_rails                  7   /* DRC   kernel/src/sutra/sutra_rails.c */
#define ZXV_PHASE_OF_sutra_runtime                7   /* DRC   kernel/src/sutra/sutra_runtime.c */
#define ZXV_PHASE_OF_sutra_selfaudit              7   /* DRC   kernel/src/sutra/sutra_selfaudit.c */
#define ZXV_PHASE_OF_swarm                        5   /* FLOOR kernel/src/holodeck/swarm.c */
#define ZXV_PHASE_OF_tantra                       5   /* DRC   kernel/src/dharma/tantra.c */
#define ZXV_PHASE_OF_telemetry                    0   /* FLOOR kernel/src/telemetry/telemetry_core.c */
#define ZXV_PHASE_OF_theme                        0   /* FLOOR kernel/src/theme/theme.c */
#define ZXV_PHASE_OF_treaty                       11  /* DRC   kernel/src/legal_engine/legal_engine_ext.c */
#define ZXV_PHASE_OF_trispace                     0   /* FLOOR kernel/src/trispace/trispace.c */
#define ZXV_PHASE_OF_ubh                          0   /* DRC   kernel/src/ubh/ubh.c */
#define ZXV_PHASE_OF_upaah                        0   /* DRC   kernel/src/dharma/upaah.c */
#define ZXV_PHASE_OF_uvn                          5   /* DRC   kernel/src/dharma/uvn.c */
#define ZXV_PHASE_OF_vfs                          1   /* FLOOR kernel/src/vfs/vfs.c */
#define ZXV_PHASE_OF_video                        4   /* DRC   kernel/src/video/video.c */
#define ZXV_PHASE_OF_viewing                      5   /* FLOOR kernel/src/holodeck/viewing.c */
#define ZXV_PHASE_OF_vino                         6   /* DRC   kernel/src/vino/vino.c */
#define ZXV_PHASE_OF_vino_stores                  6   /* DRC   kernel/src/vino_stores/vino_stores.c */
#define ZXV_PHASE_OF_virtio_blk                   4   /* FLOOR kernel/arch/arm64/virtio_blk.c */
#define ZXV_PHASE_OF_virtio_bus                   4   /* DRC   kernel/src/virtio/virtio_bus.c */
#define ZXV_PHASE_OF_virtio_gpu                   4   /* DRC   kernel/src/virtio/virtio_gpu.c */
#define ZXV_PHASE_OF_wifi                         4   /* DRC   kernel/src/wifi/wifi.c */
#define ZXV_PHASE_OF_x86_64_paging                0   /* FLOOR kernel/arch/x86_64/ring3.c */
#define ZXV_PHASE_OF_yantra                       5   /* DRC   kernel/src/dharma/yantra.c */
#define ZXV_PHASE_OF_zsp                          0   /* FLOOR kernel/src/loader/zsp.c */
#define ZXV_PHASE_OF_zxpkg                        9   /* DRC   kernel/src/zxpkg/zxpkg.c */
#define ZXV_PHASE_OF_zxv_ramdisk                  4   /* DRC   kernel/src/blockdev/ramdisk.c */
#define ZXV_PHASE_OF_zxvfs                        2   /* DRC   kernel/src/zxvfs/zxvfs.c */

#endif /* ZXV_PHASE_TABLE_H */
