#!/usr/bin/env python3
# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate zt_e164_codes.h: the assigned ITU-T E.164 country codes.

SOURCE. "List of ITU-T Recommendation E.164 assigned country codes", the
annex to the ITU Operational Bulletin (position as of 15 December 2016, with
the amendments published in later bulletins), ITU, Geneva. The list below
was transcribed by hand from that annex; it has not been machine-checked
against the current bulletin, so re-check it before relying on it for
anything beyond splitting dial strings.

INCLUDED: every code assigned to a country, territory, group of countries or
global service (800 freephone, 808 shared cost, 870 Inmarsat, 881-883 global
mobile/networks, 888 OCHA, 979 premium rate).
OMITTED: spare codes, reserved codes not in use (379 Vatican, 999), and
withdrawn codes (388 ETNS, 671 old Guam, 684 old American Samoa, 878 UPT).
Areas inside +1 (NANP) and +7 have no separate code here.

E.164 country codes are prefix-free by construction (no code is the start
of another), so a dial string splits into a code and a national number in
at most one way. This script checks that property and fails if it breaks.

Usage: python3 gen_e164_codes.py > zt_e164_codes.h
       clang-format -i zt_e164_codes.h   (the checked-in file is formatted)
"""

ONE = [1, 7]
TWO = [20, 27, 30, 31, 32, 33, 34, 36, 39, 40, 41, 43, 44, 45, 46, 47, 48, 49,
       51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 64, 65, 66, 81, 82, 84,
       86, 90, 91, 92, 93, 94, 95, 98]
THREE = (
    [211, 212, 213, 216, 218]
    + list(range(220, 259))  # 220-258 (259 spare)
    + list(range(260, 270))
    + [290, 291, 297, 298, 299]
    + list(range(350, 360))
    + list(range(370, 379))  # 370-378 (379 reserved, not in use)
    + [380, 381, 382, 383, 385, 386, 387, 389]
    + [420, 421, 423]
    + list(range(500, 510))
    + list(range(590, 600))
    + [670, 672, 673, 674, 675, 676, 677, 678, 679]
    + [680, 681, 682, 683, 685, 686, 687, 688, 689, 690, 691, 692]
    + [800, 808]
    + [850, 852, 853, 855, 856]
    + [870, 881, 882, 883, 888]
    + [880, 886]
    + list(range(960, 969))
    + [970, 971, 972, 973, 974, 975, 976, 977, 979]
    + [992, 993, 994, 995, 996, 998]
)


def main():
    codes = sorted(set(ONE + TWO + THREE))
    assert len(codes) == len(ONE) + len(TWO) + len(THREE), "duplicate code"
    s = [str(c) for c in codes]
    for a in s:
        for b in s:
            if a != b and b.startswith(a):
                raise SystemExit("not prefix-free: %s is a prefix of %s" % (a, b))
    print("/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC")
    print(" * SPDX-License-Identifier: Apache-2.0 */")
    print("/* zt_e164_codes.h -- GENERATED by gen_e164_codes.py; do not edit.")
    print(" * Assigned ITU-T E.164 country codes (source and omissions: see the")
    print(" * generator). Sorted ascending; prefix-free (checked by the generator). */")
    print("#ifndef ZT_E164_CODES_H")
    print("#define ZT_E164_CODES_H")
    print("")
    print("#include <stdint.h>")
    print("")
    print("#define ZT_E164_CODE_COUNT %du" % len(codes))
    print("")
    print("static const uint16_t ZT_E164_CODES[ZT_E164_CODE_COUNT] = {")
    for i in range(0, len(codes), 12):
        print("    " + ", ".join("%d" % c for c in codes[i:i + 12]) + ",")
    print("};")
    print("")
    print("#endif /* ZT_E164_CODES_H */")


if __name__ == "__main__":
    main()
