#!/usr/bin/env python3
# Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate zt_harmonic_tables.h: every constant the harmonic module needs
that would otherwise take floating point. Run from this directory:

    python3 gen_harmonic_tables.py > zt_harmonic_tables.h
    clang-format -i zt_harmonic_tables.h   (the checked-in file is formatted)

The kernel never runs this; the output is checked in. Rounding is
round-half-away-from-zero so the output does not depend on the Python build.
"""
import math

FS = 8000
HZ = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1111]
BLOCK = 320              # analysis block = symbol length (see HARMONIC_WIRE.md)
FLOOR_DB = 45            # noise floor, dB below a full-scale tone
BH = [0.35875, 0.48829, 0.14128, 0.01168]  # 4-term Blackman-Harris


def rnd(x):
    return int(math.floor(abs(x) + 0.5)) * (1 if x >= 0 else -1)


def emit(name, ctype, vals, per=8):
    print(f"static const {ctype} {name}[{len(vals)}] = {{")
    for i in range(0, len(vals), per):
        print("    " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
    print("};")


def main():
    w = [2 * math.pi * f / FS for f in HZ]
    coef = [rnd(2 * math.cos(x) * 16384) for x in w]
    cosq = [rnd(math.cos(x) * 16384) for x in w]
    sinq = [rnd(math.sin(x) * 16384) for x in w]
    rot = [(x * BLOCK) % (2 * math.pi) for x in w]
    rcos = [rnd(math.cos(r) * 16384) for r in rot]
    rsin = [rnd(math.sin(r) * 16384) for r in rot]
    step32 = [rnd(f / FS * 2 ** 32) for f in HZ]
    step16 = [f * 65536 // FS for f in HZ]  # the spec's integer step, truncated
    win = []
    for n in range(BLOCK):
        t = 2 * math.pi * n / (BLOCK - 1)
        v = BH[0] - BH[1] * math.cos(t) + BH[2] * math.cos(2 * t) - BH[3] * math.cos(3 * t)
        win.append(min(32767, rnd(v * 32767)))
    qw256 = [rnd(math.sin(math.pi / 2 * i / 256) * 32767) for i in range(257)]
    qw16 = [rnd(math.sin(math.pi / 2 * i / 16) * 32767) for i in range(17)]
    wsum = sum(win)
    # |X| of a full-scale (32767) on-bin tone through (x * w) >> 15
    xfs = 32767 / 2 * wsum / 32768
    pfs = rnd(xfs * xfs)
    floor = rnd(pfs / 10 ** (FLOOR_DB / 10))

    print("/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC")
    print(" * SPDX-License-Identifier: Apache-2.0 */")
    print("/* zt_harmonic_tables.h — GENERATED by gen_harmonic_tables.py; do not edit.")
    print(f" * fs = {FS} Hz, block = {BLOCK} samples, window = 4-term Blackman-Harris,")
    print(f" * noise floor = {FLOOR_DB} dB below a full-scale tone. */")
    print("#ifndef ZT_HARMONIC_TABLES_H")
    print("#define ZT_HARMONIC_TABLES_H")
    print("#include <stdint.h>")
    print(f"#define ZT_TRUNK_BLOCK_SAMPLES {BLOCK}u")
    print(f"#define ZT_TRUNK_WINDOW_SUM {wsum}")
    print(f"#define ZT_TRUNK_P_FULLSCALE {pfs}LL /* Goertzel power of a 32767 tone */")
    print(f"#define ZT_TRUNK_NOISE_FLOOR {floor}LL /* -{FLOOR_DB} dB re full scale */")
    print(f"#define ZT_TRUNK_FLOOR_DB {FLOOR_DB}")
    print("/* Goertzel 2*cos(w) in Q14 (the spec's coefficient) */")
    emit("ZT_TRUNK_COEF_Q14", "int32_t", coef)
    print("/* cos(w), sin(w) in Q14: complex Goertzel output */")
    emit("ZT_TRUNK_COS_Q14", "int32_t", cosq)
    emit("ZT_TRUNK_SIN_Q14", "int32_t", sinq)
    print("/* cos, sin of w * block in Q14: phase advance of a steady carrier per block */")
    emit("ZT_TRUNK_ROT_COS_Q14", "int32_t", rcos)
    emit("ZT_TRUNK_ROT_SIN_Q14", "int32_t", rsin)
    print("/* f / fs * 2^32: 32-bit phase step of the trunk synthesiser */")
    emit("ZT_TRUNK_STEP32", "uint32_t", step32, 5)
    print("/* f * 65536 / fs, truncated: 16-bit phase step of the residual carrier */")
    emit("ZT_RESIDUAL_STEP16", "uint32_t", step16)
    print("/* 4-term Blackman-Harris window, Q15 */")
    emit("ZT_TRUNK_WINDOW_Q15", "int16_t", win, 10)
    print("/* quarter-wave sine, Q15, 256 steps + guard (trunk synthesiser) */")
    emit("ZT_SINE_QW256_Q15", "int16_t", qw256, 10)
    print("/* quarter-wave sine, Q15, 16 steps + guard (residual carrier, per spec) */")
    emit("ZT_SINE_QW16_Q15", "int16_t", qw16, 9)
    print("#endif /* ZT_HARMONIC_TABLES_H */")


if __name__ == "__main__":
    main()
