/* synthesis_engine.c — ZEDEC Synthesis Engine Implementation
 *
 * The core OS-level service for mathematical software fabrication.
 * This engine IS the nonlinear build method, integrated into the OS
 * as a first-class service. Users can fabricate software and hardware
 * mathematically using deterministic models.
 *
 * Author: H.M. Michael-Laurence: Curzi (c)
 * Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC
 * SPDX-License-Identifier: Apache-2.0
 * Licensed under the Apache License, Version 2.0. See LICENSE at
 * the repository root.
 * 36N9 Genetics, LLC — Irrevocable, Interdimensional
 */
#include "synthesis_engine.h"

#ifdef __KERNEL__
#include "freestanding.h"
extern void fb_puts(const char *s);
extern void uart_puts(const char *s);
static void synth_puts(const char *s) {
#ifdef __ARM_ARCH__
    uart_puts(s);
#else
    fb_puts(s);
#endif
}
#else
#include <stdio.h>
#include <string.h>
static void synth_puts(const char *s) { printf("%s", s); }
#endif

/* ===== String helpers (freestanding-safe) ===== */
static int synth_strlen(const char *s) {
    int n = 0; while (s[n]) n++; return n;
}
static void synth_strcpy(char *d, const char *s) {
    while ((*d++ = *s++));
}
static void synth_strncpy(char *d, const char *s, int n) {
    int i; for (i = 0; i < n && s[i]; i++) d[i] = s[i];
    if (i < n) d[i] = '\0';
}
static int synth_strcmp(const char *a, const char *b) {
    while (*a && *a == *b) { a++; b++; }
    return *a - *b;
}
static void synth_strcat(char *d, const char *s) {
    while (*d) d++;
    while ((*d++ = *s++));
}
static void synth_memset(void *p, int v, int n) {
    char *cp = (char*)p; while (n--) *cp++ = v;
}

/* ===== Engine lifecycle ===== */
void synth_engine_init(synthesis_engine_t *engine, uint32_t device_id, const char *name) {
    synth_memset(engine, 0, sizeof(synthesis_engine_t));
    engine->device_id = device_id;
    synth_strncpy(engine->name, name, SYNTH_MAX_NAME_LEN - 1);
    engine->status = SYNTH_STATUS_IDLE;
    engine->target = SYNTH_TARGET_C;
    engine->mode = SYNTH_MODE_KERNEL_MODULE;
    engine->optimize_level = 2;
    engine->root = &engine->ast_nodes[0];

    /* Initialize root AST node */
    engine->ast_nodes[0].type = AST_ROOT;
    synth_strcpy(engine->ast_nodes[0].name, "root");
    engine->num_ast_nodes = 1;

    /* Load built-in templates */
    synth_template_load(engine, "kernel_module",
                        "/* AUTO-GENERATED by ZEDEC Synthesis Engine */\n"
                        "/* Module: {MODULE_NAME} */\n"
                        "/* Author: H.M. Michael-Laurence: Curzi (c) */\n"
                        "/* SPDX-License-Identifier: Apache-2.0 */\n"
                        "#include \"{MODULE_NAME}.h\"\n\n"
                        "void {MODULE_NAME}_init(void) {\n"
                        "    /* TODO: Initialize module */\n"
                        "}\n");

    synth_template_load(engine, "hw_device",
                        "/* AUTO-GENERATED: Hardware-as-Code Device */\n"
                        "/* Device: {DEVICE_NAME} */\n"
                        "/* Author: H.M. Michael-Laurence: Curzi (c) */\n"
                        "/* SPDX-License-Identifier: Apache-2.0 */\n"
                        "#include \"{DEVICE_NAME}.h\"\n\n"
                        "void {DEVICE_NAME}_init({DEVICE_NAME}_t *dev) {\n"
                        "    synth_memset(dev, 0, sizeof(*dev));\n"
                        "    /* TODO: Initialize device registers */\n"
                        "}\n");

    synth_template_load(engine, "systemverilog",
                        "// AUTO-GENERATED: SystemVerilog HDL\n"
                        "// Module: {MODULE_NAME}\n"
                        "// Author: H.M. Michael-Laurence: Curzi (c)\n"
                        "// SPDX-License-Identifier: Apache-2.0\n"
                        "module {MODULE_NAME} (\n"
                        "    input logic clk,\n"
                        "    input logic rst_n,\n"
                        "    // TODO: Add ports\n"
                        ");\n\n"
                        "endmodule\n");
}

int synth_engine_reset(synthesis_engine_t *engine) {
    engine->status = SYNTH_STATUS_IDLE;
    engine->spec_len = 0;
    engine->num_ast_nodes = 1;
    engine->num_gates = 0;
    engine->result.success = false;
    engine->result.output_len = 0;
    synth_memset(engine->spec_input, 0, SYNTH_MAX_SPEC_LEN);
    synth_memset(engine->result.output, 0, SYNTH_MAX_OUTPUT_LEN);
    return 0;
}

/* ===== Register access ===== */
uint64_t synth_reg_read(synthesis_engine_t *engine, synth_reg_t reg) {
    if (reg >= SYNTH_NUM_REGISTERS) return 0;
    switch (reg) {
        case REG_STATUS:       return engine->status;
        case REG_COVERAGE_R:
            return (uint64_t) (uint32_t) engine->coverage_r;
        case REG_COVERAGE_L:
            return (uint64_t) (uint32_t) engine->coverage_l;
        case REG_SURPLUS:
            return (uint64_t) (uint32_t) engine->result.surplus;
        case REG_RISK:
            return (uint64_t) (uint32_t) engine->result.risk;
        case REG_GATE_COUNT:   return engine->num_gates;
        case REG_NODE_COUNT:   return engine->num_ast_nodes;
        case REG_OUTPUT_LEN:   return engine->result.output_len;
        default:               return engine->registers[reg];
    }
}

void synth_reg_write(synthesis_engine_t *engine, synth_reg_t reg, uint64_t value) {
    if (reg >= SYNTH_NUM_REGISTERS) return;
    switch (reg) {
        case REG_TARGET_LANG:  engine->target = (synth_target_t)value; break;
        case REG_MODE:         engine->mode = (synth_mode_t)value; break;
        case REG_TEMPLATE_ID:  engine->active_template = (uint32_t)value; break;
        case REG_OPTIMIZE:     engine->optimize_level = (uint8_t)value; break;
        case REG_CONTROL:
            if (value & SYNTH_CTRL_START) {
                synth_engine_execute(engine, &engine->result);
            }
            if (value & SYNTH_CTRL_RESET) {
                synth_engine_reset(engine);
            }
            break;
        default:
            engine->registers[reg] = value;
    }
}

/* ===== DMA operations ===== */
int synth_dma_write_spec(synthesis_engine_t *engine, const char *spec, uint32_t len) {
    if (len >= SYNTH_MAX_SPEC_LEN) return -1;
    synth_strncpy(engine->spec_input, spec, len);
    engine->spec_input[len] = '\0'; /* strncpy-style copy leaves it open at len */
    engine->spec_len = len;
    return 0;
}

int synth_dma_read_output(synthesis_engine_t *engine, char *output, uint32_t max_len) {
    uint32_t copy_len = engine->result.output_len;
    if (copy_len > max_len) copy_len = max_len;
    synth_strncpy(output, engine->result.output, copy_len);
    return copy_len;
}

/* ===== AST operations ===== */
ast_node_t *synth_ast_add_node(synthesis_engine_t *engine, ast_node_type_t type, const char *name) {
    if (engine->num_ast_nodes >= SYNTH_MAX_AST_NODES) return 0;
    ast_node_t *node = &engine->ast_nodes[engine->num_ast_nodes++];
    node->type = type;
    synth_strncpy(node->name, name, SYNTH_MAX_NAME_LEN - 1);
    node->num_children = 0;
    node->parent = engine->root;
    return node;
}

/* ===== Spec parsing (simplified) ===== */
int synth_parse_spec(synthesis_engine_t *engine, const char *spec, uint32_t len) {
    engine->status = SYNTH_STATUS_PARSING;
    if (len == 0) len = synth_strlen(spec);
    synth_dma_write_spec(engine, spec, len);

    /* Parse module name from spec (look for "module:" keyword) */
    const char *p = spec;
    while (*p) {
        if (p[0] == 'm' && p[1] == 'o' && p[2] == 'd' && p[3] == 'u' &&
            p[4] == 'l' && p[5] == 'e' && p[6] == ':') {
            p += 7;
            char name[128]; int i = 0;
            while (*p && *p != '\n' && *p != ' ' && i < 127) name[i++] = *p++;
            name[i] = '\0';
            synth_ast_add_node(engine, AST_MODULE_DECL, name);
        }
        if (p[0] == 'd' && p[1] == 'e' && p[2] == 'v' && p[3] == 'i' &&
            p[4] == 'c' && p[5] == 'e' && p[6] == ':') {
            p += 7;
            char name[128]; int i = 0;
            while (*p && *p != '\n' && *p != ' ' && i < 127) name[i++] = *p++;
            name[i] = '\0';
            synth_ast_add_node(engine, AST_STRUCT_DECL, name);
        }
        if (!*p) break; /* a name ending the spec leaves p on the NUL: stop */
        p++;
    }

    engine->status = SYNTH_STATUS_IDLE;
    return engine->num_ast_nodes - 1;
}

/* ===== Axiom verification ===== */
bool synth_verify_axioms(synthesis_engine_t *engine) {
    engine->status = SYNTH_STATUS_VERIFYING;
    /* Check M5 coverage: r × ℓ ≥ 1.8 */
    bool ok = synth_check_coverage(engine);
    if (!ok) {
        engine->status = SYNTH_STATUS_COVERAGE_FAIL;
        engine->irq_coverage_violation = true;
    }
    engine->status = SYNTH_STATUS_IDLE;
    return ok;
}

bool synth_check_coverage(synthesis_engine_t *engine) {
    return (int64_t) engine->coverage_r * engine->coverage_l >= SYNTH_COVERAGE_FLOOR_Q32;
}

/* ===== Second quantization gates ===== */
int synth_gate_create(synthesis_engine_t *engine, uint32_t source, uint32_t target,
                      int32_t amplitude)
{
    if (engine->num_gates >= SYNTH_MAX_GATES) return -1;
    synth_gate_t *g = &engine->gates[engine->num_gates++];
    g->op = GATE_CREATE;
    g->source_node = source;
    g->target_node = target;
    g->amplitude = amplitude;
    g->phase = 0;
    g->applied = false;
    return 0;
}

int synth_gate_annihilate(synthesis_engine_t *engine, uint32_t node) {
    if (engine->num_gates >= SYNTH_MAX_GATES) return -1;
    synth_gate_t *g = &engine->gates[engine->num_gates++];
    g->op = GATE_ANNIHILATE;
    g->source_node = node;
    g->target_node = node;
    g->amplitude = Q16_ONE;
    g->applied = false;
    return 0;
}

int synth_gate_entangle(synthesis_engine_t *engine, uint32_t node1, uint32_t node2) {
    if (engine->num_gates >= SYNTH_MAX_GATES) return -1;
    synth_gate_t *g = &engine->gates[engine->num_gates++];
    g->op = GATE_ENTANGLE;
    g->source_node = node1;
    g->target_node = node2;
    g->amplitude = Q16_CONST(707, 1000); /* 0.707 ~ 1/√2 for maximally entangled state */
    g->phase = 0;
    g->applied = false;
    return 0;
}

int synth_gate_measure(synthesis_engine_t *engine) {
    if (engine->num_gates >= SYNTH_MAX_GATES) return -1;
    synth_gate_t *g = &engine->gates[engine->num_gates++];
    g->op = GATE_MEASURE;
    g->source_node = 0;
    g->target_node = 0;
    g->amplitude = Q16_ONE;
    g->applied = false;
    return 0;
}

int synth_apply_gates(synthesis_engine_t *engine) {
    for (uint32_t i = 0; i < engine->num_gates; i++) {
        synth_gate_t *g = &engine->gates[i];
        if (g->applied) continue;

        switch (g->op) {
            case GATE_CREATE:
                /* Creation: add AST node for new code element */
                if (g->target_node < engine->num_ast_nodes) {
                    /* integer part of the amplitude (negative counts as 0) */
                    engine->ast_nodes[g->target_node].m5.omega +=
                        g->amplitude > 0 ? (uint32_t) (g->amplitude >> 16) : 0u;
                }
                break;
            case GATE_ANNIHILATE:
                /* Annihilation: mark node as dead (remove dead code) */
                if (g->source_node < engine->num_ast_nodes) {
                    engine->ast_nodes[g->source_node].m5.omega = 0;
                    engine->ast_nodes[g->source_node].m5.r = SR_ZERO;
                }
                break;
            case GATE_ENTANGLE:
                /* Entanglement: link two modules' M5 coordinates */
                if (g->source_node < engine->num_ast_nodes &&
                    g->target_node < engine->num_ast_nodes) {
                    engine->ast_nodes[g->source_node].m5.phi =
                        engine->ast_nodes[g->target_node].m5.phi;
                }
                break;
            case GATE_MEASURE:
                /* Measurement: collapse to output — triggers code generation */
                engine->status = SYNTH_STATUS_GENERATING;
                break;
            default:
                break;
        }
        g->applied = true;
        engine->total_gates_applied++;
    }

    /* Update M5 coverage from gate operations */
    int64_t total_amplitude = 0;
    for (uint32_t i = 0; i < engine->num_gates; i++) {
        total_amplitude += engine->gates[i].amplitude;
    }
    engine->coverage_r = (int32_t) fx_sdiv64(
        total_amplitude, (int64_t) (engine->num_gates > 0 ? engine->num_gates : 1));
    int64_t cl = fx_sdiv64((int64_t) engine->num_ast_nodes * Q16_ONE, 10); /* nodes / 10 */
    engine->coverage_l = cl > INT32_MAX ? INT32_MAX : (int32_t) cl;
    if (engine->coverage_l < Q16_CONST(1, 10)) engine->coverage_l = Q16_CONST(1, 10);

    return 0;
}

/* ===== ISF surplus optimization ===== */
int32_t synth_compute_surplus(synthesis_engine_t *engine)
{
    /* f(u) = ln(1 + (N-1)u) where N = nodes, u = utilization (Q16.16).
     * ln x = log2 x * ln 2, with ln 2 = 45426 / 65536. */
    uint32_t N = engine->num_ast_nodes;
    if (N < 2) return 0;
    int64_t val = Q16_ONE + (int64_t) (N - 1) * engine->coverage_r;
    if (val <= 0) return 0;
    return (int32_t) fx_mul_q16(fx_log2_q16((uint64_t) val), 45426);
}

int32_t synth_optimize_surplus(synthesis_engine_t *engine)
{
    /* Optimize gate amplitudes to maximize surplus */
    int32_t best_surplus = synth_compute_surplus(engine);
    for (uint32_t i = 0; i < engine->num_gates; i++) {
        int32_t orig = engine->gates[i].amplitude;
        /* Try scaling amplitude by 0.5, 0.75, ..., 2.0 (Q16.16 steps) */
        for (int32_t scale = Q16_ONE / 2; scale <= 2 * Q16_ONE; scale += Q16_ONE / 4) {
            int64_t a = fx_mul_q16(orig, scale);
            engine->gates[i].amplitude = a > INT32_MAX   ? INT32_MAX
                                         : a < INT32_MIN ? INT32_MIN
                                                         : (int32_t) a;
            int32_t s = synth_compute_surplus(engine);
            if (s > best_surplus) {
                best_surplus = s;
            } else {
                engine->gates[i].amplitude = orig;
            }
        }
    }
    engine->result.surplus = best_surplus;
    if (best_surplus > Q16_CONST(3, 2)) {
        engine->irq_surplus_optimal = true;
    }
    return best_surplus;
}

/* ===== EDP risk assessment ===== */
int32_t synth_assess_risk(synthesis_engine_t *engine)
{
    /* Risk = 1 - coverage / (coverage + 1.8) (simplified EDP risk), Q16.16 */
    int64_t coverage = fx_mul_q16(engine->coverage_r, engine->coverage_l);
    int64_t den = coverage + Q16_CONST(9, 5);
    int64_t risk = den != 0 ? Q16_ONE - fx_sdiv64(coverage * Q16_ONE, den) : Q16_ONE;
    if (risk < 0) risk = 0;
    if (risk > Q16_ONE) risk = Q16_ONE;
    engine->result.risk = (int32_t) risk;
    if (risk > Q16_CONST(7, 10)) {
        engine->irq_risk_threshold = true;
        engine->status |= SYNTH_STATUS_RISK_HIGH;
    }
    return (int32_t) risk;
}

/* ===== Nonlinear compilation ===== */
int synth_nonlinear_compile(synthesis_engine_t *engine) {
    engine->status = SYNTH_STATUS_COMPILING;

    /* Apply all pending gates */
    synth_apply_gates(engine);

    /* Optimize surplus */
    synth_optimize_surplus(engine);

    /* Assess risk */
    synth_assess_risk(engine);

    /* Verify axioms */
    if (!synth_verify_axioms(engine)) {
        engine->status = SYNTH_STATUS_COVERAGE_FAIL;
        return -1;
    }

    engine->status = SYNTH_STATUS_IDLE;
    return 0;
}

/* ===== Code generation ===== */
static void synth_append(char *buf, uint32_t *offset, uint32_t max, const char *text) {
    int len = synth_strlen(text);
    if (*offset + len >= max) len = max - *offset - 1;
    for (int i = 0; i < len; i++) buf[*offset + i] = text[i];
    *offset += len;
    buf[*offset] = '\0';
}

static void synth_substitute(char *dst, const char *template, const char *var, const char *val) {
    int ti = 0, di = 0;
    int varlen = synth_strlen(var);
    while (template[ti]) {
        if (template[ti] == '{') {
            /* Check if matches variable */
            int match = 1;
            for (int j = 0; j < varlen; j++) {
                if (template[ti + 1 + j] != var[j]) { match = 0; break; }
            }
            if (match && template[ti + 1 + varlen] == '}') {
                int vlen = synth_strlen(val);
                for (int j = 0; j < vlen; j++) dst[di++] = val[j];
                ti += varlen + 2;
                continue;
            }
        }
        dst[di++] = template[ti++];
    }
    dst[di] = '\0';
}

int synth_generate_code(synthesis_engine_t *engine, synth_target_t target, synth_result_t *result) {
    engine->status = SYNTH_STATUS_GENERATING;
    engine->target = target;
    result->target = target;
    result->output_len = 0;
    synth_memset(result->output, 0, SYNTH_MAX_OUTPUT_LEN);

    /* Find module name from AST */
    char module_name[128] = "synthesized_module";
    for (uint32_t i = 0; i < engine->num_ast_nodes; i++) {
        if (engine->ast_nodes[i].type == AST_MODULE_DECL ||
            engine->ast_nodes[i].type == AST_STRUCT_DECL) {
            synth_strncpy(module_name, engine->ast_nodes[i].name, 127);
            break;
        }
    }

    /* Select template based on target and mode */
    synth_template_t *tmpl = 0;
    switch (target) {
        case SYNTH_TARGET_SYSTEMVERILOG:
        case SYNTH_TARGET_VHDL:
        case SYNTH_TARGET_CHISEL:
            tmpl = synth_template_find(engine, "systemverilog");
            break;
        case SYNTH_TARGET_C:
        default:
            if (engine->mode == SYNTH_MODE_HW_DEVICE) {
                tmpl = synth_template_find(engine, "hw_device");
            } else {
                tmpl = synth_template_find(engine, "kernel_module");
            }
            break;
    }

    if (!tmpl) {
        result->success = false;
        synth_strcpy(result->error_msg, "No suitable template found");
        engine->status = SYNTH_STATUS_ERROR;
        return -1;
    }

    /* Substitute variables in template */
    char substituted[SYNTH_MAX_OUTPUT_LEN];
    if (engine->mode == SYNTH_MODE_HW_DEVICE) {
        synth_substitute(substituted, tmpl->template_text, "DEVICE_NAME", module_name);
    } else {
        synth_substitute(substituted, tmpl->template_text, "MODULE_NAME", module_name);
    }

    synth_append(result->output, &result->output_len, SYNTH_MAX_OUTPUT_LEN, substituted);

    /* Add M5 coverage info as comment */
    char coverage_comment[256];
    /* Simple number-to-string for coverage values */
    int r_int = (int) fx_mul_q16(engine->coverage_r, 1000); /* thousandths */
    int l_int = (int) fx_mul_q16(engine->coverage_l, 1000);
    /* Build coverage comment manually */
    synth_strcpy(coverage_comment, "\n/* M5 Coverage: r=");
    /* Simple integer to string */
    int pos = synth_strlen(coverage_comment);
    if (r_int < 0) { coverage_comment[pos++] = '-'; r_int = -r_int; }
    int divisor = 1000;
    while (divisor > 0) {
        int digit = (r_int / divisor) % 10;
        if (digit > 0 || pos > 18 || divisor == 1) {
            coverage_comment[pos++] = '0' + digit;
        }
        if (divisor == 1000) coverage_comment[pos++] = '.';
        divisor /= 10;
    }
    coverage_comment[pos] = '\0';
    synth_strcat(coverage_comment, " l=");
    pos = synth_strlen(coverage_comment);
    divisor = 1000;
    while (divisor > 0) {
        int digit = (l_int / divisor) % 10;
        if (digit > 0 || pos > 23 || divisor == 1) {
            coverage_comment[pos++] = '0' + digit;
        }
        if (divisor == 1000) coverage_comment[pos++] = '.';
        divisor /= 10;
    }
    coverage_comment[pos] = '\0';
    synth_strcat(coverage_comment, " */\n");
    synth_append(result->output, &result->output_len, SYNTH_MAX_OUTPUT_LEN, coverage_comment);

    /* Set results */
    result->coverage_r = engine->coverage_r;
    result->coverage_l = engine->coverage_l;
    result->surplus = engine->result.surplus;
    result->risk = engine->result.risk;
    result->gates_applied = engine->num_gates;
    result->nodes_generated = engine->num_ast_nodes;
    result->success = true;

    engine->status = SYNTH_STATUS_DONE;
    engine->irq_synthesis_complete = true;
    engine->total_syntheses++;
    engine->successful_syntheses++;
    engine->total_lines_generated += result->output_len / 80; /* approx lines */

    return 0;
}

int synth_generate_module(synthesis_engine_t *engine, const char *module_name, synth_result_t *result) {
    synth_ast_add_node(engine, AST_MODULE_DECL, module_name);
    engine->mode = SYNTH_MODE_KERNEL_MODULE;
    return synth_generate_code(engine, SYNTH_TARGET_C, result);
}

int synth_generate_hw_device(synthesis_engine_t *engine, const char *device_name, synth_result_t *result) {
    synth_ast_add_node(engine, AST_STRUCT_DECL, device_name);
    engine->mode = SYNTH_MODE_HW_DEVICE;
    return synth_generate_code(engine, SYNTH_TARGET_C, result);
}

int synth_generate_hdl(synthesis_engine_t *engine, synth_target_t target, synth_result_t *result) {
    engine->mode = SYNTH_MODE_HDL_ARTIFACT;
    return synth_generate_code(engine, target, result);
}

/* ===== Template management ===== */
int synth_template_load(synthesis_engine_t *engine, const char *name, const char *template_text) {
    if (engine->num_templates >= SYNTH_MAX_TEMPLATES) return -1;
    synth_template_t *t = &engine->templates[engine->num_templates++];
    synth_memset(t, 0, sizeof(*t));
    synth_strncpy(t->name, name, SYNTH_MAX_NAME_LEN - 1);
    t->target = SYNTH_TARGET_C;
    t->mode = SYNTH_MODE_KERNEL_MODULE;
    int len = synth_strlen(template_text);
    if (len >= SYNTH_MAX_OUTPUT_LEN) len = SYNTH_MAX_OUTPUT_LEN - 1;
    synth_strncpy(t->template_text, template_text, len);
    t->template_len = len;
    t->min_coverage_r = Q16_ONE / 2;
    t->min_coverage_l = Q16_ONE / 2;
    return 0;
}

int synth_template_select(synthesis_engine_t *engine, uint32_t template_id) {
    if (template_id >= engine->num_templates) return -1;
    engine->active_template = template_id;
    return 0;
}

synth_template_t *synth_template_find(synthesis_engine_t *engine, const char *name) {
    for (uint32_t i = 0; i < engine->num_templates; i++) {
        if (synth_strcmp(engine->templates[i].name, name) == 0) {
            return &engine->templates[i];
        }
    }
    return 0;
}

/* ===== Main execution pipeline ===== */
int synth_engine_execute(synthesis_engine_t *engine, synth_result_t *result) {
    engine->total_syntheses++;

    /* Phase 1: Parse spec */
    if (engine->spec_len > 0) {
        synth_parse_spec(engine, engine->spec_input, engine->spec_len);
    }

    /* Phase 2: Apply gates (second quantization) */
    synth_apply_gates(engine);

    /* Phase 3: Nonlinear compilation */
    if (synth_nonlinear_compile(engine) != 0) {
        result->success = false;
        synth_strcpy(result->error_msg, "Nonlinear compilation failed — coverage violation");
        engine->status = SYNTH_STATUS_ERROR;
        engine->failed_syntheses++;
        engine->irq_error = true;
        return -1;
    }

    /* Phase 4: Generate code */
    if (synth_generate_code(engine, engine->target, result) != 0) {
        result->success = false;
        engine->status = SYNTH_STATUS_ERROR;
        engine->failed_syntheses++;
        engine->irq_error = true;
        return -1;
    }

    /* Phase 5: Final verification */
    if (!synth_check_coverage(engine)) {
        result->success = false;
        synth_strcpy(result->error_msg, "Final coverage check failed — r × ℓ < 1.8");
        engine->status = SYNTH_STATUS_COVERAGE_FAIL;
        engine->failed_syntheses++;
        engine->irq_coverage_violation = true;
        return -1;
    }

    engine->status = SYNTH_STATUS_DONE;
    engine->irq_synthesis_complete = true;
    return 0;
}

/* ===== IRQ handling ===== */
void synth_handle_irq(synthesis_engine_t *engine) {
    if (engine->irq_synthesis_complete) {
        engine->irq_synthesis_complete = false;
    }
    if (engine->irq_coverage_violation) {
        engine->irq_coverage_violation = false;
    }
    if (engine->irq_surplus_optimal) {
        engine->irq_surplus_optimal = false;
    }
    if (engine->irq_risk_threshold) {
        engine->irq_risk_threshold = false;
    }
    if (engine->irq_error) {
        engine->irq_error = false;
    }
}

/* ===== Diagnostics ===== */
const char *synth_status_string(uint8_t status) {
    if (status & SYNTH_STATUS_ERROR) return "ERROR";
    if (status & SYNTH_STATUS_COVERAGE_FAIL) return "COVERAGE_FAIL";
    if (status & SYNTH_STATUS_DONE) return "DONE";
    if (status & SYNTH_STATUS_GENERATING) return "GENERATING";
    if (status & SYNTH_STATUS_COMPILING) return "COMPILING";
    if (status & SYNTH_STATUS_VERIFYING) return "VERIFYING";
    if (status & SYNTH_STATUS_PARSING) return "PARSING";
    return "IDLE";
}

const char *synth_target_string(synth_target_t target) {
    switch (target) {
        case SYNTH_TARGET_C:             return "C";
        case SYNTH_TARGET_HEADER:        return "HEADER";
        case SYNTH_TARGET_SYSTEMVERILOG: return "SystemVerilog";
        case SYNTH_TARGET_VHDL:          return "VHDL";
        case SYNTH_TARGET_CHISEL:        return "Chisel";
        case SYNTH_TARGET_PYTHON:        return "Python";
        case SYNTH_TARGET_MAKEFILE:      return "Makefile";
        case SYNTH_TARGET_LINKER_SCRIPT: return "LinkerScript";
        case SYNTH_TARGET_BOOT_ASM:      return "BootAsm";
        default: return "Unknown";
    }
}

const char *synth_mode_string(synth_mode_t mode) {
    switch (mode) {
        case SYNTH_MODE_KERNEL_MODULE: return "KERNEL_MODULE";
        case SYNTH_MODE_HW_DEVICE:     return "HW_DEVICE";
        case SYNTH_MODE_DRIVER:        return "DRIVER";
        case SYNTH_MODE_PROTOCOL:      return "PROTOCOL";
        case SYNTH_MODE_FINANCIAL:     return "FINANCIAL";
        case SYNTH_MODE_CRYPTO:        return "CRYPTO";
        case SYNTH_MODE_TEST:          return "TEST";
        case SYNTH_MODE_APPLICATION:   return "APPLICATION";
        case SYNTH_MODE_HDL_ARTIFACT:  return "HDL_ARTIFACT";
        case SYNTH_MODE_CUSTOM:        return "CUSTOM";
        default: return "Unknown";
    }
}

const char *synth_gate_string(gate_op_t op) {
    switch (op) {
        case GATE_CREATE:      return "CREATE";
        case GATE_ANNIHILATE:  return "ANNIHILATE";
        case GATE_NUMBER:      return "NUMBER";
        case GATE_DISPLACEMENT:return "DISPLACEMENT";
        case GATE_SQUEEZE:     return "SQUEEZE";
        case GATE_ROTATION:    return "ROTATION";
        case GATE_ENTANGLE:    return "ENTANGLE";
        case GATE_MEASURE:     return "MEASURE";
        default: return "Unknown";
    }
}

void synth_dump_state(synthesis_engine_t *engine) {
    synth_puts("=== ZEDEC Synthesis Engine State ===\n");
    synth_puts("  Status: ");
    synth_puts(synth_status_string(engine->status));
    synth_puts("\n  Target: ");
    synth_puts(synth_target_string(engine->target));
    synth_puts("\n  Mode: ");
    synth_puts(synth_mode_string(engine->mode));
    synth_puts("\n  AST Nodes: ");
    /* Simple number print would go here */
    synth_puts("\n  Gates: ");
    synth_puts("\n  Coverage: ");
    synth_puts("\n  Surplus: ");
    synth_puts("\n  Risk: ");
    synth_puts("\n  Total Syntheses: ");
    synth_puts("\n=====================================\n");
}

const char *synth_engine_generate_hdl(synthesis_engine_t *engine, const char *language) {
    (void)engine;
    return language;
}
