/* Copyright (c) 2024-2026 Michael Laurence Curzi and 36N9 Genetics, LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/* i18n.h — locales, message catalogs, number/currency/date formatting, and
 * UTF-8 text helpers for the ZXV user interface.
 *
 * WHERE THE DATA COMES FROM
 *   Locale registry, plural rules, separators, digits, currency patterns and
 *   symbols, month and day names, date patterns, relative-time strings:
 *   Unicode CLDR 48.2.0 (cldr-json), generated by gen_i18n_tables.py. Every
 *   CLDR locale is present (765 tags, root excluded), plus 13 CLDR lacks (Kanuri, Kongo,
 *   Seychellois Creole, Comorian, Aymara, Nahuatl, Yucatec Maya, Samoan,
 *   Romani, Aramaic, Assyrian Neo-Aramaic, Sanskrit in IAST); those use CLDR
 *   root formats and are flagged (i18n_locale_flags() lacks I18N_LF_CLDR).
 *   UI messages: catalog/<tag>.msg. English is the source text. Every other
 *   hand-written line is MACHINE TRANSLATION that NEEDS NATIVE REVIEW, and
 *   i18n_msg() reports that status with every string so the UI can say so.
 *
 * THE CORE NEVER CHANGES LANGUAGE
 *   A message id (i18n_msgid_t, and its stable key from i18n_msg_key()) is the
 *   core's internal identifier. The swarm stores and passes ids; translation
 *   to the operator's chosen language happens only at the edge, in i18n_msg().
 *   Choosing a language changes nothing in the core (swarm_enochian.h, E8).
 *   i18n_enochian.h connects the two.
 *
 * HONEST LIMITS
 *   - Gregorian calendar only. CLDR also has Ethiopic, Islamic, Hebrew,
 *     Persian, Buddhist and other calendars; they are not built in.
 *   - Grapheme clusters follow UAX #29 extended clusters closely (marks,
 *     ZWJ emoji, regional-indicator pairs, Hangul, Indic virama conjuncts,
 *     common Prepend marks) but not every rule of every Unicode version.
 *   - Message arguments are isolated with FSI/PDI for bidirectional text; the
 *     full Unicode Bidirectional Algorithm (UAX #9) is the renderer's job.
 *   - No rounding: numbers are formatted exactly from integers. The caller
 *     decides precision.
 *
 * Freestanding: integer only, no libc, no allocation, no 64-bit division.
 * All writers are bounded: they return the byte length written (excluding
 * the NUL), or -1 if the output did not fit, in which case the buffer holds
 * a NUL-terminated prefix cut at a grapheme boundary.
 */
#ifndef ZXV_I18N_H
#define ZXV_I18N_H

#include <stdint.h>
#include <stdbool.h>
#include "i18n_msgid.h"

typedef struct i18n_loc i18n_locale_t;

typedef struct {
    uint32_t lo, hi;
} i18n_range_t;

typedef enum { I18N_ZERO = 0, I18N_ONE, I18N_TWO, I18N_FEW, I18N_MANY, I18N_OTHER } i18n_plural_t;

typedef enum {
    I18N_REVIEW_SOURCE = 0,  /* the English original                         */
    I18N_REVIEW_CLDR = 1,    /* from Unicode CLDR: authoritative             */
    I18N_REVIEW_MACHINE = 2, /* machine translation: NEEDS NATIVE REVIEW     */
    I18N_REVIEW_NATIVE = 3   /* checked by a named native speaker            */
} i18n_review_t;

typedef enum {
    I18N_DATE_FULL = 0,
    I18N_DATE_LONG,
    I18N_DATE_MEDIUM,
    I18N_DATE_SHORT
} i18n_date_style_t;

typedef enum {
    I18N_COVERAGE_NONE = 0, /* not in CLDR: root formats                 */
    I18N_COVERAGE_BASIC,
    I18N_COVERAGE_MODERATE,
    I18N_COVERAGE_MODERN
} i18n_coverage_t;

/* i18n_locale_flags() bits */
#define I18N_LF_CLDR         1u  /* the locale is in CLDR                    */
#define I18N_LF_AUTONYM_CLDR 2u  /* the autonym is CLDR's, not ours          */
#define I18N_LF_PLURALS_CLDR 4u  /* CLDR has plural rules for it             */
#define I18N_LF_MONTH_NAMES  8u  /* CLDR has real month names (not M01..M12) */
#define I18N_LF_DERIVED      16u /* derived by transliteration (sa-Latn)     */

/* i18n_fmt_currency() flags */
#define I18N_CUR_NARROW 1u /* narrow symbol ("$" rather than "US$")          */
#define I18N_CUR_CODE   2u /* always show the ISO code                       */

/* ===== locale registry ===== */
uint32_t i18n_locale_count(void);
const i18n_locale_t *i18n_locale_at(uint32_t i);
/* Exact tag (case-insensitive, '_' accepted for '-'), or NULL. */
const i18n_locale_t *i18n_locale_find(const char *tag);
/* Best available locale for a requested tag: aliases (tl -> fil, iw -> he),
 * script inference from region (zh-TW -> zh-Hant, sr-ME -> sr-Latn), then
 * truncation (sw-TZ -> sw). Never NULL: falls back to English. */
const i18n_locale_t *i18n_locale_resolve(const char *tag);
const i18n_locale_t *i18n_locale_default(void); /* en */
/* CLDR inheritance parent (sw-KE -> sw; pt-AO -> pt-PT -> pt), NULL at the top. */
const i18n_locale_t *i18n_locale_parent(const i18n_locale_t *l);
const char *i18n_locale_tag(const i18n_locale_t *l);
const char *i18n_locale_english(const i18n_locale_t *l);
const char *i18n_locale_autonym(const i18n_locale_t *l);
const char *i18n_locale_script(const i18n_locale_t *l);      /* ISO 15924, "Latn" */
const char *i18n_locale_territories(const i18n_locale_t *l); /* "KE TZ UG"        */
const char *i18n_locale_au_states(const i18n_locale_t *l);   /* AU members only   */
const char *i18n_locale_currency(const i18n_locale_t *l);    /* for region tags   */
const char *i18n_locale_numbering(const i18n_locale_t *l);   /* "latn", "arab"    */
bool i18n_locale_rtl(const i18n_locale_t *l);
uint32_t i18n_locale_flags(const i18n_locale_t *l);
i18n_coverage_t i18n_locale_coverage(const i18n_locale_t *l);
uint32_t i18n_locale_digit(const i18n_locale_t *l, uint32_t d); /* codepoint */
/* Codepoint ranges the locale's exemplar characters, punctuation and digits
 * need (from CLDR). *gaps gets how many of those codepoints
 * kernel/src/font/script.c classifies as SCRIPT_UNKNOWN when generated. */
uint32_t i18n_locale_needs(const i18n_locale_t *l, const i18n_range_t **ranges, uint32_t *gaps);

/* ===== plurals (CLDR cardinal rules) ===== */
i18n_plural_t i18n_plural(const i18n_locale_t *l, uint64_t n);
/* For a decimal: value = scaled / 10^frac_digits, digits as written, so
 * (150, 2) is "1.50" (English: other) and (1, 0) is "1" (English: one). */
i18n_plural_t i18n_plural_decimal(const i18n_locale_t *l, uint64_t scaled, uint32_t frac_digits);
/* Categories the locale uses, as a bit set of (1 << i18n_plural_t). */
uint32_t i18n_plural_categories(const i18n_locale_t *l);

/* ===== messages ===== */
typedef struct {
    const i18n_locale_t *from; /* locale whose catalog supplied the text      */
    i18n_review_t review;
    const char *note; /* CLDR path, reviewer:date, "translit:sa", or ""       */
    bool fallback;    /* text came from a locale other than the one asked     */
} i18n_msg_info_t;

/* The text of a plain message, walking the fallback chain (sw-KE -> sw -> en).
 * Never NULL. `info` may be NULL. */
const char *i18n_msg(const i18n_locale_t *l, i18n_msgid_t id, i18n_msg_info_t *info);
/* A plural message, the form chosen by i18n_plural(l, n). */
const char *i18n_msg_plural(const i18n_locale_t *l, i18n_msgid_t id, uint64_t n,
                            i18n_msg_info_t *info);
const char *i18n_msg_key(i18n_msgid_t id); /* "NAV_WALLET"; the core identifier */
int32_t i18n_msg_id(const char *key);      /* key -> id, or -1                   */
/* Substitute {0}..{9} with args. When the locale is RTL or an argument holds
 * right-to-left text, each argument is wrapped in FSI (U+2068) .. PDI (U+2069)
 * so numbers and names keep their own direction. */
int32_t i18n_format_msg(const i18n_locale_t *l, const char *tmpl, const char *const *args,
                        uint32_t nargs, char *out, uint32_t cap);

/* ===== numbers ===== */
int32_t i18n_fmt_int(const i18n_locale_t *l, int64_t v, char *out, uint32_t cap);
/* value = scaled / 10^frac_digits, all digits shown: (82, 2) -> "0.82". */
int32_t i18n_fmt_decimal(const i18n_locale_t *l, int64_t scaled, uint32_t frac_digits, char *out,
                         uint32_t cap);
/* A percentage given in percent units: (4000, 2) -> "40%"; (162, 2) -> "1.62%". */
int32_t i18n_fmt_percent(const i18n_locale_t *l, int64_t scaled, uint32_t frac_digits, char *out,
                         uint32_t cap);
/* Money from minor units: (2500, "USD", 2) -> "$25.00" in en. `exponent` is
 * the number of minor-unit digits (ISO 4217; i18n_currency_digits() gives
 * CLDR's). `symbol` overrides the locale's symbol (e.g. "VFV"), or NULL. */
int32_t i18n_fmt_currency(const i18n_locale_t *l, int64_t minor, const char *iso, uint32_t exponent,
                          uint32_t flags, const char *symbol, char *out, uint32_t cap);
const char *i18n_currency_symbol(const i18n_locale_t *l, const char *iso, bool narrow);
uint32_t i18n_currency_digits(const char *iso); /* CLDR fraction digits, default 2 */

/* ===== dates (proleptic Gregorian, days since 1970-01-01) ===== */
void i18n_civil_from_days(int32_t days, int32_t *y, uint32_t *m, uint32_t *d);
int32_t i18n_days_from_civil(int32_t y, uint32_t m, uint32_t d);
uint32_t i18n_weekday(int32_t days); /* 0 = Sunday */
int32_t i18n_fmt_date(const i18n_locale_t *l, int32_t days, i18n_date_style_t style, char *out,
                      uint32_t cap);
const char *i18n_month_name(const i18n_locale_t *l, uint32_t month, bool wide, bool standalone);
const char *i18n_day_name(const i18n_locale_t *l, uint32_t weekday, bool wide);

/* ===== UTF-8 and graphemes ===== */
/* Strict validation (no overlongs, surrogates or > U+10FFFF). *bad gets the
 * offset of the first bad byte when it returns false (may be NULL). */
bool i18n_utf8_valid(const uint8_t *s, uint32_t len, uint32_t *bad);
/* Decode one scalar. Returns its length, or -1 (and *cp = U+FFFD) if
 * malformed; the caller then skips one byte. len == 0 returns 0. */
int32_t i18n_utf8_decode(const uint8_t *s, uint32_t len, uint32_t *cp);
uint32_t i18n_utf8_encode(uint32_t cp, uint8_t out[4]); /* 0 if not a scalar */
/* Copy, replacing each malformed byte sequence with U+FFFD. */
int32_t i18n_utf8_sanitize(const uint8_t *s, uint32_t len, char *out, uint32_t cap);
bool i18n_is_grapheme_extend(uint32_t cp);
/* Offset of the next grapheme-cluster boundary after `off`. */
uint32_t i18n_grapheme_next(const uint8_t *s, uint32_t len, uint32_t off);
uint32_t i18n_grapheme_count(const uint8_t *s, uint32_t len);
/* Longest prefix of at most max_bytes that ends on a grapheme boundary. */
uint32_t i18n_truncate(const uint8_t *s, uint32_t len, uint32_t max_bytes);
/* Same, appending "…" (3 bytes) when it had to cut; result <= max_bytes. */
int32_t i18n_truncate_ellipsis(const uint8_t *s, uint32_t len, uint32_t max_bytes, char *out,
                               uint32_t cap);

const char *i18n_data_version(void); /* "CLDR 48.2.0, Unicode 15.1.0" */

#endif /* ZXV_I18N_H */
